packages/battery_plus_web/pubspec.yaml, packages/connectivity_plus_macos/pubspec.yaml, packages/connectivity_plus_web/pubspec.yaml, packages/device_info_plus_web/pubspec.yaml, packages/package_info_plus_macos/pubspec.yaml, packages/package_info_plus_web/pubspec.yaml, packages/sensors_plus_web/pubspec.yaml
Does your PR require plugin users to manually update their apps to accommodate your …
=> Bump up the Flutter version

packages/package_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
Fix running Android example in `package_info_plus`. 
Without this change, running the example on Android results in: https://github.com/flutter/flutter/issues/51195
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/master/CONTRIBUTING.md …
=> delete and recreate example gradle folder and gradlew

README.md
=> [WIP] Fix #34 with correct platform support info.

packages/connectivity_plus/README.md
Use flutter.dev instead of flutter.io
=> [connectivity_plus] Use flutter.dev instead of flutter.io

packages/android_intent_plus/pubspec.yaml, packages/device_info_plus_linux/pubspec.yaml, packages/share_plus_linux/pubspec.yaml
Fixes `melos bootstrap` on Linux. Tested on master & dev channels.
=> Update packages with nullsafety constraints

.github/workflows/all_plugins.yaml, .github/workflows/scripts/install-flutter.sh
Aim to fix https://github.com/fluttercommunity/plus_plugins/issues/52
=> Enable unsecure commands on ci

packages/android_intent_plus/CHANGELOG.md, packages/android_intent_plus/android/src/main/AndroidManifest.xml, packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/AndroidIntentPlugin.java, packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java, packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java, packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/EmbeddingV1Activity.java, packages/android_intent_plus/example/pubspec.yaml, packages/android_intent_plus/lib/android_intent.dart, packages/android_intent_plus/pubspec.yaml
=> [android_intent_plus] rename method channel and java package. See #56

packages/battery_plus/example/linux/.gitignore, packages/battery_plus/example/linux/CMakeLists.txt, packages/battery_plus/example/linux/flutter/CMakeLists.txt, packages/battery_plus/example/linux/flutter/generated_plugin_registrant.cc, packages/battery_plus/example/linux/flutter/generated_plugin_registrant.h, packages/battery_plus/example/linux/flutter/generated_plugins.cmake, packages/battery_plus/example/linux/main.cc, packages/battery_plus/example/linux/my_application.cc, packages/battery_plus/example/linux/my_application.h, packages/battery_plus/lib/battery_plus.dart, packages/battery_plus/pubspec.yaml, packages/battery_plus_linux/.gitignore, packages/battery_plus_linux/.metadata, packages/battery_plus_linux/CHANGELOG.md, packages/battery_plus_linux/LICENSE, packages/battery_plus_linux/README.md, packages/battery_plus_linux/analysis_options.yaml, packages/battery_plus_linux/lib/battery_plus_linux.dart, packages/battery_plus_linux/lib/src/battery_linux.dart, packages/battery_plus_linux/lib/src/upower_device.dart, packages/battery_plus_linux/pubspec.yaml, packages/battery_plus_linux/test/battery_plus_linux_test.dart
moved from here https://github.com/fluttercommunity/battery_plus/pull/5
=> Add Linux Support to Battery Plus

packages/package_info_plus/example/linux/.gitignore, packages/package_info_plus/example/linux/CMakeLists.txt, packages/package_info_plus/example/linux/flutter/CMakeLists.txt, packages/package_info_plus/example/linux/flutter/generated_plugin_registrant.cc, packages/package_info_plus/example/linux/flutter/generated_plugin_registrant.h, packages/package_info_plus/example/linux/flutter/generated_plugins.cmake, packages/package_info_plus/example/linux/main.cc, packages/package_info_plus/example/linux/my_application.cc, packages/package_info_plus/example/linux/my_application.h, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/lib/package_info_plus.dart, packages/package_info_plus/pubspec.yaml, packages/package_info_plus/test/package_info_test.dart, packages/package_info_plus_linux/.gitignore, packages/package_info_plus_linux/.metadata, packages/package_info_plus_linux/CHANGELOG.md, packages/package_info_plus_linux/LICENSE, packages/package_info_plus_linux/README.md, packages/package_info_plus_linux/lib/package_info_plus_linux.dart, packages/package_info_plus_linux/lib/src/package_info.dart, packages/package_info_plus_linux/pubspec.yaml
Requires https://github.com/flutter/flutter/pull/69920
=> Add Linux support to Package Info Plus

README.md, website/plugins.js
https://pub.dev/packages/package_info_plus_linux
=> Add package_info_linux to README & website

packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/example/lib/main.dart, packages/connectivity_plus/example/test_driver/connectivity_plus_e2e.dart, packages/connectivity_plus/lib/connectivity_plus.dart, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/test/connectivity_test.dart
The will be removed in the next minor release.
=> [connectivity_plus] deprecate members moved to network_info_plus

README.md, packages/android_alarm_manager_plus/README.md, packages/android_intent_plus/README.md, packages/battery_plus/README.md, packages/connectivity_plus/README.md, packages/device_info_plus/README.md, packages/network_info_plus/README.md, packages/package_info_plus/README.md, packages/sensors_plus/README.md, packages/share_plus/README.md
Adding platform support table for each individual plugin's README.md.
Closes #111
=> [all] Adding platform support table for each individual plugin's README.md

packages/device_info_plus/CHANGELOG.md, packages/device_info_plus/example/lib/main.dart, packages/device_info_plus/example/linux/flutter/CMakeLists.txt, packages/device_info_plus/example/linux/flutter/generated_plugin_registrant.cc, packages/device_info_plus/example/pubspec.yaml, packages/device_info_plus/example/test_driver/device_info_plus_e2e.dart, packages/device_info_plus/lib/device_info_plus.dart, packages/device_info_plus/pubspec.yaml, packages/device_info_plus_linux/CHANGELOG.md, packages/device_info_plus_linux/lib/src/device_info.dart, packages/device_info_plus_linux/pubspec.yaml, packages/device_info_plus_macos/CHANGELOG.md, packages/device_info_plus_macos/pubspec.yaml, packages/device_info_plus_platform_interface/CHANGELOG.md, packages/device_info_plus_platform_interface/lib/model/android_device_info.dart, packages/device_info_plus_platform_interface/lib/model/ios_device_info.dart, packages/device_info_plus_platform_interface/lib/model/linux_device_info.dart, packages/device_info_plus_platform_interface/lib/model/macos_device_info.dart, packages/device_info_plus_platform_interface/lib/model/web_browser_info.dart, packages/device_info_plus_platform_interface/pubspec.yaml, packages/device_info_plus_platform_interface/test/method_channel_device_info_test.dart, packages/device_info_plus_web/CHANGELOG.md, packages/device_info_plus_web/pubspec.yaml
Work for #50 migrated device_info to null safety
=> [device_info_plus] migrate to null safety

.github/workflows/build_deploy_website.yaml, website/package-lock.json, website/package.json, website/src/pages/docs.tsx
=> Website build fix

packages/share_plus/README.md
I switched from share to share_plus in order to get my app to also work on Windows, but due to lack of documentation, I couldn't notice existing limitations until running the app. I think README should include the descriptions of them.
None.
=> Update README.md about limitations on Windows and Linux

docs/android_alarm_manager_plus/overview.mdx, docs/android_alarm_manager_plus/usage.mdx, docs/android_intent_plus/overview.mdx, docs/android_intent_plus/usage.mdx, docs/device_info_plus/overview.mdx, docs/device_info_plus/usage.mdx, docs/network_info_plus/overview.mdx, docs/network_info_plus/usage.mdx, docs/package_info_plus/overview.mdx, docs/package_info_plus/usage.mdx, docs/sensors_plus/overview.mdx, docs/sensors_plus/usage.mdx, docs/share_plus/overview.mdx, docs/share_plus/usage.mdx
add missing documents
- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ x] All existing and new tests are passing.
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide].
- [ x] I am willing to follow-up on review comments in a timely manner. …
=> add missing documents for the doc website

docs/network_info_plus/usage.mdx, packages/network_info_plus/README.md
=> Update network_info_plus readme

packages/share_plus_web/CHANGELOG.md, packages/share_plus_web/pubspec.yaml
Does your PR require plugin users to manually update their apps to accommodate your …
=> share_plus_web 2.0.2

packages/share_plus_macos/CHANGELOG.md, packages/share_plus_macos/macos/Classes/SharePlusMacosPlugin.swift, packages/share_plus_macos/pubspec.yaml
=> [share_plus_macos] obtain Flutter view from the registrar

packages/connectivity_plus/README.md
Does your PR require plugin users to manually update their apps to accommodate your …
=> Corrected a typo.

.github/workflows/all_plugins.yaml, melos.yaml, packages/device_info_plus_platform_interface/lib/model/android_device_info.dart
It seems format command is failing hope this is fixing this script. 
https://github.com/fluttercommunity/plus_plugins/issues/223
=> fix(melos): fix melos format script

packages/android_alarm_manager_plus/README.md, packages/android_intent_plus/README.md, packages/battery_plus/README.md, packages/connectivity_plus/README.md, packages/device_info_plus/README.md, packages/network_info_plus/README.md, packages/package_info_plus/README.md, packages/sensors_plus/README.md, packages/share_plus/README.md
to show flutter team does not accept non-critical prs for plus that we support in plus plugins
https://github.com/fluttercommunity/plus_plugins/issues/173
=> Add a note to all readmes to mention important note from Flutter team

packages/connectivity_plus/README.md
Correct the package import for this package in docs, probably stale from past package renaming action. Just a minor docs change to help newcomers to the plugin really.
=> [connectivity_plus]: minor fix of import of README.md

packages/connectivity_plus/README.md
changed import 'package:connectivity_plus/connectivity.dart'; to import 'package:connectivity_plus/connectivity_plus.dart';
This will ensure a smooth and quick review process. Updating the …
=> correct connectivity readme import filename

packages/network_info_plus_linux/CHANGELOG.md, packages/network_info_plus_linux/lib/src/network_manager.dart, packages/network_info_plus_linux/pubspec.yaml
Upgrade dependencies & regenerate mocks.
#244
=> [network_info_plus_linux] upgrade dependencies

packages/battery_plus_linux/CHANGELOG.md, packages/battery_plus_linux/lib/src/upower_device.dart, packages/battery_plus_linux/pubspec.yaml, packages/battery_plus_linux/test/battery_plus_linux_test.dart
Upgrade dependencies & regenerate mocks.
#244
=> [battery_plus_linux] upgrade dependencies

packages/device_info_plus/README.md
=> Fix README.md

docs/network_info_plus/usage.mdx, packages/network_info_plus/network_info_plus/README.md
This PR increases readability of usage section by declaring a variable for the plugin and reusing it.
Does not changes anything code related.
None.
=> Improve readability of usage

packages/device_info_plus/device_info_plus/CHANGELOG.md, packages/device_info_plus/device_info_plus/pubspec.yaml, packages/device_info_plus/device_info_plus_linux/CHANGELOG.md, packages/device_info_plus/device_info_plus_linux/pubspec.yaml, packages/device_info_plus/device_info_plus_macos/CHANGELOG.md, packages/device_info_plus/device_info_plus_macos/pubspec.yaml, packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md, packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml, packages/device_info_plus/device_info_plus_web/CHANGELOG.md, packages/device_info_plus/device_info_plus_web/pubspec.yaml, packages/device_info_plus/device_info_plus_windows/CHANGELOG.md, packages/device_info_plus/device_info_plus_windows/pubspec.yaml
Just pump version and add changelog
=> add toMap to models and pump device info versions

packages/device_info_plus/device_info_plus/pubspec.yaml
=> pump device_info_plus main package to 2.1.0

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
=> update changelog connectivity 1.0.5

packages/package_info_plus/package_info_plus/pubspec.yaml, packages/package_info_plus/package_info_plus_linux/pubspec.yaml, packages/package_info_plus/package_info_plus_web/pubspec.yaml, packages/package_info_plus/package_info_plus_windows/pubspec.yaml
Just updating packages versions for package info plus to be up-to-date
=> update all deps for package info

packages/battery_plus/battery_plus/pubspec.yaml, packages/battery_plus/battery_plus_linux/CHANGELOG.md, packages/battery_plus/battery_plus_linux/pubspec.yaml, packages/battery_plus/battery_plus_macos/CHANGELOG.md, packages/battery_plus/battery_plus_macos/pubspec.yaml, packages/battery_plus/battery_plus_platform_interface/CHANGELOG.md, packages/battery_plus/battery_plus_web/CHANGELOG.md, packages/battery_plus/battery_plus_web/pubspec.yaml, packages/battery_plus/battery_plus_windows/CHANGELOG.md, packages/battery_plus/battery_plus_windows/pubspec.yaml
=> update all deps for battery plus

packages/sensors_plus/sensors_plus/README.md
Changed typo of "Platfrom" to "Platform"
*Changed typo of "Platfrom" to  "Platform"* …
=> Spell check changes

packages/battery_plus/battery_plus/CHANGELOG.md, packages/battery_plus/battery_plus/pubspec.yaml
=> add changelog and pump version

CONTRIBUTING.md
I have forked and cloned this project and following guide for contributing and found few directory path as per older directory structure which can be fixed as per current directory structures. …
=> docs: fix few directory paths on CONTRIBUTING.md

.github/workflows/all_plugins.yaml
Looks like in my recent changes to CI config I forgot to run `melos bootstrap`, which might caused some issues, like mentioned here: https://github.com/fluttercommunity/plus_plugins/pull/571#issuecomment-949550055
This PR fixes the issue. …
=> [CI] Add missing melos bootstrap

packages/android_intent_plus/example/lib/main.dart, packages/android_intent_plus/example/pubspec.yaml, packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
*I made this modification to make the example compatible with null safety.
I am still a beginner, but I do not understand why the packaged does not have the Null safety activated.
If there is a logical reason, please let me know and therefore refuse my changes.*
*Not related to any PR.
I took the initiative using the example that was provided.* …
=> Compatible with null safety

packages/android_alarm_manager_plus/README.md
corrected test file name for android_alarm_manager_plus readme.
=> Updated README.md

packages/android_alarm_manager_plus/example/test_driver/android_alarm_manager_plus_e2e.dart, packages/connectivity_plus/connectivity_plus/example/lib/main.dart, packages/device_info_plus/device_info_plus_platform_interface/lib/method_channel/method_channel_device_info.dart, packages/sensors_plus/sensors_plus/test/sensors_test.dart, packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart, packages/share_plus/share_plus/example/lib/image_previews.dart
Fix lint issues appearing from the Flutter 2.8.0 upgrade
=> [all] Fix lint issues from Flutter 2.8.0

packages/sensors_plus/sensors_plus/CHANGELOG.md, packages/sensors_plus/sensors_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/sensors_plus/sensors_plus/example/android/app/src/main/AndroidManifest.xml, packages/sensors_plus/sensors_plus/example/android/build.gradle, packages/sensors_plus/sensors_plus/pubspec.yaml, packages/share_plus/share_plus/CHANGELOG.md, packages/share_plus/share_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/share_plus/share_plus/example/android/app/src/main/AndroidManifest.xml, packages/share_plus/share_plus/example/android/build.gradle, packages/share_plus/share_plus/pubspec.yaml
Another PR in series to fix embedding issues after update to Flutter 2.10. 
Additionally updated Android Gradle plugin and Gradle wrapper version.
=> [sensors_plus] [share_plus] Fix example embedding, update Gradle plugin and wrapper

packages/network_info_plus/network_info_plus/example/android/app/src/main/AndroidManifest.xml, packages/network_info_plus/network_info_plus/example/android/build.gradle
Another PR in series to fix embedding issues after update to Flutter 2.10. Also, updated Android Gradle plugin in example app.
=> [network_info_plus] Fix example embedding

packages/share_plus/share_plus/CHANGELOG.md, packages/share_plus/share_plus/README.md, packages/share_plus/share_plus/example/ios/Flutter/AppFrameworkInfo.plist, packages/share_plus/share_plus/example/ios/Flutter/Flutter.podspec, packages/share_plus/share_plus/example/ios/Runner.xcodeproj/project.pbxproj, packages/share_plus/share_plus/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/share_plus/share_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/share_plus/share_plus/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/share_plus/share_plus/example/ios/Runner/Info.plist, packages/share_plus/share_plus/pubspec.yaml
Adds documentation regarding iPad requirement to use share_plus.
- https://github.com/fluttercommunity/plus_plugins/issues/305
- https://github.com/fluttercommunity/plus_plugins/issues/897
- https://github.com/fluttercommunity/plus_plugins/issues/870
- https://github.com/fluttercommunity/plus_plugins/issues/701
- https://github.com/fluttercommunity/plus_plugins/issues/658
- and more
=> [share_plus] add documentation iPad

docs/share_plus/usage.mdx
There was a wrong condition in the share_plus documentation for the success case.
NA
- [] All existing and new tests are passing.
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] I am willing to follow-up on review comments in a timely manner.
[pub …
=> fix success condition for share result

melos.yaml
Bumped `flutter_lints` used in Melos config, so we are on par with lints version used by plugins. Also removed the upper limit on Flutter version as don't see a need in it and because we already have Flutter 3 released.
-
- [] The analyzer (`flutter analyze`) does not report any problems on my PR. …
=> Update Melos config

packages/device_info_plus/device_info_plus/CHANGELOG.md, packages/device_info_plus/device_info_plus/pubspec.yaml, packages/device_info_plus/device_info_plus_windows/CHANGELOG.md, packages/device_info_plus/device_info_plus_windows/pubspec.yaml
=> [device_info_plus_windows] Update ffi to 2.0.1

packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart
The current test is whether it is a non-null value.
This is a GSoC task, so there are no associated issues for now.
=> test(network_info_plus): Integration test

packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
I have now completed the integration testing of its Wi-Fi functionality.
This is a GSoC task, so there are no associated issues for now.
=> test(connectivity_plus): Integration test

packages/sensors_plus/sensors_plus/CHANGELOG.md, packages/sensors_plus/sensors_plus/ios/Classes/FLTSensorsPlusPlugin.m, packages/sensors_plus/sensors_plus/pubspec.yaml
- Providing additional fixes for the crash issue when closing application.
https://github.com/fluttercommunity/plus_plugins/pull/981
=> [sensors_plus] Fix crash issue on closing application

packages/device_info_plus/device_info_plus/CHANGELOG.md, packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart, packages/device_info_plus/device_info_plus/example/lib/main.dart, packages/device_info_plus/device_info_plus/pubspec.yaml, packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md, packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart, packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml, packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_test.dart
- Revert "Remove androidId (#1007)"
- Version bump
=> Revert 4.1.0 device_info_plus changes

packages/device_info_plus/device_info_plus_windows/CHANGELOG.md, packages/device_info_plus/device_info_plus_windows/pubspec.yaml
This PR updates the `win32` dependency to avoid version conflicts in the near future.
Example: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/6
=> [device_info_plus] Update win32

packages/package_info_plus/package_info_plus_windows/CHANGELOG.md, packages/package_info_plus/package_info_plus_windows/pubspec.yaml
This PR updates the `win32` dependency to avoid version conflicts in the near future.
Example: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/6
=> [package_info_plus] Update win32

packages/android_intent_plus/example/integration_test/android_intent_plus_test.dart
Now our integration test just supports the Android platform.
This is a GSoC task, so there are no associated issues for now.
=> test(android_intent_plus): Integration test

packages/android_alarm_manager_plus/CHANGELOG.md, packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart, packages/android_alarm_manager_plus/pubspec.yaml
added entry point to resolve 3.3.0 lookup issue
#1061
=> add pragma entry point

packages/share_plus/share_plus/CHANGELOG.md
Added missing `#` to CHANGELOG.
=> [share_plus] Add missing `#` to CHANGELOG

packages/share_plus/share_plus/CHANGELOG.md, packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m, packages/share_plus/share_plus/pubspec.yaml
Revert patch 4.2.0 on share_plus
- #1081
- #1079
=> Revert "[share_plus] Fix Instagram does not show up in provider list for web links (#1079)"

.github/workflows/battery_plus.yaml, .github/workflows/connectivity_plus.yaml, .github/workflows/device_info_plus.yaml, .github/workflows/network_info_plus.yaml, .github/workflows/package_info_plus.yaml, .github/workflows/scripts/integration-test.sh, .github/workflows/sensors_plus.yaml, .github/workflows/share_plus.yaml
Doing some work we did not finish with the GSOC.
I am enabling the integration_test to run on iOS.
=> Enable integration_test run on iOS Simulator

packages/android_alarm_manager_plus/CHANGELOG.md, packages/android_alarm_manager_plus/README.md, packages/android_alarm_manager_plus/pubspec.yaml
Just a short FAQ for AlarmManager
=> alarm manager faq

.github/workflows/build_deploy_website.yaml
Fixing deployment script by using https://github.com/FirebaseExtended/action-hosting-deploy Action. Should work fine after @mhadaily added proper Google Service account JSON into the repo.
Suggest to test by merging the PR.
Closes #969  …
=> [website] Replace deploy Action

.github/workflows/build_preview_website.yaml
After fixing website deployment I am introducing additional workflow for our CI to build and deploy previews of website changes in PRs. It would allow us to be sure that nothing is broken before merging when somebody changes something related to Plus Plugins website.
Followed [the official guide](https://firebase.google.com/docs/hosting/github-integration), so expect it to work properly right away 🙂 …
=> [website] Workflow to deploy preview of changes in PRs

packages/android_intent_plus/LICENSE
* Corrected BSD-3 licence
[Bug]: No correc LICENCE file for BSD licence #937
fix(android_intent_plus): fixed a bug!  #937
- [✅ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ✅] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ✅] All existing and new tests are passing.
- [ ✅] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [ ✅] I updated/added relevant documentation (doc comments with `///`).
- [ ✅] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [✅ ] I read and …
=> corrected BSD-3-Clause License

website/docusaurus.config.js
Edit this page website was not working before, Now fixed
=> fixed broken 'Edit this page' Link in the Website

website/docusaurus.config.js, website/src/theme/MDXComponents/index.tsx
[Fixed] Every Admonitions are now working on every page.
No experience in working with react, let me know if anything is wrong.
#1117 
=> [website] Fixed admonitions

packages/share_plus/share_plus/CHANGELOG.md, packages/share_plus/share_plus/README.md, packages/share_plus/share_plus/example/lib/image_previews.dart, packages/share_plus/share_plus/example/lib/main.dart, packages/share_plus/share_plus/lib/share_plus.dart, packages/share_plus/share_plus/pubspec.yaml, packages/share_plus/share_plus_platform_interface/CHANGELOG.md, packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart, packages/share_plus/share_plus_platform_interface/lib/share_plus_platform_interface.dart, packages/share_plus/share_plus_platform_interface/pubspec.yaml, packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart, packages/share_plus/share_plus_web/CHANGELOG.md, packages/share_plus/share_plus_web/lib/share_plus_web.dart, packages/share_plus/share_plus_web/pubspec.yaml
This PR is a continuation of #318.
There were a few issues in that original implementation:
- The int arrays were passed as a concatenated int string to the sharing program
- File name being forgotten
- Mime Types missing (causing `Permission Denied` errors)
- The `withResult` implementations were missing
- The examples were not updated properly
- Tests were missing
This PR aims at fixing these issues as they seemed to be the remaining ones.
Also, I have tested the feature on Chrome (Android + PC) and Edge (PC) and it worked in my test cases (multiple files, different mime types etc.).
Firefox is sadly not supported (due to Browser limitations, see [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility) for details).
Fixes #212
Before you create this …
=> [share_plus] Enable Web implementations for `shareFiles`

packages/package_info_plus/package_info_plus_web/CHANGELOG.md, packages/package_info_plus/package_info_plus_web/lib/package_info_plus_web.dart, packages/package_info_plus/package_info_plus_web/pubspec.yaml, packages/package_info_plus/package_info_plus_web/test/package_info_plus_web_test.dart
`dart:core`'s `Uri.origin` does not support schemes other than `http` and `https`. This PR adds a workaround by extending the `Uri` class with an `_origin` getter which returns the origin for `chrome-extensions://` w/o throwing `StateError` by combining `Uri.scheme` and `Uri.host`.
This will enable ONLY `chrome-extensions` other than `http` and `https`, nothing else, going along the same lines as dart sdk authors did by preventing anything other than `http` and `https`. If there is some other use case, adding support for that will be trivial.
Fixes #1134
Does your PR require plugin users to manually update their apps …
=> [package_info_plus] add support for chrome-extensions

packages/share_plus/share_plus_platform_interface/CHANGELOG.md, packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart, packages/share_plus/share_plus_platform_interface/pubspec.yaml
=> Fix #1161 add missing import

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Updated the CONTRIBUTING.md with what we discussed today in the all-hands meeting.
Heavily inspired by https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md#the-release-process :heart: 
=> docs: Update CONTRIBUTING.md

packages/android_alarm_manager_plus/CHANGELOG.md, packages/android_alarm_manager_plus/pubspec.yaml, packages/android_intent_plus/CHANGELOG.md, packages/android_intent_plus/pubspec.yaml, packages/battery_plus/battery_plus/CHANGELOG.md, packages/battery_plus/battery_plus/pubspec.yaml, packages/connectivity_plus/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/connectivity_plus/pubspec.yaml, packages/device_info_plus/device_info_plus/CHANGELOG.md, packages/device_info_plus/device_info_plus/pubspec.yaml, packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md, packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml, packages/network_info_plus/network_info_plus/CHANGELOG.md, packages/network_info_plus/network_info_plus/pubspec.yaml, packages/package_info_plus/package_info_plus/CHANGELOG.md, packages/package_info_plus/package_info_plus/pubspec.yaml, packages/sensors_plus/sensors_plus/CHANGELOG.md, packages/sensors_plus/sensors_plus/pubspec.yaml, packages/share_plus/share_plus/CHANGELOG.md, packages/share_plus/share_plus/pubspec.yaml
=> chore(release): prepare for release

.github/dependabot.yml, packages/device_info_plus/device_info_plus/android/build.gradle, packages/device_info_plus/device_info_plus/android/gradle/wrapper/gradle-wrapper.properties, packages/device_info_plus/device_info_plus/example/android/build.gradle, packages/device_info_plus/device_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
Same as #1261 - updating Kotlin, Gradle and adding a Dependabot config for Android dependencies.
#1248 
#1222 
=> chore(device_info_plus): Update Kotlin, Gradle and add Dependabot config

packages/android_alarm_manager_plus/example/lib/main.dart, packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart, packages/android_intent_plus/example/pubspec.yaml, packages/battery_plus/battery_plus/example/lib/main.dart, packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart, packages/network_info_plus/network_info_plus/example/lib/main.dart, packages/network_info_plus/network_info_plus/test/network_info_test.dart, packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart, packages/share_plus/share_plus/test/share_plus_linux_test.dart, packages/share_plus/share_plus/test/share_plus_windows_test.dart, packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
Fixes a bunch of depreciation for Flutter 3.7 and dart 2.19
=> fix(all): Fix depreciations for flutter 3.7 and 2.19 dart

.github/PULL_REQUEST_TEMPLATE.md
Fixing the typo that confuses some people in the checklist for PR, like here: https://github.com/fluttercommunity/plus_plugins/pull/1768#issuecomment-1532068192
=> chore(github_templates): Fix the checklist item typo

packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart, packages/battery_plus/battery_plus/example/lib/main.dart, packages/battery_plus/battery_plus/example/pubspec.yaml, packages/battery_plus/battery_plus/pubspec.yaml, packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
=> chore(battery_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

packages/android_alarm_manager_plus/android/build.gradle
=> chore(android_alarm_manager)!: Bump min Android version

README.md, packages/android_alarm_manager_plus/README.md, packages/android_intent_plus/README.md, packages/battery_plus/battery_plus/README.md, packages/connectivity_plus/connectivity_plus/README.md, packages/device_info_plus/device_info_plus/README.md, packages/network_info_plus/network_info_plus/README.md, packages/package_info_plus/package_info_plus/README.md, packages/sensors_plus/sensors_plus/README.md, packages/share_plus/share_plus/README.md
- Updated emojis used in platform support table to make them more visible for users with dark theme on Github website/app. 
- Unified README files titles
=> docs(all): Update READMEs

packages/share_plus/share_plus/example/ios/Runner.xcodeproj/project.pbxproj, packages/share_plus/share_plus/pubspec.yaml
Same as #1851 and #1852 - adding more relaxed constraints for `file` dependency.
=> chore(share_plus): Update file dependency constraints

docs/connectivity_plus/usage.mdx
Saw that website had outdated `Usage` page for `connectivity_plus`, so synced it with `README` file.
=> docs(connectivity_plus): Update usage documentation on website

packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart
=> fix(android_alarm_manager_plus): Fix documentation typo

.github/workflows/connectivity_plus.yaml
=> ci(connectivity_plus): Remove Java installation step

.github/workflows/device_info_plus.yaml
=> ci(device_info_plus): Remove Java installation step

.github/workflows/package_info_plus.yaml
=> ci(package_info_plus): Remove Java installation step

.github/workflows/network_info_plus.yaml
=> ci(network_info_plus): Remove Java installation step

.github/workflows/sensors_plus.yaml
=> ci(sensors_plus): Remove Java installation step

packages/network_info_plus/network_info_plus/lib/src/network_info_plus_windows.dart
Since version `4.0.0`, the windows implementation got a rewrite in Dart.
Previously, when a PC has no wifi, then `null` is returned. Since `4.0.0` we return an empty string `''` instead which does not align with the API. Furthermore, this (unwanted?) breaking change seems to be unecessary.
- Related #1780 
=> fix(network_info_plus): Return nullable values on windows again

packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
=> chore(connectivity_plus): Update compileSDK to 34 for example

packages/android_intent_plus/example/android/app/build.gradle
=> chore(android_intent_plus): Update compileSDK to 34 for example

packages/sensors_plus/sensors_plus/example/android/app/build.gradle
=> chore(sensors_plus): Update compileSDK to 34 for example

packages/package_info_plus/package_info_plus/android/build.gradle, packages/package_info_plus/package_info_plus/example/android/build.gradle
=> fix(package_info_plus): Change Kotlin version from 1.9.10 to 1.7.22

docs/sensors_plus/usage.mdx, packages/sensors_plus/sensors_plus/README.md, website/package-lock.json, website/package.json, website/src/theme/MDXComponents/index.tsx
Updating documentation for users about new feature of custom sampling rate in `sensors_plus`
=> docs(sensors_plus): Add info about sensors sampling rate configuration

.github/workflows/connectivity_plus.yaml
=> chore(connectivity_plus): Switch CI runners to M1

.github/workflows/network_info_plus.yaml
=> chore(network_info_plus): Switch CI runners to M1

.github/workflows/package_info_plus.yaml
And another workflow migrates to M1 machines
=> chore(package_info_plus): Switch CI runners to M1

.github/workflows/sensors_plus.yaml
=> chore(sensors_plus): Switch CI runners to M1

docs/connectivity_plus/overview.mdx, docs/connectivity_plus/usage.mdx, packages/connectivity_plus/connectivity_plus/README.md
Change examples and a few texts to be up to date with plugin's state.
=> docs(connectivity_plus): Update documentation to address API changes

packages/android_intent_plus/android/build.gradle, packages/android_intent_plus/example/android/app/build.gradle
=> build(android_intent_plus)!: Target Java 17 on Android

packages/package_info_plus/package_info_plus/android/build.gradle, packages/package_info_plus/package_info_plus/example/android/app/build.gradle, packages/package_info_plus/package_info_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
=> build(package_info_plus)!: Target Java 17 on Android

packages/sensors_plus/sensors_plus/android/build.gradle, packages/sensors_plus/sensors_plus/example/android/app/build.gradle, packages/sensors_plus/sensors_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
=> build(sensors_plus)!: Target Java 17 on Android

packages/sensors_plus/sensors_plus/example/android/app/build.gradle, packages/sensors_plus/sensors_plus/example/android/build.gradle, packages/sensors_plus/sensors_plus/example/android/settings.gradle
=> refactor(sensors_plus): Migrate Android example to use the new plugins declaration

packages/share_plus/share_plus/CHANGELOG.md
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*
*e.g.*
- *Fix #123*
- *Related #456*
=> docs(share_plus): remove typo from the changelog

packages/battery_plus/battery_plus/example/android/app/build.gradle, packages/battery_plus/battery_plus/example/android/build.gradle, packages/battery_plus/battery_plus/example/android/settings.gradle
=> refactor(battery_plus): Migrate Android example to use the new plugins declaration

packages/device_info_plus/device_info_plus/example/android/app/build.gradle, packages/device_info_plus/device_info_plus/example/android/build.gradle, packages/device_info_plus/device_info_plus/example/android/settings.gradle
=> refactor(device_info_plus): Migrate Android example to use the new plugins declaration

packages/android_intent_plus/example/android/app/build.gradle, packages/android_intent_plus/example/android/build.gradle, packages/android_intent_plus/example/android/settings.gradle
=> refactor(android_intent_plus): Migrate Android example to use the new plugins declaration

packages/package_info_plus/package_info_plus/README.md
Adds documentation regarding how the plugin works in web and possible CORS access issues.
- Related https://github.com/fluttercommunity/plus_plugins/issues/2699#issuecomment-2055180900
=> docs(package_info_plus): Improve web documentation re. CORS

packages/share_plus/share_plus/README.md
Updated documentation to be a bit more explicit regarding 3rd party share compatibility and support.
=> docs(share_plus): Update README.md

packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
Simulator model changes, so we need to update the integration tests
=> fix(device_info_plus): fix integration_test iOS

packages/android_alarm_manager_plus/example/pubspec.yaml, packages/android_alarm_manager_plus/pubspec.yaml
=> chore(android_alarm_manager_plus): upgrade flutter_lints to 4.0.0

CONTRIBUTING.md, pubspec.yaml
Bumping Melos version in the root of the repo. There was a breaking change that required an update to our contribution guide, which I also did here.
https://pub.dev/packages/melos/changelog
=> chore(ci): Update Melos

packages/battery_plus/battery_plus/lib/src/battery_plus_web.dart
This PR was automatically closed by GitHub, reopening againg
See #3153
=> fix(battery_plus): Fix type conversion

packages/connectivity_plus/connectivity_plus/README.md
Same as for other plugins - fixing the requirements section.
=> docs(connectivity_plus): Update plugin requirements in README

packages/device_info_plus/device_info_plus/README.md
Actualisation of `Requirements` section.
=> docs(device_info_plus): Update plugin requirements in README

packages/package_info_plus/package_info_plus/README.md
Actualisation of `Requirements` section in README
=> docs(package_info_plus): Update plugin requirements in README

packages/sensors_plus/sensors_plus/README.md
Actualisation of plugin requirements in README
=> docs(sensors_plus): Update plugin requirements in README

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt
=> fix(device_info_plus): add @Suppress(deprecate) to Build.SERIAL

README.md
This PR updated the project's root README.me with local links to plugins's own README.mds and also changes link to CONTRIBUTING.md to be local
n/a
=> docs: Update root README.md with local links to plugin's README.md

packages/battery_plus/battery_plus/example/lib/main.dart
Fix analysis issues in example
- Related #3513 
=> chore(battery_plus): fix analysis issues in example

packages/package_info_plus/package_info_plus/test/package_info_plus_linux_test.dart
Fixes analysis issues in project
- related #3513
=> chore(package_info_plus): remove unnecessary library name in test
