fluttercommunity/plus_plugins

packages/android_alarm_manager_plus/README.md
packages/android_intent_plus/README.md
packages/connectivity_plus/README.md
packages/device_info_plus/README.md

Use secure links in README
This will increase the package scores by 5.
[plus_plugins](https://github.com/fluttercommunity/plus_plugins/issues/16).
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/master/CONTRIBUTING.md

Use secure links in README

---

AUTHORS
packages/battery_plus/macos/battery_plus.podspec
packages/battery_plus/pubspec.yaml
packages/battery_plus_macos/macos/battery_plus_macos.podspec
packages/battery_plus_macos/pubspec.yaml

This PR cleans up the description, package information, and author information for battery_plus_macos.
- None

Clean up Pubspec and Podspec metadata 

---

packages/package_info_plus_web/lib/package_info_plus_web.dart

When creating a new Flutter Web app, the generated index.html contains
the following information:
<base href="/">
The MDN web docs mentioned "document.baseURI", so this patch is using
`window.document.baseUri` to get the base URL for version.json.
#26 …

[package_info_plus_web] Fix version.json lookup

---

packages/android_alarm_manager_plus/example/lib/main.dart

display1 is deprecated.
so we should change to headline4. …

[android_alarm_manager_plus] removed deprecated display1

---

packages/device_info_plus/README.md

Use flutter.dev instead of flutter.io

[device_info_plus] Use flutter.dev instead of flutter.io

---

packages/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus_windows/lib/package_info_plus_windows.dart
packages/package_info_plus_windows/lib/src/package_info_plus_windows_real.dart
packages/package_info_plus_windows/lib/src/package_info_plus_windows_stub.dart

Same as flutter/plugins@2595703 for path_provider_windows.
Moves the real implementation of package_info_plus_windows behind a
conditional export, instead exporting a stub on platforms that don't
support dart:ffi. This avoids build breakage in web projects that have
transitive dependencies on package_info_plus (and thus
package_info_plus__windows due to manual endorsement).
This will no longer be necessary once
flutter/flutter#52267 is fixed, since only
Windows builds will ever need to have code-level dependency on
package_info_plus_windows.
flutter/flutter#52267 …

[package_info_plus] fix web build (broken by windows & ffi)

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/README.md
packages/android_alarm_manager_plus/android/src/main/AndroidManifest.xml
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmBroadcastReceiver.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/FlutterBackgroundExecutor.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/PluginRegistrantException.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/RebootBroadcastReceiver.java
packages/android_alarm_manager_plus/example/android/app/src/main/AndroidManifest.xml
packages/android_alarm_manager_plus/ios/Classes/AndroidAlarmManagerPlusPlugin.h
packages/android_alarm_manager_plus/ios/Classes/AndroidAlarmManagerPlusPlugin.m
packages/android_alarm_manager_plus/ios/android_alarm_manager.podspec
packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart
packages/android_alarm_manager_plus/pubspec.yaml
packages/android_alarm_manager_plus/test/android_alarm_manager_test.dart

#56 for `android_alarm_manager_plus`

[android_alarm_manager_plus] rename method channel and java package. See #56

---

packages/battery_plus/CHANGELOG.md
packages/battery_plus/android/build.gradle
packages/battery_plus/android/src/main/AndroidManifest.xml
packages/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/android/src/main/java/io/flutter/plugins/battery/BatteryPlugin.java
packages/battery_plus/ios/Classes/FLTBatteryPlugin.m
packages/battery_plus/ios/Classes/FLTBatteryPlusPlugin.h
packages/battery_plus/ios/Classes/FLTBatteryPlusPlugin.m
packages/battery_plus/lib/battery_plus.dart
packages/battery_plus/pubspec.yaml
packages/battery_plus_linux/lib/battery_plus_linux.dart
packages/battery_plus_linux/lib/src/battery_plus_linux_real.dart
packages/battery_plus_linux/lib/src/battery_plus_linux_stub.dart
packages/battery_plus_linux/pubspec.yaml
packages/battery_plus_linux/test/battery_plus_linux_test.dart
packages/battery_plus_macos/macos/Classes/BatteryPlusMacosPlugin.swift
packages/battery_plus_macos/pubspec.yaml
packages/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus_platform_interface/lib/src/method_channel_battery_plus.dart
packages/battery_plus_platform_interface/pubspec.yaml
packages/battery_plus_web/CHANGELOG.md
packages/battery_plus_web/lib/battery_plus_web.dart
packages/battery_plus_web/pubspec.yaml
packages/battery_plus_windows/pubspec.yaml
packages/battery_plus_windows/windows/battery_plus_windows_plugin.cpp

[battery_plus] rename method channel and plugins (#56)

---

packages/package_info_plus/CHANGELOG.md
packages/package_info_plus/pubspec.yaml
packages/package_info_plus_linux/CHANGELOG.md
packages/package_info_plus_linux/pubspec.yaml
packages/package_info_plus_web/CHANGELOG.md
packages/package_info_plus_web/lib/package_info_plus_web.dart
packages/package_info_plus_web/pubspec.yaml

```
Because every version of package_info_plus from path depends on package_info_plus_linux ^0.1.0 which depends on package_info_plus_platform_interface ^0.1.0, every version of package_info_plus from path requires package_info_plus_platform_interface ^0.1.0.
So, because package_info_example depends on package_info_plus from path which depends on package_info_plus_platform_interface ^0.3.0, version solving failed.
```

[package_info_linux] fix platform interface dependency version

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
packages/android_intent_plus/lib/android_intent.dart
packages/android_intent_plus/test/android_intent_test.dart

In https://github.com/flutter/flutter/issues/71518 the author requested a way to be able to launch Intents with the createChooser wrapper.
In this PR I have added the method channel `launchChooser` which allows users to do that.
Usage:
```dart
final intent = const AndroidIntent(
action: 'android.intent.action.SEND',
type: 'plain/text',
data: 'text example',
);
intent.launchChooser('Chose an app');
```
- https://github.com/flutter/flutter/issues/71518
- https://github.com/fluttercommunity/plus_plugins/issues/75
Note: I have added e2e and unit tests, but …

[android_intent_plus] fix flutter/flutter#71518 by adding launchChooser method.

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
packages/android_intent_plus/example/android/app/build.gradle
packages/android_intent_plus/example/android/app/src/main/AndroidManifest.xml
packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/EmbeddingV1Activity.java
packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/MainActivity.java
packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/MyBroadcastReceiver.java
packages/android_intent_plus/example/android/app/src/main/res/values/strings.xml
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/example/test_driver/android_intent_plus_e2e.dart
packages/android_intent_plus/lib/android_intent.dart
packages/android_intent_plus/pubspec.yaml
packages/android_intent_plus/test/android_intent_test.dart

Adds method to send Intent as broadcast, as suggested in https://github.com/flutter/flutter/issues/65533
To show this example, a broadcast register is created in the example project on the Android side. It will show a toast when the broadcast is received.
- https://github.com/flutter/flutter/issues/65533
- https://github.com/fluttercommunity/plus_plugins/issues/75

[android_intent_plus] implement send intent as broadcast

---

packages/package_info_plus_web/lib/package_info_plus_web.dart

When accessing the version.json file the generated URL contains an extra forward-slash, that can prevent in some deployments access to the file
https://github.com/fluttercommunity/plus_plugins/issues/96

[package_info_plus_web] Fix double slash in version.json lookup

---

packages/device_info_plus_platform_interface/lib/model/web_browser_info.dart

Fix this issue https://github.com/fluttercommunity/plus_plugins/issues/94
https://github.com/fluttercommunity/plus_plugins/issues/94
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]). …

fix(device_info_plus): return Edge for browser name for both new edge and old one

---

packages/device_info_plus/CHANGELOG.md
packages/device_info_plus/pubspec.yaml

The device_info_plus v0.6.0 release commit went somehow missing. It was never pushed/merged to the repo. I've downloaded the sources from pub.dev and applied the minor changes.
Outdated platform plugin dependency versions in v0.5.0 (that the repo still had) were causing version conflicts:
```
Because every version of device_info_plus from path depends on device_info_plus_platform_interface ^0.3.0 and device_info_plus_linux ^0.1.0 depends on device_info_plus_platform_interface ^0.2.0, device_info_plus from path is incompatible with device_info_plus_linux ^0.1.0.
So, because device_info_example depends on device_info_plus from path which depends on device_info_plus_linux ^0.1.0, version solving failed.
```
These were sorted out in v0.6.0.

[device_info_plus] sync repo sources with the v0.6.0 release

---

.github/workflows/all_plugins.yaml
packages/android_alarm_manager_plus/example/test_driver/android_alarm_manager_plus_e2e_test.dart
packages/device_info_plus/example/lib/main.dart

Work required to do: https://github.com/fluttercommunity/plus_plugins/issues/50

Enable channel beta on CI

---

packages/package_info_plus/README.md

When I read the `README.md` of `package_info_plus` it wasn't for me clear, which platforms are supported. You can see it maybe with the dependencies like `package_info_plus_linux`. However, it is very hidden. And in the description of the `pubspec.yaml`, which will be displayed at the right side, mentioning only Android & iOS which is confusing (My thoughts: Why not also mention Linux, Web, macOS and Windows? Or is there no support for this platforms)? 
Part of #111

[package_info_plus] Added supported platforms to README.md

---

analysis_options.yaml
melos.yaml
packages/android_intent_plus/example/analysis_options.yaml
packages/package_info_plus/example/analysis_options.yaml

Small change to setup null safety in the analyzer used by melos.
Two exceptions need to be done for the example project in android_intent_plus and in package_info_plus

[all] melos analyzer support null safety

---

packages/share_plus/ios/Classes/FLTSharePlusPlugin.m

When sharing a non-image file with the iOS share sheet (via the share plugin), the correct actions based on the file type are not appearing in the share sheet. 
For example, when sharing a PDF file, the share sheet currently looks like the screenshot on the left. Notice that compared with the screenshot on the right, the current share sheet does not include the `Markup` or `Print` actions.
| Current Behavior  | Fixed - Using `NSURL`  |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/1865904/100383907-b8a27380-3016-11eb-979c-8f1243de657f.jpeg" width="375" />  | <img src="https://user-images.githubusercontent.com/1865904/100384122-4ed69980-3017-11eb-9d3e-5608ff81170c.jpeg" width="375" />  |
The fix consists of using a `NSURL` based on the supplied …

[share_plus] Use NSURL when sharing non-image files to make correct actions appear in share sheet

---

CONTRIBUTING.md

Changed `master` to `main` in the contributor guide.

Change master with main branch 

---

packages/share_plus_macos/pubspec.yaml

To fix:
Uploading...
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.

[share_plus_macos] bump Flutter SDK version constraint

---

packages/device_info_plus_macos/pubspec.yaml

Required because of the missing `ios/` directory.

[device_info_plus_macos] bump up Flutter version constraint

---

packages/device_info_plus/CHANGELOG.md
packages/device_info_plus/pubspec.yaml
packages/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus_linux/pubspec.yaml
packages/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus_macos/pubspec.yaml
packages/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus_platform_interface/lib/device_info_plus_platform_interface.dart
packages/device_info_plus_platform_interface/pubspec.yaml
packages/device_info_plus_web/CHANGELOG.md
packages/device_info_plus_web/pubspec.yaml

MacOsDeviceInfo export was missing in the platform interface.

[device_info_plus] fix macos support

---

packages/battery_plus/CHANGELOG.md
packages/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/pubspec.yaml

Desktop & web already send the current battery status when the stream is opened. Given that there is no battery status getter in the API, this seems a reasonable approach to avoid "null" battery status on startup.

[battery_plus_android] send initial battery status

---

packages/battery_plus/CHANGELOG.md
packages/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/ios/Classes/FLTBatteryPlusPlugin.m
packages/battery_plus/pubspec.yaml
packages/battery_plus_linux/CHANGELOG.md
packages/battery_plus_linux/lib/src/battery_plus_linux_real.dart
packages/battery_plus_linux/pubspec.yaml
packages/battery_plus_macos/CHANGELOG.md
packages/battery_plus_macos/macos/Classes/BatteryPlusChargingHandler.swift
packages/battery_plus_macos/pubspec.yaml
packages/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus_platform_interface/lib/src/enums.dart
packages/battery_plus_platform_interface/lib/src/utils.dart
packages/battery_plus_platform_interface/pubspec.yaml
packages/battery_plus_web/CHANGELOG.md
packages/battery_plus_web/pubspec.yaml
packages/battery_plus_windows/CHANGELOG.md
packages/battery_plus_windows/pubspec.yaml
packages/battery_plus_windows/windows/system_battery.cpp

Added "unknown" battery state for batteryless systems (e.g. workstations).
Closes: #61

[battery_plus] add "unknown" status (#61)

---

website/plugins.js
website/src/pages/index.tsx

Make the table a bit narrower to make it fit mobile screens better. These tweaks make all columns almost fully visible in landscape mode on Pixel 5. In portrait mode, it's not possible to scroll all the way to the left to see the package name, but I have no idea how to fix that. :)

[website] minor tweaks to make it more mobile friendly

---

packages/network_info_plus/CHANGELOG.md
packages/network_info_plus/lib/network_info_plus.dart
packages/network_info_plus/pubspec.yaml
packages/network_info_plus_linux/CHANGELOG.md
packages/network_info_plus_linux/pubspec.yaml
packages/network_info_plus_macos/CHANGELOG.md
packages/network_info_plus_macos/pubspec.yaml
packages/network_info_plus_platform_interface/CHANGELOG.md
packages/network_info_plus_platform_interface/lib/method_channel_network_info.dart
packages/network_info_plus_platform_interface/lib/network_info_plus_platform_interface.dart
packages/network_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus_platform_interface/test/method_channel_network_info_test.dart
packages/network_info_plus_web/CHANGELOG.md
packages/network_info_plus_web/pubspec.yaml
packages/network_info_plus_windows/CHANGELOG.md
packages/network_info_plus_windows/pubspec.yaml

Importing `platform_interface/src/foo.dart` in the main package loses 10 pub score points:
Pass static analysis
20/30 points: code has no errors, warnings, lints, or formatting issues
INFO: Don't import implementation files from another package.

[network_info_plus] address pub score (#16)

---

packages/package_info_plus/CHANGELOG.md
packages/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/pubspec.yaml
packages/package_info_plus/test/package_info_test.dart

Added a similar method as already given in the shared_preference plugin (https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L196), to allow the easy usage of the package_info_plus plugin during tests. The method allows the setup of mock data and also enables the developer to change the data during tests.
Fixes https://github.com/fluttercommunity/plus_plugins/issues/145

[package_info_plus] Make PackageInfo testable with mock data

---

docs/battery/overview.mdx

There's no tutorial page yet, so `npm run build` fails (and website changes don't get deployed):
```
Error: Docusaurus found broken links!
Please check the pages of your site in the list bellow, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
Exhaustive list of all broken links found:
- On source page path = /docs/battery/overview:
-> linking to tutorial (resolved as: /docs/battery/tutorial)
at Object.reportMessage (/home/jpnurmi/Projects/flutter/plus_plugins/website/node_modules/@docusaurus/utils/lib/index.js:440:19)
at Object.handleBrokenLinks (/home/jpnurmi/Projects/flutter/plus_plugins/website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:142:1 …
```

[website] comment out broken doc link to fix build & deployment

---

packages/battery_plus/CHANGELOG.md
packages/battery_plus/lib/battery_plus.dart
packages/battery_plus/pubspec.yaml
packages/battery_plus_linux/CHANGELOG.md
packages/battery_plus_linux/pubspec.yaml
packages/battery_plus_macos/CHANGELOG.md
packages/battery_plus_macos/pubspec.yaml
packages/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus_platform_interface/lib/battery_plus_platform_interface.dart
packages/battery_plus_platform_interface/lib/method_channel_battery_plus.dart
packages/battery_plus_platform_interface/pubspec.yaml
packages/battery_plus_platform_interface/test/battery_plus_platform_interface_test.dart
packages/battery_plus_web/CHANGELOG.md
packages/battery_plus_web/pubspec.yaml
packages/battery_plus_windows/CHANGELOG.md
packages/battery_plus_windows/pubspec.yaml

Importing `platform_interface/src/foo.dart` in the main package loses 10 pub score points:
Pass static analysis
20/30 points: code has no errors, warnings, lints, or formatting issues
INFO: Don't import implementation files from another package.

[battery_plus] address pub.dev score (#16) 

---

packages/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/lib/connectivity_plus.dart
packages/connectivity_plus/pubspec.yaml
packages/connectivity_plus_linux/CHANGELOG.md
packages/connectivity_plus_linux/pubspec.yaml
packages/connectivity_plus_macos/CHANGELOG.md
packages/connectivity_plus_macos/pubspec.yaml
packages/connectivity_plus_platform_interface/CHANGELOG.md
packages/connectivity_plus_platform_interface/lib/connectivity_plus_platform_interface.dart
packages/connectivity_plus_platform_interface/lib/method_channel_connectivity.dart
packages/connectivity_plus_platform_interface/pubspec.yaml
packages/connectivity_plus_platform_interface/test/method_channel_connectivity_test.dart
packages/connectivity_plus_web/CHANGELOG.md
packages/connectivity_plus_web/pubspec.yaml
packages/connectivity_plus_windows/CHANGELOG.md
packages/connectivity_plus_windows/pubspec.yaml

Importing `platform_interface/src/foo.dart` in the main package loses 10 pub score points:
Pass static analysis
20/30 points: code has no errors, warnings, lints, or formatting issues
INFO: Don't import implementation files from another package.

[connectivity_plus] address pub score (#16)

---

packages/device_info_plus_linux/pubspec.yaml
packages/device_info_plus_windows/pubspec.yaml

I forgot to publish the packages whilst bragging on Twitter. This came up while publishing `device_info_plus_linux` & `device_info_plus_windows`:
```
Package validation found the following potential issue:
* This package is opting into null-safety, but a dependency or file is not.
package:device_info_plus_platform_interface is not opted into null safety in its pubspec.yaml:
Note that by publishing with non-migrated dependencies your package may be
broken at any time if one of your dependencies migrates without a breaking 
change release. 
We highly recommend that you wait until all of your dependencies have been 
migrated before publishing.
Run `pub outdated --mode=null-safety` for more information about the state of
dependencies.
See https://dart.dev/null-safety/migration-guide
for more …
```

[device_info] fix platform_interface dependency for linux & windows

---

README.md

If that is not intended then this PR fixes pub.dev version badges links. 
When you click on them it displays the image in the new tab but [usually on other packages](https://github.com/flutter/packages) it opens pub.dev link. …

fix README.md pub links

---

packages/device_info_plus/CHANGELOG.md
packages/device_info_plus/pubspec.yaml
packages/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus_linux/pubspec.yaml

The latest `flutter_driver` in master depends on `file` 6.1.0.

[device_info_plus_linux] upgrade `file` dependency

---

packages/package_info_plus/CHANGELOG.md
packages/package_info_plus/pubspec.yaml
packages/package_info_plus_linux/CHANGELOG.md
packages/package_info_plus_linux/pubspec.yaml
packages/package_info_plus_macos/CHANGELOG.md
packages/package_info_plus_macos/pubspec.yaml
packages/package_info_plus_platform_interface/CHANGELOG.md
packages/package_info_plus_platform_interface/pubspec.yaml
packages/package_info_plus_web/CHANGELOG.md
packages/package_info_plus_web/pubspec.yaml
packages/package_info_plus_windows/CHANGELOG.md
packages/package_info_plus_windows/pubspec.yaml

I just discovered some problems with the [pub.dev score](https://pub.dev/packages/package_info_plus/versions/1.0.0-nullsafety.0/score) for the new null safety version (btw. thanks for the migration 👍 ). I lowered the version constraints to the [recommended one](https://dart.dev/null-safety/migration-guide#package-version):
```
Before you publish a stable null safety version of a package, we strongly recommend following these pubspec rules:
Set the Dart lower SDK constraint to 2.12.0-259.9.beta.
Use stable versions of all direct dependencies.
```
I also updated some dependencies.
#50 
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and …

[package_info_plus] Update preview dependencies #50

---

packages/battery_plus/example/linux/flutter/CMakeLists.txt
packages/battery_plus/example/windows/flutter/CMakeLists.txt
packages/connectivity_plus/example/linux/flutter/CMakeLists.txt
packages/device_info_plus/example/linux/flutter/CMakeLists.txt
packages/network_info_plus/example/linux/flutter/CMakeLists.txt
packages/network_info_plus/example/windows/flutter/CMakeLists.txt
packages/package_info_plus/example/linux/flutter/CMakeLists.txt
packages/package_info_plus/example/windows/flutter/CMakeLists.txt
packages/share_plus/example/linux/flutter/CMakeLists.txt
packages/share_plus/example/windows/flutter/CMakeLists.txt

Both VERBATIM (Windows & Linux) and FLUTTER_TARGET_PLATFORM (Linux only) CMake migration changes have reached dev, so we can commit them to avoid applying them every time `pub get` is run:
Running "flutter pub get" in xxx...
add_custom_command() missing VERBATIM or FLUTTER_TARGET_PLATFORM, updating.
Building Linux application...

Migrate CMake files

---

packages/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/device_info_plus_platform_interface/pubspec.yaml

Fix issue reported in #184 by supporting nullable values coming from Android.
In theory we only need to update the platform interface and release it.
Will release once the PR is merged.
This has been tested with an emulator and using the example project.

Fix #184 - Support null values from Android

---

.github/workflows/all_plugins.yaml
packages/device_info_plus_platform_interface/lib/model/macos_device_info.dart

This PR improves the documentation of the `MacOsDeviceInfo` class.
It fixes some typos and formatting incompatibilities with Dart's documentation generator.
See https://pub.dev/documentation/device_info_plus_platform_interface/1.0.0/model_macos_device_info/MacOsDeviceInfo-class.html for how it currently looks like.
None as far as I am aware. …

Improve `MacOsDeviceInfo` documentation

---

AUTHORS
packages/share_plus/CHANGELOG.md
packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/ios/share_plus.podspec
packages/share_plus/pubspec.yaml

Fixes one of the issues reported in #190 where the iOS share sheet would show a blank preview instead of the given text.
Verified working on iOS 14.4, 12.0 simulators
#190 [share_plus] Text not showing in share modal and web opens a new tab to about:blank …

feat(share_plus): Show preview title in iOS share sheet (#190)

---

packages/package_info_plus_macos/macos/Classes/FLTPackageInfoPlusPlugin.h
packages/package_info_plus_macos/macos/Classes/FLTPackageInfoPlusPlugin.m
packages/package_info_plus_macos/pubspec.yaml

* Renamed FLTPackageInfoPlugin to FLTPackageInfoPlusPlugin in order to avoid conflict with `package_info` plugin*
fluttercommunity/plus_plugins#214

issue-213: renamed FLTPackageInfoPlugin to FLTPackageInfoPlusPlugin

---

.github/workflows/all_plugins.yaml

Job is currently broken, would be good to fix it but I don't have the knowledge to do it. I have created a ticket #220 to fix it, meanwhile let's disable it.

Disable integration_test job until fixed

---

packages/share_plus/CHANGELOG.md
packages/share_plus/ios/share_plus.podspec
packages/share_plus/pubspec.yaml

When running on iOS 12.x and below, apps depending on share_plus 2.0.1 crash at startup
I was able to reproduce the issue in a new flutter app with a dependency on either
`share_plus: 2.0.1`
or
```
share_plus:
path: path_to_local_repo/plus_plugins/packages/share_plus
```
I was not able to reproduce the issue in the share_plus example included in this repository. I'm not sure why
In Xcode, build settings show an other linker flag of `-framework LinkPresentation`. This creates a requirement of having the LinkPresentation framework available at launch. Since LinkPresentation is not available until iOS 13 and later, this caused apps running iOS 12.x and lower to crash
Updated iOS Podspec to use a weak_framework link to LinkPresentation framework. This updates the other linker flag in the …

fix(share_plus): Fixed crash at launch on iOS 12.x and below (#222)

---

packages/share_plus_linux/CHANGELOG.md
packages/share_plus_linux/lib/share_plus_linux.dart
packages/share_plus_linux/pubspec.yaml
packages/share_plus_linux/test/share_plus_linux_test.dart
packages/share_plus_web/CHANGELOG.md
packages/share_plus_web/lib/share_plus_web.dart
packages/share_plus_web/pubspec.yaml
packages/share_plus_windows/CHANGELOG.md
packages/share_plus_windows/lib/share_plus_windows.dart
packages/share_plus_windows/pubspec.yaml
packages/share_plus_windows/test/share_plus_windows_test.dart

This fixes the issue mentiond in https://github.com/fluttercommunity/plus_plugins/issues/235
Are there any existing unit tests which I can add a test to? 
Fixes https://github.com/fluttercommunity/plus_plugins/issues/235
Fixes https://github.com/fluttercommunity/plus_plugins/issues/226 (at least a part of it) …

fix(share_plus): Fix url encoding for web, Linux and Windows

---

packages/share_plus_linux/CHANGELOG.md
packages/share_plus_linux/lib/share_plus_linux.dart
packages/share_plus_linux/pubspec.yaml
packages/share_plus_linux/test/share_plus_linux_test.dart
packages/share_plus_web/CHANGELOG.md
packages/share_plus_web/lib/share_plus_web.dart
packages/share_plus_web/pubspec.yaml
packages/share_plus_windows/CHANGELOG.md
packages/share_plus_windows/lib/share_plus_windows.dart
packages/share_plus_windows/pubspec.yaml
packages/share_plus_windows/test/share_plus_windows_test.dart

See https://github.com/fluttercommunity/plus_plugins/pull/236#discussion_r632676591
cc @miquelbeltran  @stuartmorgan
No, but this comment: https://github.com/fluttercommunity/plus_plugins/pull/236#discussion_r632676591
[pub …

fix(share_plus): Another try at fixing url encoding

---

packages/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/share_plus/android/src/main/java/dev/fluttercommunity/plus/share/MethodCallHandler.java
packages/share_plus/android/src/main/java/dev/fluttercommunity/plus/share/Share.java
packages/share_plus/android/src/main/res/xml/flutter_share_file_paths.xml
packages/share_plus/example/android/app/build.gradle

This PR fixes #241. It resolves issues with deprecations as of android API version 29 and replaces the requirement for external storage locations with an easy application cache usage. It also adds a warning to users so their files don't get deleted by `clearShareCacheFolder()` (ex `clearExternalShareFolder()`). In addition, it removes an annoying compile time warning caused by raw type conversion (type correctness is ensured on the dart side)
[issue database]: …

[share_plus] Fix android API-deprications and wrongful assumptions

---

packages/share_plus/CHANGELOG.md
packages/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/pubspec.yaml

Updated iOS share sheet preview title to use subject when text is not set
Currently, the iOS share sheet preview tittle will show the value of the text parameter. If the text parameter is not set, then the share sheet preview title will be blank.
This change makes it so that the share sheet preview title will show the value of the subject parameter if it is set and the text parameter is not. If both text and subject are set, it will show the value of the text parameter.
This change was motivated by a comment by @TheJulianJES in https://github.com/fluttercommunity/plus_plugins/pull/207#issuecomment-845512546
Specifically, if he saves an image with text set to a value it will show the share sheet title preview correctly, but it will also save two files instead of the expected one: 
- the …

feat(share_plus): Updated iOS share sheet preview title to use subject when text is not set

---

packages/package_info_plus_linux/lib/src/package_info.dart

Currently, the `_getVersionJson()` function in package_info_plus_linux reads files synchronously. It's not reading much data, but on slow drives, it could cause issues (I've ran Linux on thumb drives that would take seconds to read a text file). I made the function asynchronous. This won't be a breaking change as `getAll()` (the only function that uses `_getVersionJson()`) was already asynchronous.
None. Just noticed this myself and thought I'd fix it.
[issue …

fix(package_info_plus_linux): Use async functions in _getVersionJson()

---

packages/network_info_plus_windows/windows/include/network_info_plus_windows/network_info.h
packages/network_info_plus_windows/windows/network_info_plus_windows_plugin.cpp

The current include order for network_info.h and network_info_plus_windows_plugin.cpp prevented the windows version to successfully run. See also the related issues. The wrong order seem to be caused by the melos format run as can be seen at d7f7f3f2ecceb0158fe879b7ac124a72d4d32637.
#193 #202 #208 

fix(network_info_plus_windows): Fix include order

---

packages/share_plus/CHANGELOG.md
packages/share_plus/android/src/main/java/dev/fluttercommunity/plus/share/SharePlusPlugin.java
packages/share_plus/pubspec.yaml

We should not tear down the method channel onDetachedFromActivity. That will cause MissingPluginException for the following method calls.
flutter/flutter#12264 …

Do not remove the tearDownChannel onDetachedFromActivity.

---

packages/package_info_plus/CHANGELOG.md
packages/package_info_plus/pubspec.yaml
packages/package_info_plus_web/CHANGELOG.md
packages/package_info_plus_web/lib/package_info_plus_web.dart
packages/package_info_plus_web/pubspec.yaml

Version.json can get cached on different servers due to cache policies. adding a cache buster can help to prevent this and returning real data all the time. 
https://github.com/fluttercommunity/plus_plugins/issues/225
[pub …

Add cache buster to packageinfo version.json

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/build.gradle
packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/build.gradle
packages/battery_plus/android/build.gradle
packages/battery_plus/example/android/build.gradle
packages/connectivity_plus/example/android/build.gradle
packages/device_info_plus/android/build.gradle
packages/device_info_plus/example/android/build.gradle
packages/network_info_plus/android/build.gradle
packages/network_info_plus/example/android/build.gradle
packages/package_info_plus/android/build.gradle
packages/package_info_plus/example/android/build.gradle
packages/sensors_plus/android/build.gradle
packages/sensors_plus/example/android/build.gradle
packages/share_plus/android/build.gradle
packages/share_plus/example/android/build.gradle

The jcenter maven repo is sunsetting and is now readonly https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter.
https://github.com/fluttercommunity/plus_plugins/issues/246

Migrate to mavenCentral

---

packages/package_info_plus_windows/CHANGELOG.md
packages/package_info_plus_windows/lib/src/file_version_info.dart
packages/package_info_plus_windows/pubspec.yaml

Each property of `_FileVersionInfo` has a trailing `\u0000` if the property exists. Just removing the empty char before returning value in `getValue`.
- #182
- #250
- [] I read and followed the [Flutter Style Guide].
[pub …

[package_info_plus_windows] remove trailing \u0000

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/connectivity_plus/connectivity_plus/pubspec.yaml

Add Java 8 reference to Gradle for _Connectivity Plus_. This is necessary because the default toolchain will emit a warning that Java 7 is facing deprecation (and rightly so!) but because `-Werror` is also specified, this warning is treated as a build-breaking error.
- #319
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.  
Dart code was not changed, only Gradle configs.
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBU …

Add explicit compiler version

---

packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/ios_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/macos_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/ios_device_info_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/macos_device_info_test.dart

Added toMap method on android, ios, and macOS device info models.
Closes #259

Added toMap method 

---

packages/connectivity_plus/connectivity_plus/android/build.gradle

Hotfix of android java version used 
Error thrown:
`Could not get unknown property 'javaToolchains' for task ':app:compileDebugAndroidTestJavaWithJavac' of type com.android.build.gradle.tasks.AndroidJavaCompile.`
https://github.com/fluttercommunity/plus_plugins/issues/345
https://github.com/fluttercommunity/plus_plugins/issues/341 …

Fix connectivity_plus: Could not get unknown property 'javaToolchains' for task ':app:compileDebugAndroidTestJavaWithJavac'

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityPlugin.java
packages/connectivity_plus/connectivity_plus/pubspec.yaml

connectivity_plus: Fix for an Android memory leak from a broadcast receiver which is not unregistered after the plugin is closed.
Android Broadcast receiver holds an instance of Android-Activity until it's unregistered.
This fix unregisters the receiver while tearing the plugin down.
https://github.com/fluttercommunity/plus_plugins/issues/326 …

connectivity_plus fix android memory leak (#326)

---

packages/android_alarm_manager_plus/README.md

I can't make the code from readme work, but the example app works.
By comparing the two, somehow `static` is missing in the example in readme and the alarm won't set without it.

doc: Callback needs to be static

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java
packages/connectivity_plus/connectivity_plus/pubspec.yaml

We are calling `unregisterReceiver` even if a call to `onListen` (which calls `registerReceiver` for API < N) has never been requested by consumer.
This happen if the package is used to one-shot check connectivity and not using the connectivity change stream events.
An alternative to this fix would be to track the onListen call with a boolean flag and call `unregisterReceiver` only if the flag has been set to true in `onListen`, let me know if you like this approach more.
Closes #358, #367

fix(connectivity-plus): fix unregisterReceiver call

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/battery_plus/example/lib/main.dart
packages/battery_plus/battery_plus/example/test_driver/battery_plus_e2e.dart
packages/battery_plus/battery_plus/ios/Classes/FLTBatteryPlusPlugin.m
packages/battery_plus/battery_plus/lib/battery_plus.dart
packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus/test/battery_test.dart
packages/battery_plus/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus/battery_plus_platform_interface/lib/battery_plus_platform_interface.dart
packages/battery_plus/battery_plus_platform_interface/lib/method_channel_battery_plus.dart
packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
packages/battery_plus/battery_plus_platform_interface/test/battery_plus_platform_interface_test.dart
packages/battery_plus/battery_plus_windows/windows/battery_plus_windows_plugin.cpp
packages/battery_plus/battery_plus_windows/windows/include/battery_plus_windows/system_battery.h
packages/battery_plus/battery_plus_windows/windows/system_battery.cpp

Adding save power mode getter  in order to disable some functionalities if the device is in battery-save mode.
Only **Android**, **iOS** && **Windows** (thanks to @mzdm) are done for now, need some help for other platforms.
I try to run `melos run format` but without success even in a clean clone.
#229 
[Flutter …

feat(battery_plus): add save power mode getter

---

docs/package_info_plus/usage.mdx
packages/package_info_plus/package_info_plus/README.md

This PR simplifies the **README** of [package_info_plus](pub.dev/packages/package_info_plus) by removing the usage section with `.then` notation.
Closes #315.

[package_info_plus] docs: simplifies the usage

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmBroadcastReceiver.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/ScheduledAlarmsList.java
packages/android_alarm_manager_plus/example/lib/main.dart
packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart
packages/android_alarm_manager_plus/pubspec.yaml

The plugin now stores all the upcoming alarms, be it one shot or periodic and returns a json string containing info about all the
scheduled alarms.  Oneshot alarms are removed from this list when the alarm goes off. Peroidic alarms are removed only when it is explicitly cancelled.
#342  …

feat: get scheduled alarms functionality added.

---

docs/overview.mdx

The links in docs/overview don't work as of now if you go to the url https://plus.fluttercommunity.dev/docs/overview. This is because browser adds a '/' at the end of the url. To fix the issue we can use complete path to docs.
Fixes #397  …

Fixed links in docs/overview.mdx

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java
packages/connectivity_plus/connectivity_plus/pubspec.yaml

connectivity_plus plugin uses ConnectivityManager.NetworkCallback() when the Android OS version is VERSION_CODES.M or above.
Once the network is changed, it sends the latest network state to Flutter by using ConnectivityManager.getActiveNetwork()
(Ref: connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java)
Sometimes getActiveNetwork() returns the network interface (not null) which is just disconnected for network disconnection.
This causes that the network state is shown as connected when it's disconnected.
* I just created a simple patch since the issue #290 is not fixed quickly. If you have a better fix already prepared, please ignore this PR.
https://github.com/fluttercommunity/plus_plugins/issues/290
Before you create this PR confirm that it …

Connectivity_plus detect no-network on Android M and above

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/package_info_plus/pubspec.yaml

This PR restores backward compatibility of `package_info_plus`.
`package_info_plus` violates semantic versioning spec in 1.0.4 where #340 added a required parameter to `PackageInfo`'s public constructor, this is a breaking change to [lines declaring `PackageInfo` as a non-nullable type with dummy values](https://github.com/bottlepay/plus_plugins/blob/a70e634f7094054fb7e13a1b917e49149e57411e/packages/package_info_plus/package_info_plus/example/lib/main.dart#L37-L43).
The change removes the `required` keyword and sets a default value(empty string) to allow the variable to be non-nullable.
Closes #392 
This will ensure a smooth and quick review process. Updating the …

fix(package_info_plus): restore backward compatibility

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/README.md
packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfo.java
packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfoMethodChannelHandler.java
packages/network_info_plus/network_info_plus/example/lib/main.dart
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m
packages/network_info_plus/network_info_plus/ios/Classes/getgateway.c
packages/network_info_plus/network_info_plus/ios/Classes/getgateway.h
packages/network_info_plus/network_info_plus/ios/Classes/route.h
packages/network_info_plus/network_info_plus/lib/network_info_plus.dart
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/test/network_info_test.dart
packages/network_info_plus/network_info_plus_platform_interface/CHANGELOG.md
packages/network_info_plus/network_info_plus_platform_interface/lib/method_channel_network_info.dart
packages/network_info_plus/network_info_plus_platform_interface/lib/network_info_plus_platform_interface.dart
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/test/method_channel_network_info_test.dart

We added for both **iOS** and **Android** support for fetching information : 
- IPv6 address
- Broadcast address
- Gateway address
- Subnet mask
Linux, MacOS and Windows was not done in this PR and need help 👍 
#206 
#132  …

feat(network_info_plus): add ipv6, gateway, broadcast and subnet mask information

---

packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
packages/connectivity_plus/connectivity_plus_linux/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity_real.dart
packages/connectivity_plus/connectivity_plus_linux/pubspec.yaml
packages/connectivity_plus/connectivity_plus_platform_interface/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/enums.dart
packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/utils.dart
packages/connectivity_plus/connectivity_plus_platform_interface/pubspec.yaml
packages/connectivity_plus/connectivity_plus_web/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_web/lib/src/utils/connectivity_result.dart
packages/connectivity_plus/connectivity_plus_web/pubspec.yaml

So far, implemented for Android, Linux, and Web.

Add ethernet as connectivity result

---

packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/battery_plus/ios/Classes/FLTBatteryPlusPlugin.m
packages/battery_plus/battery_plus/test/battery_test.dart

Add break statements for `unknown` battery state in Android and iOS implementations. The lack of these break statements will lead to erroneous errors being emitted when the `unknown` state is emitted. The other implementations seem to properly handle the `unknown` state.
Potentially related issue: https://github.com/fluttercommunity/plus_plugins/issues/231 …

Handle fall through in unknown battery state

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/pubspec.yaml

increase SDK version to address failing publish due to not having ios folder. 
```
Uploading...
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
```

increase flutter sdk, that requires to remove ios folder

---

packages/share_plus/share_plus_linux/CHANGELOG.md
packages/share_plus/share_plus_linux/lib/share_plus_linux.dart
packages/share_plus/share_plus_linux/pubspec.yaml
packages/share_plus/share_plus_linux/test/share_plus_linux_test.dart

As stated here (https://github.com/flutter/flutter/issues/88463#issuecomment-901509331), `canLaunch` doesn't work with sandboxes such as Flatpak, which makes it impossible to share from these containers. 
According to the [documentation](https://pub.dev/documentation/url_launcher/latest/url_launcher/launch.html), `launch` method itself throws a `PlatformException` if the URL scheme is unknown or if there is no corresponding application, so the presence of `canLaunch` in the code is redundant and breaks Flatpak compatibility. 
https://github.com/flutter/flutter/issues/88463
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs …

[share_plus_linux] Fix sharing in Flatpak apps

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

Uses a different share item on iOS so that more share providers (Instagram, etc) kick in
https://github.com/fluttercommunity/plus_plugins/issues/459

[share_plus] Use NSURL for web links

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/pubspec.yaml
packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/example/pubspec.yaml
packages/android_intent_plus/pubspec.yaml
packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/example/pubspec.yaml
packages/battery_plus/battery_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/example/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/sensors_plus/sensors_plus/CHANGELOG.md
packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_web/integration_test/pubspec.yaml

Update `integration_test` to Flutter SDK.
#465

migrate integration_test to flutter sdk

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/ios/Classes/getgateway.c
packages/network_info_plus/network_info_plus/pubspec.yaml

Fix issue #431 network_info_plus: 'net/route.h' file not found when building for iOS emulator
#431 

[network_info_plus] Fix issue #431 network_info_plus: 'net/route.h' file not found when building for iOS emulator

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/ios/Classes/FLTPackageInfoPlusPlugin.m
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_macos/CHANGELOG.md
packages/package_info_plus/package_info_plus_macos/macos/Classes/FLTPackageInfoPlusPlugin.m
packages/package_info_plus/package_info_plus_macos/pubspec.yaml

This PR adds fallback to `CFBundleName` if `CFBundleDisplayName` does not exist. This approach is suggested by Apple in [QA1544](https://developer.apple.com/library/archive/qa/qa1544).
#432 

[package_info_plus] fix app name on iOS and macOS

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_windows/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_windows/pubspec.yaml
packages/connectivity_plus/connectivity_plus_windows/windows/CMakeLists.txt
packages/connectivity_plus/connectivity_plus_windows/windows/connectivity_plus_windows_plugin.cpp
packages/connectivity_plus/connectivity_plus_windows/windows/include/connectivity_plus_windows/network_manager.h
packages/connectivity_plus/connectivity_plus_windows/windows/network_manager.cpp

Add ethernet as connectivity result - #399 for Windows.
One maybe not so obvious change is that `NetworkListener` now implements `INetworkEvents`. It allows to watch for connectivity changes on individual networks and then compute system-wide connectivity type. If you're connected to both Ethernet and Wi-Fi and then disconnecting Wi-Fi, `INetworkListManagerEvents` won't fire callback because overall system connectivity did not change.
For backward compatibility any Internet-connected interface that's not Ethernet is considered Wi-Fi.
Does your PR require …

[connectivity_plus_windows] add ethernet support

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AlarmService.java
packages/android_alarm_manager_plus/pubspec.yaml

This PR fixes `android_alarm_manager_plus` for Android 12+ by adding the `FLAG_IMMUTABLE` to the `PendingIntent`s.
Fixes #477

Fix alarm_manager_plus for Android 12+

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/ios/Classes/FLTCaptiveNetworkInfoProvider.h
packages/network_info_plus/network_info_plus/ios/Classes/FLTCaptiveNetworkInfoProvider.m
packages/network_info_plus/network_info_plus/ios/Classes/FLTHotspotNetworkInfoProvider.h
packages/network_info_plus/network_info_plus/ios/Classes/FLTHotspotNetworkInfoProvider.m
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfo.h
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfo.m
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoProvider.h
packages/network_info_plus/network_info_plus/pubspec.yaml

This PR migrates network info to modern `NEHotspotNetwork` APIs while keeping backward compatibility with older iOS versions. The code looks a little bit overkill for a couple of simple conditions though.
#240

[network_info_plus] ios: handle deprecation of `CNCopyCurrentNetworkInfo`

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/example/macos/Runner.xcodeproj/project.pbxproj
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_macos/CHANGELOG.md
packages/network_info_plus/network_info_plus_macos/macos/Classes/IPHelper.h
packages/network_info_plus/network_info_plus_macos/macos/Classes/NetworkInfoPlusPlugin.swift
packages/network_info_plus/network_info_plus_macos/pubspec.yaml

- Adds a way to obtain IP v6 on MacOS.
- Adds other missing methods on network_info_plus for MacOS.
- Fix #498

[network_info_plus] Implemented get ip v6 macos

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java
packages/android_alarm_manager_plus/pubspec.yaml

The recently merged PR https://github.com/fluttercommunity/plus_plugins/pull/495 didn't include the removal for this package, because the tests were failing (and to not have too much overhead, I reverted the changes).
This PR does the same as https://github.com/fluttercommunity/plus_plugins/pull/495, but for `android_alarm_manger_plus`, and the checks are successful this time (couldn't check the reason locally because the tests use `melos`, maybe just had to add `static` in line 43/44).
Does your PR require plugin users to manually update their apps to …

fix(android_alarm_manager_plus): Remove deprecated method registerWith

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/android/src/main/AndroidManifest.xml
packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/battery_plus/example/android/app/build.gradle
packages/battery_plus/battery_plus/example/android/app/src/main/AndroidManifest.xml
packages/battery_plus/battery_plus/example/android/app/src/main/kotlin/io/flutter/plugins/batteryexample/example/MainActivity.kt
packages/battery_plus/battery_plus/example/android/build.gradle
packages/battery_plus/battery_plus/example/android/gradle.properties
packages/battery_plus/battery_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/battery_plus/battery_plus/pubspec.yaml

This PR:
- Upgrades android compile sdk version to 31
- Upgrades dependencies
- Several code improvements
#505

fix(battery_plus): Upgrade gradle, android compile version & implement code improvements

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/android/src/main/AndroidManifest.xml
packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.java
packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/src/main/AndroidManifest.xml
packages/device_info_plus/device_info_plus/example/android/app/src/main/kotlin/io/flutter/plugins/deviceinfoexample/example/MainActivity.kt
packages/device_info_plus/device_info_plus/example/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/gradle.properties
packages/device_info_plus/device_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/device_info_plus/device_info_plus/pubspec.yaml

This PR:
- Upgrades android compile sdk version to 31
- Several code improvements
#505

fix(device_info_plus): Upgrade gradle, android compile version & implement code improvements

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/pubspec.yaml

This PR reinstates minimum java version for lambda support.
Fixes #516 

fix(connectivity_plus): fix lambda not supported error.

---

CONTRIBUTING.md

I would like to reflect in the CONTRIBUTING document what kind of contributions are expected.
Any ideas or improvements?

Update CONTRIBUTING on types of contributions

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/pubspec.yaml

* In this PR, I have fixed the issue related to setting the package to `null` in `buildIntent()` method. With this fix, `buildIntent()` will not reset the package if the given `intent` is not resolvable which helps to get the expected results from `canResolveActivity()` method.
[#245](https://github.com/fluttercommunity/plus_plugins/issues/245) …

fix(android_intent_plus): fixed a bug!

---

packages/battery_plus/battery_plus/example/pubspec.yaml
packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/example/pubspec.yaml
packages/network_info_plus/network_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/share_plus/share_plus/example/pubspec.yaml

This PR explicitly specify platform-specific implementation paths in example apps.
The reason is the nature of federated plugins. In example apps main package is always specified via path. In case of unfederated plugin, it's platform-specific implementations are already part of the main package and will be picked up when building example (thus accounting for changes in any platform implementation). However with federated plugins main package has it's platform-specific implementations as version-locked dependencies. Building example app takes main package via path (thus accounting for changes Android/iOS implementations), but other platform implementations are resolved to published versions in pub ignoring current changes.
Specifying paths explicitly fixes CI's `pub_get_check` job and …

[examples] explicitly override deps

---

packages/device_info_plus/device_info_plus_macos/macos/Classes/DeviceInfoPlusMacosPlugin.swift

[device_info_plus_macos] fix compiler warnings

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/lib/device_info_plus.dart
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus/device_info_plus_platform_interface/lib/model/web_browser_info.dart
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/test/model/web_browser_info_test.dart

Adds `toMap` method to serialize `WebBrowserInfo` on `device_info_plus`.
Closes #592.

feat(device_info_plus): add toMap method to WebBrowserInfo

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m
packages/network_info_plus/network_info_plus/pubspec.yaml

This PR fixes a small bug in `getWifiInterface` method. It returns address of `ifaddrs` struct that escapes `getifaddrs`/`freeifaddrs` pair. That is considered undefined behaviour and only works because iOS does not reclaim memory immediately.
For consistency with other platform implementations most methods changed to return `null` instead of `error` string, when corresponding piece of information is not available.
For consistency with `macOS` implementation I've replaced `inet_ntoa` with `getnameinfo` which uses [scoped IPv6 address] representation among other things. 
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is …

[network_info_plus_ios] fix undefined behaviour

---

packages/battery_plus/battery_plus/README.md
packages/device_info_plus/device_info_plus/README.md

The path used to display the Flutter Favourite badge in the README of device_info_plus package was incorrect, this PR fixes that path and now the badge is displayed as intended in the README.

Fixed broken link to Flutter Favourite badge in device_info_plus README

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/README.md
packages/device_info_plus/device_info_plus/example/test_driver/device_info_plus_e2e.dart
packages/device_info_plus/device_info_plus/example/test_driver/device_info_plus_e2e_test.dart
packages/device_info_plus/device_info_plus/lib/device_info_plus.dart
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus/device_info_plus_platform_interface/lib/device_info_plus_platform_interface.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/base_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/ios_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/linux_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/macos_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/web_browser_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/windows_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/test/method_channel_device_info_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/linux_device_info_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/windows_device_info_test.dart

This PR adds a new superclass of platform-specific device info objects. `BaseDeviceInfo` exposes one generic `toMap` method to be provided by platform-specific subclasses. Missing implementations provided for Linux and Windows. A new convenience accessor `deviceInfo` returns platform-specific device info. It can either be narrow-typed using `is` or serialized to map.
```dart
final deviceInfoPlugin = DeviceInfoPlugin();
final deviceInfo = await deviceInfoPlugin.deviceInfo;
if (deviceInfo is AndroidDeviceInfo) {
// Android
} else if (deviceInfo is IosDeviceInfo) {
// iOS
} else {
// Other
}
final deviceInfoMap = deviceInfo.toMap();
// Push `deviceInfoMap` to server as a part of bug report, telemetry, etc.
```
#615
Before you create this PR confirm that it meets all requirements listed below …

[device_info_plus] add toMap

---

packages/package_info_plus/package_info_plus/example/ios/Runner/Info.plist
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/example/test_driver/package_info_plus_e2e.dart
packages/package_info_plus/package_info_plus/example/test_driver/package_info_plus_e2e_test.dart

This PR fixes several broken things in integration tests in `package_info_plus`:
- It didn't not work when testing for web (`kIsWeb` must be the first to check, then other platforms).
- Sometime time ago #340 added `buildSignature` to Android without reflecting that in integration tests. So there is one more `Not set` field in all other platforms, causing relevant checks to fail.
- Version fields in iOS were hardcoded in `Info.plist`. The tests were OK with these version numbers, but it just didn't look right.
- The macOS tests failed because they were checking for outdated version numbers.
This will ensure a smooth and quick review process. Updating the …

[package_info_plus] fix e2e tests

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus_linux/CHANGELOG.md
packages/battery_plus/battery_plus_linux/lib/src/upower_device.dart
packages/battery_plus/battery_plus_linux/pubspec.yaml
packages/battery_plus/battery_plus_linux/test/battery_plus_linux_test.dart
packages/battery_plus/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus/battery_plus_platform_interface/lib/method_channel_battery_plus.dart
packages/battery_plus/battery_plus_platform_interface/pubspec.yaml

Update dependencies, so the plugin won't block updates or usage of other plugins as mentioned in #648
Fixes #648

[battery_plus] Update dependencies

---

packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_linux/CHANGELOG.md
packages/network_info_plus/network_info_plus_linux/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/CHANGELOG.md
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml

Update dependencies, so the plugin won't block updates or usage of other plugins as mentioned in #651
Closes #651 

[network_info_plus] Update dependencies

---

packages/network_info_plus/network_info_plus/CHANGELOG.md

In #653 I forgot to update changelog file and missed the fact that pub check failed on Github Actions 🤦🏻‍♂️ 
So 2.1.2 on pub.dev has no changelogs.
This PR fixes this issue. …

[network_info_plus] Add missing changelog update

---

packages/package_info_plus/package_info_plus/test/package_info_test.dart

Skips failing test on Linux which causes all recently submitted PRs to fail `test_and_coverage` CI step.
Flutter 2.8 started to use platform implementations while running tests (flutter/flutter#90288). Linux implementation of `PackageInfoPlus` does not use platform channels thus failing test.
The second issue is versioning. When #574 landed the Linux implementation version and it's dependency in main package were not updated. I don't know if that was required for publishing new code in `pub`, but currently published version `1.0.3` still uses old way of registering Linux plugin. Whatever Flutter 2.8 uses to find and register platform plugins, it cannot find plugins that uses that old way of registering. If you bootstrap with `melos bootstrap --scope package_info_plus` (this is what CI …

[package_info_plus] fix test on linux

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus/device_info_plus_linux/pubspec.yaml
packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
packages/device_info_plus/device_info_plus_windows/lib/src/device_info_plus_windows.dart
packages/device_info_plus/device_info_plus_windows/pubspec.yaml

Right now using published versions of `device_info_plus` on Windows and Linux fails with Flutter 2.8.1. #574 and #598 needs publishing. Fixes #646.

[device_info_plus] update versions for publishing

---

packages/device_info_plus/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus/device_info_plus_linux/pubspec.yaml
packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
packages/device_info_plus/device_info_plus_windows/pubspec.yaml

We need to upgrade to fix 
`Uploading...
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
`
- [ x No, this is *not* a breaking change. …

[Device_info_plus] Update update SDK to >=1.20.0

---

.editorconfig

While working on #666 and #667 I saw that current `.editorconfig` file had config applied to all files in the project, while plugins have more than just Dart file there. In this PR I modified the `.editorconfig` in a way to follow proper code styles for Groovy and Kotlin (https://developer.android.com/kotlin/style-guide) files as well as saved previous config for Dart files. …

Update EditorConfig for different languages

---

packages/android_alarm_manager_plus/README.md
packages/android_intent_plus/README.md
packages/battery_plus/battery_plus/README.md
packages/connectivity_plus/connectivity_plus/README.md
packages/device_info_plus/device_info_plus/README.md
packages/network_info_plus/network_info_plus/README.md

I improved each plugin's README.md content and unified its format.
What I did is 
- move `#h1` tag to at the top of README.md(`android_alarm_manager_plus`, `android_intent_plus`, `share_plus`)
- fix broken image link(`connectivity_plus`, `network_info_plus`, `package_info_plus`, `sensors_plus`, `share_plus`)
- insert/fix GitHub Actions badge(all plugin)

improve each plugin README.md and unify their format

---

.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

In #687 I broke workflow files for every individual plugin due to including both `paths` and `paths-ignore` which is not allowed for Github Actions. This PR address the issue by using proper filtering according to docs: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
[Flutter Style …

Fix files filtering in workflow triggers

---

.github/workflows/all_plugins.yaml

This PR adds https://github.com/invertase/github-action-dart-analyzer Action to automatically add review comments to PRs opened in this repository. I believe it will help maintainers to get better visual feedback, so less people will ignore analyzer issues due to no requirement to go through Actions logs. …

Add Dart Analyzer Action

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/battery_plus/example/lib/main.dart
packages/battery_plus/battery_plus/ios/Classes/FLTBatteryPlusPlugin.m
packages/battery_plus/battery_plus/lib/battery_plus.dart
packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus/test/battery_test.dart
packages/battery_plus/battery_plus_linux/CHANGELOG.md
packages/battery_plus/battery_plus_linux/lib/src/battery_plus_linux.dart
packages/battery_plus/battery_plus_linux/pubspec.yaml
packages/battery_plus/battery_plus_linux/test/battery_plus_linux_test.dart
packages/battery_plus/battery_plus_macos/CHANGELOG.md
packages/battery_plus/battery_plus_macos/macos/Classes/BatteryPlusMacosPlugin.swift
packages/battery_plus/battery_plus_macos/pubspec.yaml
packages/battery_plus/battery_plus_platform_interface/CHANGELOG.md
packages/battery_plus/battery_plus_platform_interface/lib/battery_plus_platform_interface.dart
packages/battery_plus/battery_plus_platform_interface/lib/method_channel_battery_plus.dart
packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
packages/battery_plus/battery_plus_platform_interface/test/battery_plus_platform_interface_test.dart
packages/battery_plus/battery_plus_web/CHANGELOG.md
packages/battery_plus/battery_plus_web/lib/battery_plus_web.dart
packages/battery_plus/battery_plus_web/pubspec.yaml
packages/battery_plus/battery_plus_windows/CHANGELOG.md
packages/battery_plus/battery_plus_windows/pubspec.yaml
packages/battery_plus/battery_plus_windows/windows/battery_plus_windows_plugin.cpp

This PR adds a `Battery.batteryState` getter on the side of the existing `Battery.onBatteryStateChanged` to make it straightforward to query the current battery state without having to listen to a stream.
Closes: #685

[battery_plus] add batteryState getter

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/lib/android_intent.dart
packages/android_intent_plus/pubspec.yaml

In Android, the [Intent](https://developer.android.com/reference/android/content/Intent.html#intent-structure) class has two different methods to put an [array](https://developer.android.com/reference/android/content/Intent#putExtra(java.lang.String,%20java.lang.String[])) and [array list](https://developer.android.com/reference/android/content/Intent#putStringArrayListExtra(java.lang.String,%20java.util.ArrayList%3Cjava.lang.String%3E)) values to the intent. And in the previous implementation, we only use one of them, which is used to put array list values to the intent. And since dart `List` type is[ mapped to](https://docs.flutter.dev/development/platform-integration/platform-channels?tab=type-mappings-java-tab#codec) `ArrayList` in java, it limits users to pass array types to the …

[android_intent_plus]: Added a new argument to explicitly pass array arguments to an intent

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/FlutterBackgroundExecutor.java
packages/android_alarm_manager_plus/pubspec.yaml

This PR fixes a small bug in `android_alarm_manager_plus` initialization code. 
There is a common workaround to include `io.flutter.app.FlutterApplication` as application name in manifest, but that does not feel right, because of mixing V1 embedding with V2. All `FlutterApplication` doing is initializing `FlutterLoader` explicitly. However more modern V2 embedding relies on implicit `FlutterLoader` initialization during instantiation of `FlutterEngine`. The fix is to instantiate `FlutterEngine` first, then call `findAppBundlePath` (which is annotated `NonNull`, so additional check is redundant).
Fixes #649, supersedes #690.
This will ensure a smooth and quick review …

[android_alarm_manager_plus] fix initialization

---

packages/device_info_plus/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus/device_info_plus_macos/macos/Classes/DeviceInfoPlusMacosPlugin.swift
packages/device_info_plus/device_info_plus_macos/pubspec.yaml

I have tested the lastest version on my macOS  Monterey 12.1, the computer name and os version is incorrect.
```
{arch: x86_64, model: MacBookPro14,1, hostName: Darwin, osRelease: 21.2.0, activeCPUs: 4, memorySize: 8589934592, cpuFrequency: 2300000000, computerName: 192.168.1.5, kernelVersion: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64, systemGUID: A23CF907-4FB2-50E8-A3F5-E8F2DE4BC121}
```
The computer name is IP address '192.168.1.5', but actually should be 'MegatronKing's Book'. And the os version should be Monterey 12.1 rather than the Darwin kernal version.
I fixed this bug and test seems ok.
```
{arch: x86_64, model: MacBookPro14,1, hostName: Darwin, osRelease: Version 12.1 (Build 21C52), activeCPUs: 4, memorySize: 8589934592, …
```

[device_info_plus] Fixed incorrect computer name and version on MacOS

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/android/src/main/java/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.java
packages/battery_plus/battery_plus/pubspec.yaml

This PR addresses the issue for users with Samsung devices with new Android versions where check `isInBatterySaveMode()` was throwing a null pointer exception. It seems that since some time ago (I suspect it happened when Samsung switched from TouchWiz to OneUI) there is no need in using some Samsung specific APIs and values. Due to this change the standard Android API to check batter save mode works fine and returns proper result. 
Since we don't know for sure which Samsung devices use old Samsung way and which not I have just added an additional check to see if calling old API returns null and in such case just call an Android default `PowerManager` to check the mode.
Fix was tested on Galaxy S9+ with Android 10 / One UI 2.5
Closes #713 
Before you create this PR confirm that it meets …

[battery_plus_info] Fix NPE on modern Samsung devices

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/example/android/app/src/main/AndroidManifest.xml
packages/package_info_plus/package_info_plus/example/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/package_info_plus/package_info_plus/pubspec.yaml

Another PR in series to fix embedding issues after update to Flutter 2.10. Additionally, updated Android Gradle plugin and Gradle wrapper version.

[package_info_plus] Fix embedding issue in example

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/src/main/AndroidManifest.xml
packages/device_info_plus/device_info_plus/example/android/build.gradle
packages/device_info_plus/device_info_plus/pubspec.yaml

Another PR in series to fix embedding issues after update to Flutter 2.10.
This one also has updates to Kotlin and Gradle plugins, since in the latest Android Studio example won't build due to very old Kotlin version.
[pub versioning …

[device_info_plus] Fix embedding issue in example, update Android dependencies

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/example/android/app/src/main/AndroidManifest.xml
packages/battery_plus/battery_plus/example/android/build.gradle
packages/battery_plus/battery_plus/pubspec.yaml

Another PR in series to fix embedding issues after update to Flutter 2.10.
This one also has updates to Kotlin and Gradle plugins, since in the latest Android Studio `example` won't build due to very old Kotlin version.
[pub versioning …

[battery_plus] Fix example embedding issue, dependencies updates

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/example/android/app/src/main/AndroidManifest.xml
packages/android_intent_plus/pubspec.yaml

Updates to make plugin work with Flutter 2.10 and not fail CI checks. 
- Changed AndriodManifest to use proper application name to not see warning about old embedding.
- Updated `platform` dependency to not use deprecated/removed functions.
This PR supersedes #722, which lacked changelogs update and plugin version bump. …

[android_intent_plus] Fix example embedding issue, update Platform dependency

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_linux/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_linux/pubspec.yaml

`dbus` plugin 0.7.0 is out so `gsettings` is conflicting with `connectivity_plus` as they both are dependent on `dbus`. So I Bumped `nm` to 0.5.0.
Also I bumped `connectivity_plus_linux` to 1.3.0 and updated the CHANGELOG.
N.A. …

[connectivity_plus_linux] Bump nm to 0.5.0

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/network_info_plus/network_info_plus/example/ios/Flutter/Flutter.podspec
packages/network_info_plus/network_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/network_info_plus/network_info_plus/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/network_info_plus/network_info_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_linux/CHANGELOG.md
packages/network_info_plus/network_info_plus_linux/pubspec.yaml
packages/network_info_plus/network_info_plus_macos/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/CHANGELOG.md
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus/network_info_plus_web/pubspec.yaml
packages/network_info_plus/network_info_plus_windows/pubspec.yaml

PR to update `nm` dependency, so network_info_plus is compatible with latest `connectivity_plus` and `battery_plus` plugins.
Additionally, did the same change as in recent #755 and made every platform plugin use the same version min Flutter version.
Closes #761
[pub versioning …

[network_info_plus] Dependencies update

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_macos/CHANGELOG.md
packages/share_plus/share_plus_macos/macos/Classes/SharePlusMacosPlugin.swift
packages/share_plus/share_plus_macos/pubspec.yaml
packages/share_plus/share_plus_platform_interface/CHANGELOG.md
packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
packages/share_plus/share_plus_platform_interface/lib/share_plus_platform_interface.dart
packages/share_plus/share_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart

As per #386 a lot of users would like to know how the user interacted with the share-sheet, so this PR adds exactly this capability. It does this by providing the two extra methods `shareWithResult` and `shareFilesWithResult` on `Share`, which both return a `ShareResult` which can then be used to determine if the user completed an action or dismissed the dialogue. It also provides the user with information on the specific share action (app/build-in) the user might have taken.
By adding this as two new methods, no other APIs have to change. It would be possible to add this feature as an argument to the "old" `share` and `shareFiles` -> `bool withResult = false`, but that would require updating all other *share_plus* platforms implementation, which could probably break some code somewhere …

[share_plus] add ability to get feedback on user action + 100% coverage

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_linux/CHANGELOG.md
packages/share_plus/share_plus_linux/pubspec.yaml
packages/share_plus/share_plus_macos/CHANGELOG.md
packages/share_plus/share_plus_macos/pubspec.yaml
packages/share_plus/share_plus_platform_interface/CHANGELOG.md
packages/share_plus/share_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus_web/CHANGELOG.md
packages/share_plus/share_plus_web/pubspec.yaml
packages/share_plus/share_plus_windows/CHANGELOG.md
packages/share_plus/share_plus_windows/pubspec.yaml

Fix share_plus 4.0.0

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/CHANGELOG.md
packages/share_plus/share_plus_platform_interface/pubspec.yaml

In this PR I fixed issues with type in `result.error()`, which some users reported in #758. Saw that the code wasn't formatted according to our `editorconfig` file, which was added some time ago, so reformatted the code.
I didn't like that `share_plus` now has minSDK 23 as it cuts quite a lot of users/devices. I thought we could make it much lower, but it seems that 22 is the minimum possible, because `Intent.createChooser()` with `sender` parameter appeared only in SDK 22. So I made required changes to set minSDK to 22 and some additional small fixes.
Finally, I saw that in #788 there were changes to min Flutter version, but not all platforms were updated. Fixed it as well, so `share_plus` requires Flutter 1.20 on all platforms now.
Closes #758
Partially closes #789 
Before you create …

[share_plus] Fix types, lower Android minSDK

---

docs/share_plus/usage.mdx
packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/CHANGELOG.md
packages/share_plus/share_plus_platform_interface/lib/share_plus_platform_interface.dart
packages/share_plus/share_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart

- Revert `minSdkVersion` back to 16 and dynamically determine support for `shareWithResult` at runtime
- Gracefully fall back to "normal" share without result if the environment does not support `shareWithResult`
- Improve documentation for `shareWithResult`
Closes #789
[pub …

[share_plus] minSdkVersion 16 & graceful fallback

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_linux/CHANGELOG.md
packages/package_info_plus/package_info_plus_linux/pubspec.yaml
packages/package_info_plus/package_info_plus_windows/CHANGELOG.md
packages/package_info_plus/package_info_plus_windows/pubspec.yaml

At commit 7e898675fbd18cb6ac90f36c1e6bd126aea1c64d the plugins for windows and linux had changes to auto register via `static void registerWith()`. But neither the plugins nor the main package versions were increased and published.
This commit fixes that by increasing the versions of the plugins and the main package.
Closes #806
Closes #760
Closes #747
Closes #773
[Flutter …

[package_info_plus] fix MissingPluginException for windows and linux

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/example/test_driver/package_info_plus_e2e.dart
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_linux/CHANGELOG.md
packages/package_info_plus/package_info_plus_linux/lib/src/package_info.dart
packages/package_info_plus/package_info_plus_linux/pubspec.yaml
packages/package_info_plus/package_info_plus_web/CHANGELOG.md
packages/package_info_plus/package_info_plus_web/lib/package_info_plus_web.dart
packages/package_info_plus/package_info_plus_web/pubspec.yaml
packages/package_info_plus/package_info_plus_web/test/package_info_plus_web_test.dart

package_info_plus for linux and web returns now return the `package_name` contained in the `version.json` file (which was introduced in [this PR](https://github.com/flutter/flutter/pull/88457)) 
See the data returned on both web and linux platforms :
Closes #203
[pub versioning …

[package_info_plus] Resolve package name linux and web

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/ios/Classes/ReachabilityConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus/pubspec.yaml

- Resolves "reference to member 'unavailable' cannot be resolved without a contextual type" error that occurs during ios compilation.
Closes #656 

fix(connectivity_plus): Reachability.swift ".unavailable" is deprecated

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus/device_info_plus_macos/macos/Classes/CwlSysctl.swift
packages/device_info_plus/device_info_plus_macos/pubspec.yaml

This PR adds handling of macOS Sysctl.value() errors to avoid crashing when the sysctl call fails (e.g. no "hw.cpufrequency" present on Apple M1 macOS builds).
Fixes #825.

[device_info_plus] Fix crash on macOS running on Apple M1

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

This PR fixes a bug where the subject is not set when sharing a raw URL e.g. "https://example.com" or files via email.
Fixes #691

[share_plus] fix subject when sharing raw url or files

---

packages/battery_plus/battery_plus_macos/CHANGELOG.md
packages/battery_plus/battery_plus_macos/macos/Classes/BatteryPlusChargingHandler.swift
packages/battery_plus/battery_plus_macos/pubspec.yaml

Adds a case to handle macOS desktop such as Mac mini.
Withtout this check the application simply crashes when trying to access the first element of the empty list of battery sources.

[battery_plus_macos] Fix crash on macOS running on Apple Mac mini

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/ios/Classes/PathMonitorConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus/ios/Classes/ReachabilityConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus/ios/Classes/SwiftConnectivityPlusPlugin.swift
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/PathMonitorConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ReachabilityConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml

* copied from MacOS implementation
* available on iOS 12+
* correctly notifies when switching between Wifi networks without internet access
Fixes #632 for iOS 12+

[connectivity_plus] Add NWPathMonitor based ConnectivityProvider for iOS

---

.github/workflows/all_plugins.yaml

Job for pub.dev requirements check used just `pub` command, which [is deprecated and removed](https://dart.dev/tools/pub/cmd). Because of this command our recent CI runs fail on mentioned step.
-

[CI/CD] Replace deprecated pub command

---

packages/sensors_plus/sensors_plus/CHANGELOG.md
packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt
packages/sensors_plus/sensors_plus/pubspec.yaml

Fixed crash related to `lateinit` variable when closing app with back button on android
https://github.com/fluttercommunity/plus_plugins/pull/753#issuecomment-1098022408

[sensors_plus] Fixed crash when app closes if streams haven't been listened to

---

packages/connectivity_plus/connectivity_plus/ios/Classes/SwiftConnectivityPlusPlugin.swift

`SwiftConnectivityPlusPlugin` might receive updates from background threads, but it always needs to use the Flutter channel on the main thread. 
Fixes #845

[connectivity_plus] Send events on main thread

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

Currently, when using sharing files on iOS, saved files would have new generic names like "image PNG", "image PNG 2", etc, instead of ones they were shared with.
This PR also fixes an issue where images had no previews and the share-sheet always displayed the App's icon.
As always I provide a test respository for these changes [here](https://github.com/Coronon/share_plus_example).
Fixes #821
Closes #808 …

[share_plus] iOS: fix file names and preview

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ConnectivityPlugin.swift
packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml

I stumbled on bug #845 on macOS and noticed that there was a PR to fix it (#846). However that PR only fixes the iOS plugin, so I replicated the change made to `connectivity_plus/ios/Classes/SwiftConnectivityPlusPlugin.swift` also to `connectivity_plus_macos/macos/Classes/ConnectivityPlugin.swift`.

[connectivity_plus] Send events on main thread, macos too

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

The 'Save Image' option was not showing when invoking the ShareSheet with share_plus after `4.0.6` which switched to use the before abandoned `ShareDate` class again. The implementation of `activityViewControllerPlaceholderItem` did not provide enough context to the OS however to display the image specific options. Other apps that allow sharing were not effected as they relied upon `itemForActivityType`.
As always, I provide a working example [here](https://github.com/Coronon/share_plus_example).
Fixes #897
[issue database]: …

[share_plus] fix 'Save Image' option not showing

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_web/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_web/lib/connectivity_plus_web.dart
packages/connectivity_plus/connectivity_plus_web/pubspec.yaml

This PR disables the use of the `NetworkInformationAPI` implementation, as it is still experimental.
I don't see this change as a breaking change, as the extra information that is exposed by `NetworkInformation` from `dart:html` is not exposed to end users.
Context: https://github.com/fluttercommunity/plus_plugins/issues/639#issuecomment-1153099644
See also [NetworkInformation API docs](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation)
https://github.com/fluttercommunity/plus_plugins/issues/639
https://github.com/fluttercommunity/plus_plugins/issues/856
https://github.com/fluttercommunity/plus_plugins/issues/641
https://github.com/fluttercommunity/plus_plugins/issues/436

[connectivity_plus_web] Disable network information api

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

A previous fix shared images in `itemForActivityType` as `UIImage` instances, which allowed proper previews to be shown, while it also fixed file names by sharing other mime types as `NSURL`. This broke the file name for images, which were converted to PNG by `UIImage imageWithContentsOfFile:`.
With this fix, previews are shown and the file name/type is properly preserved.
I provide a [test project](https://github.com/Coronon/share_plus_example) as always.
Fixes #914
Also fixes #900 on a sidenote
[issue database]: …

[share_plus] fix image file names not preserved

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
packages/device_info_plus/device_info_plus_windows/pubspec.yaml

According to report in #824 Google Play's new policies discourage usage of unique ids, by requiring to explicitly declare usage of such ids in Data Safety section. I recently had similar experience with `flutter_segment` package, which used segment_analytics Android library, which was accessing AndroidId as well: https://github.com/la-haus/flutter-segment/issues/30
I believe we should exclude AndroidId from set of data returned by `device_info_plus`, so people, who use the package don't have to declare collection of unique IDs in Data Safety section on their Google Play Store listing. Bumped the major version, since removal is a breaking change from my point of view. Those, who would still need to use AndroidId for some reason could use older version of `device_info_plus`.
Additionally, …

[device_info_plus] Remove AndroidId, update Windows dependencies

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/ios/Classes/SwiftConnectivityPlusPlugin.swift
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ConnectivityPlugin.swift
packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml

This PR ensures that once the flutter engine has been detached on iOS and macOS, the engine is no longer called with events. It appears to already have been done on android and I'm not familiar enough with the flutter <-> windows integration to tackle that (although it might need to be done eventually).
I'm really not sure how to write tests for this so I left that unchecked.
#865 
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBU …

[connectivity_plus] Stop sending events when detached from flutter

---

.github/workflows/stale.yml

We don't want feature requests to be marked as stale and closed automatically by a recently added bot. In this PR I added an exclusion, so `enhancement` labeled issues won't be touched by the bot.
Additionally adjusted the time period after which bot marks issues and PRs as stale to better match the activity in the repository by maintainers.
No related issue
[Flutter Style …

[CI/CD] Exclude feature requests from stale state, adjust time periods

---

packages/share_plus/share_plus/lib/share_plus.dart

Amend documentation to avoid confusion as in #864
It was not clear that this parameter could be used on Macs.
#864

[share_plus] document sharePositionOrigin for Macs

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_web/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_web/lib/src/dart_html_connectivity_plugin.dart
packages/connectivity_plus/connectivity_plus_web/pubspec.yaml

…
This was also changed on the original connectivity package but I think it happened right after this package was copied. See https://github.com/flutter/plugins/blob/connectivity-v3.0.6/packages/connectivity/connectivity_for_web/lib/src/dart_html_connectivity_plugin.dart

[connectivity_plus_web] fix Bad state: Stream has already been listened to

---

packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_windows/CHANGELOG.md
packages/package_info_plus/package_info_plus_windows/pubspec.yaml

`package_info_plus`:
Bump minimum dart version to 2.17.0.
Updated package_info_plus_windows to version 2.0.0.
Updated package_info_plus_macos to 1.3.0.
Updated test to 1.21.1.
Updated flutter_lints to 2.0.1.
`package_info_plus_windows`:
Bump minimum dart version to 2.17.0.
Update ffi dependency to 2.0.1 (#941).
Updated win32 to 2.7.0.
Updated flutter_lints to 2.0.1.
#941  …

[package_info_plus] Update dependencies

---

packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/android/src/main/java/dev/fluttercommunity/plus/network_info/NetworkInfo.java
packages/network_info_plus/network_info_plus/pubspec.yaml

Fixed a bug of wifi name not getting with double quotes #986  
#968 

fix(network_info_plus): fixed a bug!

---

packages/android_alarm_manager_plus/CHANGELOG.md
packages/android_alarm_manager_plus/pubspec.yaml
packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/pubspec.yaml
packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/CHANGELOG.md
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/sensors_plus/sensors_plus/CHANGELOG.md
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/pubspec.yaml

Pub.dev now has the feature for adding custom links to GitHub issues (before, it was generated automatically).
This PR sets the link to plus_plugins issues filtered by the package's tag.
(the update for `device_info_plus` is included in https://github.com/fluttercommunity/plus_plugins/pull/1007)
none …

Add issue tracker links

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus/device_info_plus_linux/pubspec.yaml
packages/device_info_plus/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus/device_info_plus_macos/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_test.dart
packages/device_info_plus/device_info_plus_web/CHANGELOG.md
packages/device_info_plus/device_info_plus_web/pubspec.yaml
packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
packages/device_info_plus/device_info_plus_windows/pubspec.yaml

- Revert "Revert 4.1.0 device_info_plus changes (#1020)"
- Version bumps
https://github.com/fluttercommunity/plus_plugins/issues/939#issuecomment-1213044548

Redo changes in device_info_plus_platform_interface 2.6.0

---

packages/share_plus/share_plus/example/integration_test/share_plus_test.dart

Now our integration test supports the Android platform.
Write an integration test of the share_plus plugin supporting the Android Platform.
This is a GSoC task, so there are no associated issues for now.

test(share_plus): Integration test

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

Following the issue reported in #730 and performing some tests, I've found that the share functionality on iOS doesn't seem to work well.
Trying to share text caused the app to show an empty share sheet (no apps listed).
Seems that the issue is caused by attempting to encode the incoming text string as a NSURL object.
I don't understand why we need to do that, but this causes issues.
This change removes that line of code, and sharing works again.
The following has been tested and worked:
- Sharing text with Telegram
- Sharing text + Image with Telegram (both appear)
- Sharing text + subject on Mail (text and subject are set correctly)
- Sharing text + subject + image on Mail (all three appear correctly - see screenshot in comments)
Gmail seems to have issues supporting the "subject" …

(share_plus) fix text share on iOS

---

.github/workflows/all_plugins.yaml
README.md

Reporting code coverage sounds like a good idea, but it has some drawbacks:
1. Codecov only considers the coverage of Unit Tests.
2. Our code is mainly located in the native side of the plugin.
3. We rely on Integration Tests, which aren't considered for code coverage.
4. The report gives misleading results, marking a job as failed because the coverage changed.
Because of these, I'd like to remove the Codecov coverage reports.

Remove Codecov coverage reports from PRs

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

iOS: Fix Instagram does not show up in provider list for web links
- issue #459 appear again
- put back NSURL for the shareText, when text is pure URL
- using LPMetadataProvider to get LPLinkMetadata make the user experience better
[#459](https://github.com/fluttercommunity/plus_plugins/issues/459) …

[share_plus] Fix Instagram does not show up in provider list for web links

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

(iPad and maybe Mac): The sharePositionOrigin must be in the coordinate space of sourceView. See https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller/1622324-sourcerect, else `[LayoutConstraints] Unable to simultaneously satisfy constraints.` appears.
Before you create this PR confirm that it …

fix(share_plus): Throw error if sharePositionOrigin not in sourceView

---

packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus_windows/CHANGELOG.md
packages/battery_plus/battery_plus_windows/pubspec.yaml
packages/battery_plus/battery_plus_windows/windows/battery_plus_windows_plugin.cpp

battery_plus_windows.
This commit only contains the changes to battery_plus_windows, without the fixes that caused compilation issues in connectivity_plus_windows.
Reapplies the reverted changes to battery_plus_windows
#1086  …

[windows] Fixes crashes when listening to update streams in

---

.github/workflows/build_deploy_website.yaml

Looks like Firebase Action doesn't respect the `defaults` syntax as it didn't find `firebase.json` file: https://github.com/fluttercommunity/plus_plugins/actions/runs/3154184239/jobs/5131506340
Trying to fix it by using available `entryPoint` parameter.

[website] Add explicit entry point for Firebase Deploy Action

---

docs/android_alarm_manager_plus/usage.mdx
packages/android_alarm_manager_plus/README.md
website/docusaurus.config.js

Recently added FAQ in Alarm Manager README should be added to Plus plugins website as well. This PR adds it. I also added a link to https://dontkillmyapp.com/ to let people find more info on possible battery optimisation issues they might have.
Also found out that `Edit this page` button at the bottom of every page on the website doesn't work because of wrong path. Fixed it as well.

[website] Add FAQ for Alarm Manager, fix Edit this page link

---

packages/battery_plus/battery_plus/CHANGELOG.md
packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt
packages/battery_plus/battery_plus/pubspec.yaml

Fixes battery state always return unknown on API lesser than 26. I manually verified by running locally. but, how do you write a test for this fix?
#944 

[Battery_plus] Fix: batteryState always return unknown on API < 26

---

.github/workflows/build_preview_website.yaml

Adding ignored paths to avoid triggering website preview build when non website related files are changed, so we don't have issues, like in #1113 where checks are marked as failed because of the failing website preview workflow.

[Github Actions] Add ignored paths for Build website preview workflow

---

.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/share_plus.yaml
packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart
packages/battery_plus/battery_plus/lib/battery_plus.dart
packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart
packages/share_plus/share_plus/example/integration_test/share_plus_test.dart

Adds workflow steps to run integration tests for MacOS for plugins:
- battery_plus
- connectivity_plus
- device_info_plus
- network_info_plus
- package_info_plus
Also, tweaked a few tests to adapt for MacOS
These packages / APIs aren't implemented in MacOS yet, so haven't added them.
- `sensors_plus`
- `share_plus`
- `battery_plus`'s `isInBatterySaveMode`
Fixes #1105 …

Enable Integration tests for MacOS

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
packages/android_intent_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
packages/android_intent_plus/example/android/build.gradle
packages/android_intent_plus/example/android/gradle.properties
packages/android_intent_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/android_intent_plus/pubspec.yaml

Fix for #245 broke the functionality of safe fallback from explicit to implicit intent when package can't be resolved. This PR adds such functionality back.
Additionally updated Android Gradle plugin and used Gradle version.
Closes #919  …

[android_intent_plus] Fix fallback to implicit intent

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/ios/Classes/PathMonitorConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus/ios/Classes/ReachabilityConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_macos/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/PathMonitorConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus_macos/macos/Classes/ReachabilityConnectivityProvider.swift
packages/connectivity_plus/connectivity_plus_macos/pubspec.yaml

- Discard usued warnings for `ensurePathMonitor` call in macOS and iOS.
- Discard usued warnings for `ensureReachability` call in macOS and iOS.
Fixes: #1078

[connectivity_plus] discard unused result warning for method calls

---

.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/scripts/integration-test.sh
.github/workflows/share_plus.yaml
packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart
packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart

* Runs integration_test on Linux.
* Ignores the share_plus integration test on Linux -> it works for me locally but it seems that the github runners do not implement mailto. If we consider this part of this issue, please comment about it and I will start working on it.
The solution is to create a virtual device using Xvfb and have that as the display that flutter is expecting.
[Request]: Integration tests for Linux #1104  …

[linux test integration] - run Linux tests in CI 1104

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/device_info_plus/device_info_plus/ios/Classes/FLTDeviceInfoPlusPlugin.m
packages/device_info_plus/device_info_plus/pubspec.yaml

Currently, `iosInfo.utsname.machine` returns the underlying architecture of the iOS device when the device is a simulator. This updates the behavior to return the simulator's model identifier instead (e.g. `iPhone 15,2` for an iPhone 14 Pro).
https://github.com/fluttercommunity/plus_plugins/issues/273 …

[device_info_plus] Detect iOS simulator model identifier

---

docs/network_info_plus/usage.mdx
packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/README.md
packages/network_info_plus/network_info_plus/android/src/main/AndroidManifest.xml
packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfo.kt
packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfoPlusPlugin.kt
packages/network_info_plus/network_info_plus/example/android/app/src/main/AndroidManifest.xml
packages/network_info_plus/network_info_plus/example/lib/main.dart
packages/network_info_plus/network_info_plus/pubspec.yaml

While working on #1090 saw that plugin uses some deprecated APIs.
Namely, there were usages of:
- [WifiManager.connectionInfo()](https://developer.android.com/reference/android/net/wifi/WifiManager#getConnectionInfo())
- [WifiInfo.getIpAddress()](https://developer.android.com/reference/android/net/wifi/WifiInfo#getIpAddress())
- [WifiManager.getDhcpInfo()](https://developer.android.com/reference/android/net/wifi/WifiManager#getDhcpInfo())
I modified the code, so on devices with Android 12 (S) and newer plugin uses new recommended way of getting the same information. Now plugin relies on [ConnectivityManager.getLinkProperties()](https://developer.android.com/reference/android/net/ConnectivityManager#getLinkProperties(android.net.Network)) and …

[network_info_plus] Use new Android APIs

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/pubspec.yaml

`UIApplication.keyWindow` is deprecated in iOS 13+, leading to iOS 13+ applications built with the `share_plus` plugin to emit deprecation warnings on build. In addition, `UIApplication.keyWindow` is not guaranteed to work in the future.
This PR changes the `RootViewController()` function to check if the iOS version is `>13`, and if so, uses the new approach instead of `UIApplication.keyWindow`.
See https://stackoverflow.com/questions/57134259/how-to-resolve-keywindow-was-deprecated-in-ios-13-0#answer-58031897 for more information.
I have tested this change using the `share_plus` example on the iOS Simulator.
Fixes #917
This will ensure a smooth and quick review …

[share_plus] Remove usage of deprecated UIApplication.keyWindow in iOS 13+

---

packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus/device_info_plus_linux/pubspec.yaml
packages/device_info_plus/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus/device_info_plus_macos/pubspec.yaml
packages/device_info_plus/device_info_plus_web/CHANGELOG.md
packages/device_info_plus/device_info_plus_web/pubspec.yaml

Plugin already published under 5.0.1, this PR is just to save the changes.

Fix #1162 device_info_plus federated plugin versions

---

packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/pubspec.yaml

Keeping the share_plus dependencies up to date
Maybe #1167

(share_plus) update internal dependencies

---

packages/android_intent_plus/CHANGELOG.md
packages/android_intent_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus/CHANGELOG.md
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_web/CHANGELOG.md
packages/connectivity_plus/connectivity_plus_web/pubspec.yaml
packages/device_info_plus/device_info_plus/CHANGELOG.md
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_linux/CHANGELOG.md
packages/device_info_plus/device_info_plus_linux/pubspec.yaml
packages/device_info_plus/device_info_plus_macos/CHANGELOG.md
packages/device_info_plus/device_info_plus_macos/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/CHANGELOG.md
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus_web/CHANGELOG.md
packages/device_info_plus/device_info_plus_web/pubspec.yaml
packages/device_info_plus/device_info_plus_windows/CHANGELOG.md
packages/device_info_plus/device_info_plus_windows/pubspec.yaml
packages/network_info_plus/network_info_plus/CHANGELOG.md
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/sensors_plus/sensors_plus/CHANGELOG.md
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/sensors_plus/sensors_plus_platform_interface/CHANGELOG.md
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml
packages/sensors_plus/sensors_plus_web/CHANGELOG.md
packages/sensors_plus/sensors_plus_web/pubspec.yaml
packages/share_plus/share_plus/CHANGELOG.md
packages/share_plus/share_plus/pubspec.yaml

This is the result of running `melos version --no-git-tag-version`.
I'd like to do a patch release using melos following the instructions in the CONTRIBUTING guide.
All packages have the same release message:
```
- **CHORE**: Version tagging using melos.
```
After this gets merged, it will be published and tags created.

chore(release): prepare for release

---

.github/workflows/share_plus.yaml
packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/example/lib/utils/file_picker_web.dart
packages/share_plus/share_plus/example/lib/utils/file_picker_win.dart
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus_windows/.clang-format
packages/share_plus/share_plus_windows/lib/share_plus_windows.dart
packages/share_plus/share_plus_windows/lib/src/version_helper.dart
packages/share_plus/share_plus_windows/pubspec.yaml
packages/share_plus/share_plus_windows/test/share_plus_windows_test.dart
packages/share_plus/share_plus_windows/windows/.gitignore
packages/share_plus/share_plus_windows/windows/CMakeLists.txt
packages/share_plus/share_plus_windows/windows/include/share_plus_windows/share_plus_windows_plugin_c_api.h
packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin.cpp
packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin.h
packages/share_plus/share_plus_windows/windows/share_plus_windows_plugin_c_api.cpp
packages/share_plus/share_plus_windows/windows/vector.h

This brings support for all the existing `package:share_plus` methods to Windows:
- `share`
- `shareFiles`
- `shareWithResult`
- `shareFilesWithResult`
- `shareXFiles`
This pull request adds the modern Share UI (_i.e._ `DataTransferManager`) for Windows 10 or greater.
It is very rich in experience & uses same UWP API through WRL.
The feature parity is equivalent as other platforms. Text, subject, images & files are supported.
On older Windows versions, existing behavior is kept (opening `mailto:` URL with subject & body).
https://user-images.githubusercontent.com/28951144/193889028-b15f6c3c-9fc1-442c-b472-39b848fcf0ae.mp4
This PR closes following issues:
- Closes #333. 
- Closes #999.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …

feat(share_plus)!: Native share UI for Windows

---

packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
packages/connectivity_plus/connectivity_plus_linux/lib/src/connectivity.dart
packages/connectivity_plus/connectivity_plus_linux/test/connectivity_plus_linux_test.dart
packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/enums.dart
packages/connectivity_plus/connectivity_plus_platform_interface/lib/src/utils.dart

adds support for vpn as `ConnectivityResult` to android and linux.
for android - added it as there is a parameter for it, but haven't tested it on device as i don't have a VPN.
for linux - again, added it (taking the word of the issue author) but can't test it on device.
for macos / ios - i suppose they don't support knowing if a vpn is active as i wasn't able to find any doc supporting it. the APIs currently use don't have such a parameter.
for windows, web - tried searching for something, but not an expert so will leave it to them / a feature request to come up.
Fixes #1166
Does your PR require plugin users to …

feat(connectivity_plus): vpn support for android and linux

---

packages/android_intent_plus/README.md

Documents usage  of `canResolveActivity()` for Andorid 11 and up. With links to official documentation
Fixes: https://github.com/fluttercommunity/plus_plugins/issues/850
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*
*e.g.*
- *Fix #123*
- *Related #456*

docs(android_intent_plus): Add documentation for canResolveActivity

---

CONTRIBUTING.md

Saw that `Contribution guide` has invalid command to activate Melos, so fixing the issue in this PR.

docs: Use correct command to activate Melos

---

packages/share_plus/share_plus_linux/lib/share_plus_linux.dart
packages/share_plus/share_plus_linux/pubspec.yaml
packages/share_plus/share_plus_windows/lib/share_plus_windows.dart
packages/share_plus/share_plus_windows/lib/src/version_helper.dart
packages/share_plus/share_plus_windows/pubspec.yaml

This pull-request fixes an issue where calling `Share.shareXFiles` caused stack-overflow due to an endless recursion cycle on:
- Windows 10 builds higher than 17763.
- Linux.
Now `shareXFiles` has been overrided in both `ShareLinux` & `ShareWindows` classes, to correctly throw `UnimplementedError` instead. More information may be located at: https://github.com/fluttercommunity/plus_plugins/issues/1180#issuecomment-1272842044.
**NOTE**: This fix should be released for both 4.x.x (currently on pub.dev) & 5.x.x (post #1158 _i.e._ next version).
This pull-request also resolves another issue for older Windows versions (builds lower than 17763), where Dart sided fallback implementation couldn't be registered correctly.
Closes #1180.
Does your PR require plugin users to manually update their …

fix(share_plus): Share.shareXFiles resulting in stack-overflow on Windows & Linux

---

.github/workflows/android_alarm_manager_plus.yaml

Introduced build matrix so tests run against multiple Android versions. It should help us to be sure that functionality of the plugin isn't broken by some change.
This PR has matrix only for Android alarm manager plus to get initial feedback. If other maintainers agree with suggested strategies in the next PR I will add similar changes for all plugins at once.
Initially I wanted to have 19 as a minimal version, but on 19 I saw such error:
So it seems that `integration_test` doesn't work well with old APIs.
Mid version corresponds to Android O, which is something in the middle of the suggested range.
Max version is 32 as 33 acted strange during my tests on fork.

ci(android_alarm_manager_plus): Add matrix of versions for integration tests

---

.github/workflows/all_plugins.yaml
.github/workflows/pr.yml

Enforces the use of Conventional Commits on all PRs.
This ensures that all work can be managed using `melos version`, as it requires following Conventional Commits strictly.
Also makes reading PR changes easier.
I used the example provided by https://github.com/marketplace/actions/semantic-pull-request to configure it.
None

ci(all): Enforce using Conventional Commit PR title

---

.github/workflows/all_plugins.yaml
.github/workflows/build_deploy_website.yaml

Saw warnings that some of our workflows use Node 12, which is deprecated since recently.
Addressing the issue. I haven't touched individual plugins workflows, because there are more PRs incoming to add build matrix with different Android versions usage for integration tests.
For future I would setup a Dependabot updates as it supports checking out new Actions versions as well.
-

ci: Update checkout actions

---

packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/example/lib/utils/file_picker_web.dart
packages/share_plus/share_plus/example/lib/utils/file_picker_win.dart
packages/share_plus/share_plus/example/macos/Runner/DebugProfile.entitlements
packages/share_plus/share_plus/example/macos/Runner/Release.entitlements
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus_macos/macos/Classes/SharePlusMacosPlugin.swift

In the MacOS implementation of share_plus show the `NSSharingServicePicker` asynchronously.
For testing purpose i've update the corresponding sample app :  
replace filepicker_windows with file_selector, for a working sample in all desktop (MacOS, Windows, Linux).
- Related #1177

fix(share_plus): Show NSSharingServicePicker asynchronously on main thread

---

docs/android_alarm_manager_plus/usage.mdx
packages/android_alarm_manager_plus/README.md
packages/android_alarm_manager_plus/example/lib/main.dart

Fix for a problem with `android_alarm_manager_plus` not working in release mode on Flutter 3.3.0 and newer.
It seems that due to recent changes to a tree-shaking quite a few plugins started to have issues with isolates when app is built in release mode.
The main requirement is to annotate the callback function with `@pragma('vm:entry-point')` in the app where the plugin is used. So I have updated the README and docs to mention this requirement.
Here is the list with similar issues or issues on topic:
https://github.com/flutter/flutter/issues/109248
https://github.com/firebase/flutterfire/issues/9446
https://www.reddit.com/r/flutterhelp/comments/x3tq8l/package_not_found_in_release_but_there_in_debug/
And this is the issue about missing documentation update about the change that broke …

docs(android_alarm_manager_plus): Fix example and docs to explain required annotation

---

packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfo.kt

As it turned out in Android 12 and newer `SSID` and `BSSID` are considered a location sensitive info, thus the new API to get WifiInfo via `getNetworkCapabilities()` returned all info except these 2 values. And it doesn't matter that app has required permissions. Explanation is provided in the official docs:
https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkCapabilities(android.net.Network)
The suggested way to register a callback with [required flag](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#FLAG_INCLUDE_LOCATION_INFO) seems not the best option for the `network_info_plus` as we want to get info on demand, not wait till something changes in network configuration. 
It seems we are not the only ones, who issue …

fix(network_info_plus): Get SSID on Android 12 and newer

---

.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

Updating workflows to run Android integration tests on different API levels for all plugins, like I recently did in #1184

ci(all): Add Android build matrix for all plugins

---

packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart

After adding an Android build matrix saw that [integration tests fail ](https://github.com/fluttercommunity/plus_plugins/actions/runs/3244740493/jobs/5321314320)for `device_info_plus` on newly added Andoid APIs. As it turned out there was a hardcoded version of Android (30), which caused test to fail on all other versions.
Also, saw that same test was missing check for a newly added device metrics data, so added it as well.

test(device_info_plus): Add Android display metrics check, fix Android version check

---

docs/device_info_plus/overview.mdx
docs/device_info_plus/usage.mdx
packages/device_info_plus/device_info_plus/README.md
packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart

Adding more info to some of `AndroidDeviceInfo` properties, so it is clear which properties might be null on some older platforms.
Saw that links to API documentation on the website and README redirected users just to pub.dev page of the `device_info_plus`, so updated the link. Also added the same link to the `Overview` page explaining to users that they can find the full list of properties there.

docs(device_info_plus): Add info about Android properties availability, update API docs links

---

docs/sensors_plus/overview.mdx
docs/sensors_plus/usage.mdx
packages/sensors_plus/sensors_plus/README.md

Saw that in our current version of website docs there were no info about magnetometer availability in `sensors_plus`. Fixing it. Did some minor corrections to both website docs and README.

docs(sensors_plus): Update website docs and README

---

packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
packages/device_info_plus/device_info_plus_platform_interface/lib/model/web_browser_info.dart
packages/device_info_plus/device_info_plus_platform_interface/test/method_channel_device_info_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_fake.dart
packages/device_info_plus/device_info_plus_platform_interface/test/model/android_device_info_test.dart

It seems that during migration to null safety all properties for Android platform were just marked as nullable, while in reality almost all properties are not nullable. Thus, we had issues like #706 with users not really understanding why something is nullable now.
I refactored the plugin interface to have only a few properties which really can be null declared as nullable, while the rest if non-nullable anymore.
#706 

refactor(device_info_plus)!: Change nullability for AndroidDeviceInfo properties

---

.github/dependabot.yml

Remove removed plugins
https://github.com/fluttercommunity/plus_plugins/network/updates

ci(all): Remove removed plugins from dependabot.yml

---

.github/dependabot.yml
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/share_plus/share_plus/example/android/build.gradle
packages/share_plus/share_plus/example/android/gradle/wrapper/gradle-wrapper.properties

We started to have a few requests to update Kotlin or Gradle in Android part of plugins. So I will do a series of PRs to resolve it. And for future adding a Dependabot config to do such updates automatically.
#1248 
#1222

chore(share_plus): Update Kotlin, Gradle and add Dependabot config

---

.github/dependabot.yml
packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/battery_plus/battery_plus/example/android/build.gradle

Same as #1261 - updating Kotlin, Gradle and adding a Dependabot config for Android dependencies.
This is the final one in the series of Kotlin/Gradle updates so far till I migrate rest of packages to Kotlin.
#1248 
#1222 

chore(battery_plus): Update Kotlin, Gradle and add Dependabot config

---

.github/dependabot.yml
packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
packages/network_info_plus/network_info_plus/example/android/build.gradle

Same as #1261 - updating Kotlin, Gradle and adding a Dependabot config for Android dependencies.
#1248 
#1222 

chore(network_info_plus): Update Kotlin, Gradle and add Dependabot config

---

packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_platform_interface/pubspec.yaml
packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/pubspec.yaml

Fixes the issue where the `dart_plugin_registrant.dart` file is not generated correctly.
Tested this locally with packages referenced by path. When I increased the Flutter SDK version to 2.11 then the issue we saw in #1270 was gone.
- Fix: https://github.com/fluttercommunity/plus_plugins/issues/1270
- Related: https://github.com/flutter/flutter/pull/96610
- Related: https://github.com/flutter/flutter/issues/113720
- Related: https://github.com/fluttercommunity/plus_plugins/issues/1274

fix(all): Increase min Flutter version to fix dartPluginClass registration

---

packages/connectivity_plus/connectivity_plus/lib/connectivity_plus.dart

This PR adds a missing export.
https://github.com/fluttercommunity/plus_plugins/pull/1227#discussion_r999845769

fix(connectivity_plus): Add connectivity_plus_web export

---

packages/device_info_plus/device_info_plus/README.md

Documents the deprecation of the `toMap` method, explaining that it is not JSON compatible and shouldn't be used as such.
- closes  #1291

docs(device_info_plus): Document toMap deprecation

---

packages/share_plus/share_plus/README.md

Document the use of temporary directories and why developers should care about it.
- closes #1299

docs(share_plus): #1299 document XFile.fromData

---

.github/workflows/connectivity_plus.yaml
.github/workflows/scripts/build-examples.sh
.github/workflows/scripts/integration-test.sh

The Linux build tests always failed because the `apt-get install` command errored.
This PR runs `apt-get update` before any `install`.
- [Failing test](https://github.com/fluttercommunity/plus_plugins/actions/runs/3351525648/jobs/5553032279)
- [Successful test](https://github.com/Coronon/plus_plugins/actions/runs/3351625509/jobs/5553203086)
No issue yet

fix(workflows): run apt-get update before install

---

packages/share_plus/share_plus/android/src/main/AndroidManifest.xml
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPlugin.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt
packages/share_plus/share_plus/android/src/main/res/xml/flutter_share_file_paths.xml

The `share_plus` android `shareWithResult` and `shareFilesWithResult` implementations are broken. The returned `ShareResult.raw` is always `null` on successful share. This PR fixes this by using `FLAG_MUTABLE` instead of `FLAG_IMMUTABLE`, as pointed out by @aakash-pamnani. This issue was not found when initially implementing the `shareWithResult` methods, as the `FLAG_IMMUTABLE` was only required by the highest API versions. Back then, a simple warning was emitted that strongly suggested using `FLAG_IMMUTABLE`, which seemed to break nothing.
This PR now fixes the behavior and ensures that the `FLAG_MUTABLE` `PendingIntent` given out may not be abused by moving from an implicit internal `Intent` to an explicit one. This also reduces mental complexity of the implementation.
I also added …

fix(share_plus): return correct share result on android

---

packages/share_plus/share_plus/lib/src/share_plus_linux.dart
packages/share_plus/share_plus/lib/src/share_plus_web.dart
packages/share_plus/share_plus/lib/src/share_plus_windows.dart
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus/test/share_plus_linux_test.dart
packages/share_plus/share_plus/test/share_plus_windows_test.dart

Remove direct dependence of url_launcher, instead depending on platform specific packages.
resolves #1070

feat(share_plus): remove direct dependence of url_launcher

---

packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart

Fixing integration tests which fail for `connectivity_plus` on Android 5 (API 21) since build matrix was introduced. 
Here is an example of such test: https://github.com/fluttercommunity/plus_plugins/actions/runs/3351644055/jobs/5553908690
As it turned out the reason for failing was the fact that Android 5 emulators have mobile internet turned on by default, not wifi. Here is how device config looks on a newly created emulator with Android 5:
I have added a check for Android version to check for correct connection type depending on Android version. I could add `device_info_plus` to get Android version, but felt like it is an overkill, so used slightly hacky way.

test(connectivity_plus): Fix integration test on Android 5

---

.github/workflows/build_preview_website.yaml

This PR introduces an additional condition for `build_preview_website` workflow which should allow us to see a preview of website changes done by Dependabot or somebody not from maintainers team (basically, from changes made in forks). The reason the preview deployment fails now for such PRs is that there is no access to repo secrets from forks. To keep things secure I followed one of suggested paths: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ and added a new label called `safe_deploy`. We, maintainers, can add it to the PR if we see that there no suspicious code changes introduced in some PR. Adding this label will trigger a preview build and deployment with access to required Github secrets of the repo, thus, completing successfully and providing us …

ci(website): Add condition to allow access to secrets for PRs from forks

---

packages/share_plus/share_plus/lib/src/share_plus_linux.dart
packages/share_plus/share_plus/lib/src/share_plus_web.dart
packages/share_plus/share_plus/lib/src/share_plus_windows.dart
packages/share_plus/share_plus/test/share_plus_linux_test.dart
packages/share_plus/share_plus/test/share_plus_windows_test.dart
packages/share_plus/share_plus/test/url_launcher_mock.dart

Reverting back to old construct as @stuartmorgan suggested https://github.com/fluttercommunity/plus_plugins/pull/1295#discussion_r1009240852
Also remove `canLaunch` check.

fix(share_plus): remove `canLaunch` check

---

packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/package_info_plus/test/package_info_test.dart

Overwrites for hashCode and equals for PackageInfo to get value equality, also adds verbose toString method to PackageInfo and adds tests for the changes
- *Fix #1321*
- [x ] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x ] I did not modify the `CHANGELOG.md` nor the `pubspec.yaml` files.
- [x ] All existing and new tests are passing.
- [x ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x ] No, this is *not* a breaking change.

fix(package_info_plus): adds value equality for PackageInfo

---

packages/share_plus/share_plus/example/lib/main.dart

The example uses `Platform` calls on Web which result in exceptions.
- Related #1320 

fix(share_plus): example broken on web

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_fake.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_test.dart

Add `serialNumber` property to `AndroidDeviceInfo` class
https://github.com/fluttercommunity/plus_plugins/issues/840

feat(device_info_plus): Add serialNumber property to AndroidDeviceInfo

---

.github/workflows/build_preview_website.yaml
website/docusaurus.config.js
website/package-lock.json
website/package.json

Was looking through logs of preview build and saw that there are some errors due to Docusaurus components having different versions:
This PR addresses these issues.
-

chore(deps): Update Docusaurus dependncies

---

docs/android_alarm_manager_plus/usage.mdx
docs/android_intent_plus/usage.mdx
docs/battery_plus/overview.mdx
docs/connectivity_plus/usage.mdx
docs/package_info_plus/usage.mdx
packages/android_alarm_manager_plus/README.md
packages/android_intent_plus/README.md
packages/battery_plus/battery_plus/README.md
packages/connectivity_plus/connectivity_plus/README.md
packages/device_info_plus/device_info_plus/README.md
packages/network_info_plus/network_info_plus/README.md
packages/package_info_plus/package_info_plus/README.md
packages/sensors_plus/sensors_plus/README.md
packages/share_plus/share_plus/README.md

Updating docs to cleanup them a little bit and add missing info on either website or in README files (for example, added info from #389 about package_info_plus).
Also, started to use fresh Github features for admonitions in README files for better visualisation:
Will do some more docs updates in further PRs.
Closes #389 

docs(all): Updates for READMEs and website pages

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template is changed, so that the Contributor Guide can be clicked. It helps people to actually open and read it.

chore(all): Add link to Contributor Guide to PR template

---

packages/package_info_plus/package_info_plus/README.md

Table wasn't rendered properly, since the row with line separators were on the same line as the row of titles.

docs: Fixed markdown table formatting in README

---

packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart

Fixes the code formatting issue in #1479:
```
These files are not formatted correctly:
-----------------------------------------------------------------
packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart
-----------------------------------------------------------------
diff --git a/packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart b/packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart
index efa5d105..f0b62868 100644
--- a/packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart
+++ b/packages/package_info_plus/package_info_plus/test/package_info_plus_web_test.mocks.dart
@@ -27,2 +27,2 @@ class _FakeResponse_0 extends _i1.Fake implements _i2.Response …
```

chore(package_info_plus): fix mock formatting

---

packages/battery_plus/battery_plus/lib/src/battery_plus_linux.dart
packages/battery_plus/battery_plus/test/battery_plus_linux_test.dart

Use a broadcast stream to allow multiple listeners.
> A single-subscription stream allows only a single listener during the whole lifetime of the stream.
...
> Listening twice on a single-subscription stream is not allowed, even after the first subscription has been canceled.
https://api.dart.dev/stable/2.19.0/dart-async/Stream-class.html
Fixes: #1478

fix(battery_plus_linux): broadcast stream

---

packages/package_info_plus/package_info_plus/lib/src/file_version_info.dart

Struct fields should not be nullable, removing nullability modifier.
* https://github.com/fluttercommunity/plus_plugins/issues/1525

refactor: Remove nullable struct fields

---

packages/connectivity_plus/connectivity_plus/README.md

*This PR is for updating the document for missing network interface enums*

docs(connectivity_plus): Documentation added for the missing network interface enums

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/build.gradle
packages/android_alarm_manager_plus/example/android/gradle/wrapper/gradle-wrapper.properties

bump gradle version to 7.3.1, kotlin version to 1.7.22, and gradle-wrapper's gradle version to 7.5.1

chore(android_alarm_manager_plus): bump gradle and kotlin version

---

packages/android_alarm_manager_plus/LICENSE
packages/android_intent_plus/LICENSE
packages/battery_plus/battery_plus/LICENSE
packages/battery_plus/battery_plus_platform_interface/LICENSE
packages/connectivity_plus/connectivity_plus/LICENSE
packages/connectivity_plus/connectivity_plus_platform_interface/LICENSE
packages/device_info_plus/device_info_plus/LICENSE
packages/device_info_plus/device_info_plus_platform_interface/LICENSE
packages/network_info_plus/network_info_plus/LICENSE
packages/network_info_plus/network_info_plus_platform_interface/LICENSE
packages/package_info_plus/package_info_plus/LICENSE
packages/package_info_plus/package_info_plus_platform_interface/LICENSE
packages/sensors_plus/sensors_plus/LICENSE
packages/sensors_plus/sensors_plus_platform_interface/LICENSE
packages/share_plus/share_plus/LICENSE
packages/share_plus/share_plus_platform_interface/LICENSE

The LICENSE files should not contain "//" prefixes. It might be convenient for directly copying and pasting the license headers to source files but such formatting is not compatible with Flutter's [license registry](https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html).
| Before | After |
|---|---|
| <img width="912" alt="Screenshot 2023-03-04 at 07 26 06" src="https://user-images.githubusercontent.com/140617/222879952-4e005e9c-06f1-4bf1-a702-ad8afe649341.png"> | <img width="912" alt="Screenshot 2023-03-04 at 07 26 57" src="https://user-images.githubusercontent.com/140617/222879956-2e52e70e-bf70-4a77-a6cc-6b3d149350ff.png"> |
https://api.flutter.dev/flutter/material/showLicensePage.html
Consider this a preparation step for fixing #1058 which requires adding libnatpmp …

style(all): Clean up LICENSE files formatting

---

.github/dependabot.yml

I see that for some reason Dependabot ignores some of packages we have in this repo, so, for example, `share_plus` uses not the most up-to-date dependencies. After some research I found out that it might be a bug in Dependabot: https://github.com/dependabot/dependabot-core/issues/2574
As suggested in that issue any commit to yaml config will make Dependabot re-evaluate it and, hopefully, will resume PRs creation. So trying my luck here.
In case Dependabot continues ignoring packages I would try to swap it to https://github.com/renovatebot/renovate as an experiment.

chore(all): Refresh Dependabot config

---

.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/share_plus.yaml

After some research found out that MacOS integration tests were failing due to this issue https://github.com/flutter/flutter/issues/118469
Older Flutter version is suggested as a solution for this problem. I have tested the change in https://github.com/fluttercommunity/plus_plugins/pull/1596 and saw that it works. Thus, updated all workflows to use older Flutter version and explanation comment on why fixed version is used.
Fixes https://github.com/fluttercommunity/plus_plugins/issues/1591

test(all): Fix macos integration tests for all packages

---

packages/package_info_plus/package_info_plus/lib/package_info_plus.dart

Making this a required argument unnecessarily broke all calls to setMockInitialValues. This undoes that change but is not itself a breaking change.
Make installerStore an optional argument in setMockInitialValues.

fix(package_info_plus): Make installerStore an optional argument in mocks

---

.github/dependabot.yml

This PR changes the [versioning strategy](https://stackoverflow.com/a/66819358) for npm dependabot updates.
We had a couple of [dependabot alerts](https://github.com/fluttercommunity/plus_plugins/security/dependabot?q=is%3Aclosed), that were not updated via dependabot.
Maybe the issue of this [PR](https://github.com/fluttercommunity/plus_plugins/pull/1544) not able to rebase could also be solved.

chore(website): Improve dependabot for npm packages

---

.github/workflows/scripts/install-tools.sh

CI workflow was activating latest version of Melos, so in #1614 and #1613 checks were already running with Melos 3.0.0, which was released just recently. Initially I wanted to follow the migration guide, but saw in changelogs that version 3.0.0 requires 2.18 as min Dart SDK: https://github.com/invertase/melos/blob/main/CHANGELOG.md#melos---v300
I wouldn't like us to bump plugins min Dart version for now, so modified the script to use 2.9.0 as it was used before.

ci(all): Fix Melos version on 2.9.0

---

packages/package_info_plus/package_info_plus/example/lib/main.dart
packages/share_plus/share_plus/example/lib/main.dart

While testing some changes for package_info_plus saw that example app has non-scrollable content, so in landscape mode there is an overflow (see attached screenshot). This PR fixes it along with switching example app to usage of Material 3. Used the same color seed as in `share_plus`. The only addition is an elevation to AppBar, so it is not white by default. Did the same adjustment to `share_plus` for consistency.
Before:
After:

fix(package_info_plus): Make example app content scrollable

---

packages/package_info_plus/package_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/packageinfo/PackageInfoPlugin.kt

Added calls to a newer API that is suggested since Android 11 to get information about package that installed the app.
Closes #1598 

feat(package_info_plus): Use new API to get install source on Android >= 11

---

packages/share_plus/share_plus/android/src/main/AndroidManifest.xml

Addressing an issue reported in #1608. After looking at the documentation and code saw that we indeed don't need to have receiver exposed as only catch the intent that we launch from the app that uses `share_plus`
Docs on topic: 
- https://developer.android.com/guide/topics/manifest/receiver-element
- https://developer.android.com/training/permissions/restrict-interactions#broadcast-receivers
Tested the change - no issues with getting result of share in example app.
Closes #1608

fix(share_plus): Set exported=false for BroadcastReceiver on Android

---

docs/sensors_plus/usage.mdx
packages/sensors_plus/sensors_plus/example/lib/main.dart

I believe the description of the accelerometer in docs/sensors_plus/usage.mdx is not accurate.
I changed the description of AccelerometerEvent and UserAccelerometerEvent. See https://en.wikipedia.org/wiki/Accelerometer
The text is now rather long; I was unable to compress the information I find relevant in a shorter text.
I changed the order of the topics because I feel the presentation is more clear if we explain first the concept of acceleration in itself, and only after that we explain that the gravity is indistinguishable from an accelerated movement. I also changed the order in packages/sensors_plus/sensors_plus/example/lib/main.dart (perhaps this wasn't necessary).
I wonder if the descriptions of GyroscopeEvent and MagnetometerEvent are accurate and complete. I think at least the …

docs(sensor_plus): improve description of accelerometer

---

packages/android_alarm_manager_plus/example/pubspec.yaml
packages/android_intent_plus/example/pubspec.yaml
packages/battery_plus/battery_plus/example/pubspec.yaml
packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/example/pubspec.yaml
packages/network_info_plus/network_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/example/pubspec.yaml

Manual dependency_overrides in the examples shouldn't be needed since Melos already should handle those.

refactor(all): Remove all manual dependency_overrides

---

packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt

Without this change I see the following errors with strict compilation flags:
```
Error: 'types' is captured by a lambda expression that is passed as immutable type(s) String but is of type List which is mutable [Immutable]
if (types.size == 1) {
~~~~~
Error: 'reducedMimeType' is captured by a lambda expression that is passed as immutable type(s) String but is not final [Immutable]
reducedMimeType = types.first()
~~~~~~~~~~~~~~~
```

fix(share_plus_android): Fix strict compilation errors in MIME reduction function

---

packages/android_alarm_manager_plus/example/android/app/build.gradle

location: packages\android_alarm_manager_plus\example\android\app\build.gradle
compileSdkVersion changed to 33 from 31 because its showing an error in Debug Console 
error: 
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\Users\HP\Desktop\codes\plus_plugins\packages\android_alarm_manager_plus\example\android\app\build.gradle:
android {
compileSdkVersion 33
...
}

build(android_alarm_manager_plus): Bump example app compileSDK to 33

---

packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt
packages/battery_plus/battery_plus/example/android/build.gradle

Replacement PR for #1629 to get the fix merged faster.
Additionally did a minor code cleanup
Found this Stack Overflow answer related to Huawei: https://stackoverflow.com/questions/45743484/ispowersavemode-always-returns-false-for-huawei-devices/65682806#65682806

fix(battery_plus): Huawei power save mode check

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/app/build.gradle
packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/app/build.gradle
packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/android/build.gradle
packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle

Reverting `namespace` addition to release a fix for those who use old AGP versions.
Closes #1722 
Closes #1724 

fix(all): Revert addition of namespace to avoid build fails on old AGPs

---

docs/package_info_plus/usage.mdx
packages/package_info_plus/package_info_plus/lib/package_info_plus.dart

Added an explanation on why `buildNumber` sometimes returns the same value as `version` property.
Closes #1644 

docs(package_info_plus): Explain why buildNumber returns version when no build number defined

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/app/build.gradle
packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/app/build.gradle
packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/android/build.gradle
packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle

Bringing back `namespace` property as a breaking change now.
Additionally explicitly specified `compileOptions`.
Closes #1721 

fix(all)!: Add support of namespace property to support AGP 8

---

packages/device_info_plus/device_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/device_info_plus/device_info_plus/example/ios/Runner/Info.plist
packages/device_info_plus/device_info_plus/lib/src/model/ios_device_info.dart

One more refactor similar to #1246, but this time for iOS.
According to https://developer.apple.com/documentation/uikit/uidevice and https://pubs.opengroup.org/onlinepubs/7908799/xsh/sysutsname.h.html almost all properties that we return with the plugin are not nullable. So this PR updates nullability of properties to match the iOS specs.
Closes #1670

refactor(device_info_plus): Declare proper nullability for iOS properties

---

packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_web_test.dart
packages/package_info_plus/package_info_plus/lib/src/file_version_info.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_windows.dart
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/test/package_info_plus_linux_test.dart
packages/package_info_plus/package_info_plus/test/package_info_plus_windows_test.dart

- Use Win32 `GetUserDefaultLangID` rather than redefining
- Use Win32 `typedef`s for Windows types
- Remove unnecessary nullability in `_FileVersionInfoData`
- Reduced wide dependency on Win32
- Upgraded minimum Dart version to match language features already used
- Add some tests
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*
*e.g.*
- *Fix #123*
- *Related #456*

refactor(package_info_plus): Tidy up Windows implementation

---

packages/android_alarm_manager_plus/example/lib/main.dart
packages/android_alarm_manager_plus/example/pubspec.yaml
packages/android_alarm_manager_plus/pubspec.yaml

chore(android_alarm_manager_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/app/build.gradle
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/example/pubspec.yaml
packages/android_intent_plus/pubspec.yaml

chore(android_intent_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/network_info_plus/network_info_plus/example/integration_test/network_info_plus_test.dart
packages/network_info_plus/network_info_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/network_info_plus/network_info_plus/example/ios/Flutter/Flutter.podspec
packages/network_info_plus/network_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/network_info_plus/network_info_plus/example/ios/Runner/Info.plist
packages/network_info_plus/network_info_plus/example/lib/main.dart
packages/network_info_plus/network_info_plus/example/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml

chore(network_info_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/pubspec.yaml

Updating used dependencies and aligning constraint with other plugins maintained by the Flutter team (for example, here: https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher/pubspec.yaml#L8). Not marking as a breaking change as we already have `namespace` marked as breaking change.

chore(share_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_platform_interface/pubspec.yaml

chore(package_info_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml

chore(sensors_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml

chore(device_info_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/example/lib/main.dart
packages/connectivity_plus/connectivity_plus/lib/src/connectivity_plus_web.dart
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_platform_interface/pubspec.yaml

chore(connectivity_plus): Update Flutter dependencies, set Flutter >=3.3.0 and Dart to >=2.18.0 <4.0.0

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt

There's already a check for PRODUCT contains "sdk", so there's no need to test various combinations of this. Perhaps it's also worth using case-insensitive tests and, for example, simply checking if MODEL then contains "sdk"?
There's already a check for PRODUCT contains "sdk", so there's no need to test various combinations of this. Also, added parenthesis around the initial conjunction for better readability (in terms of precedence).
Perhaps it's also worth using case-insensitive tests and, for example, simply checking if MODEL then contains "sdk"?
This is a bit of a micro-optimization, but I've noticed this code is [referenced on Stack Overflow, etc.,](https://stackoverflow.com/a/55355049/2872279) and this could potentially be simplified further. It should also stop additional checks …

chore(device_info_plus): Remove redundant checks for PRODUCT strings with sdk

---

packages/sensors_plus/sensors_plus/android/build.gradle
packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/sensors_plus/sensors_plus/example/ios/Flutter/Flutter.podspec
packages/sensors_plus/sensors_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/sensors_plus/sensors_plus/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/sensors_plus/sensors_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/sensors_plus/sensors_plus/example/ios/Runner/Info.plist
packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec

Additionally saw that podspec file still had old info about maintainers, docs url, etc., so fixed it.
#1665 

chore(sensors_plus)!: Bump min Android and iOS versions, update podspec file

---

packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/share_plus/share_plus/example/ios/Runner/Info.plist
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/ios/share_plus.podspec

Additionally saw that podspec file still had old info about maintainers, docs url, etc., so fixed it.
#1665 

chore(share_plus)!: Bump min Android and iOS versions, update podspec file

---

packages/battery_plus/battery_plus/lib/src/battery_plus_linux.dart
packages/battery_plus/battery_plus/lib/src/battery_plus_web.dart

Addressing the issue reported in `Score` section on pub.dev https://pub.dev/packages/battery_plus/score about Sink not being closed on Web and Linux.

fix(battery_plus): Close StreamController on Web and Linux when done

---

packages/package_info_plus/package_info_plus/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/package_info_plus/package_info_plus/example/ios/Flutter/Flutter.podspec
packages/package_info_plus/package_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/package_info_plus/package_info_plus/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/package_info_plus/package_info_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/package_info_plus/package_info_plus/example/ios/Runner/Info.plist
packages/package_info_plus/package_info_plus/ios/package_info_plus.podspec

Additionally saw that podspec file still had old info about maintainers, docs url, etc., so fixed it.
#1665

chore(package_info_plus)!: Bump min Android and iOS versions, update podspec file

---

packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/ios/network_info_plus.podspec

Additionally saw that podspec file still had old info about maintainers, so fixed it.
#1665

chore(network_info_plus)!: Bump min Android and iOS versions, update podspec file

---

packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec

Additionally saw that podspec file still had old info about maintainers, docs url, etc., so fixed it.
#1665

chore(connectivity_plus)!: Bump min Android and iOS versions, update podspec file

---

packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/app/build.gradle

chore(android_intent_plus)!: Bump min Android version

---

packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/ios/device_info_plus.podspec
packages/network_info_plus/network_info_plus/ios/network_info_plus.podspec
packages/package_info_plus/package_info_plus/ios/package_info_plus.podspec
packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec
packages/share_plus/share_plus/ios/share_plus.podspec

Additionally saw that podspec file still had old info about maintainers, so fixed it.
#1665

chore(device_info_plus)!: Bump min Android and iOS versions, update podspec file

---

.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart

Fixing workflows as due to changes introduced in #1628 it is required to run `melos bootstrap` in integration tests for release PRs to resolve versions properly.
We had the problem of failing checks in https://github.com/fluttercommunity/plus_plugins/pull/1674 and in https://github.com/fluttercommunity/plus_plugins/pull/1718 due to missing bootstrapping.
Also, switched to `macos-13` runners as they help to avoid issues like https://github.com/flutter/flutter/issues/118469 as we had earlier this year.

ci(all): Bootstrap for integration tests, update runners

---

.github/workflows/all_plugins.yaml

`flutter format` was deprecated in favor of `dart format`.
https://github.com/fluttercommunity/plus_plugins/actions/runs/4940139249/jobs/8831507992

ci: Replace deprecated flutter command

---

packages/android_alarm_manager_plus/test/android_alarm_manager_test.dart
packages/battery_plus/battery_plus/lib/src/battery_plus_web.dart
packages/battery_plus/battery_plus_platform_interface/test/battery_plus_platform_interface_test.dart
packages/connectivity_plus/connectivity_plus/example/integration_test/connectivity_plus_test.dart
packages/connectivity_plus/connectivity_plus_platform_interface/test/method_channel_connectivity_test.dart
packages/device_info_plus/device_info_plus_platform_interface/test/method_channel_device_info_test.dart
packages/network_info_plus/network_info_plus_platform_interface/test/method_channel_network_info_test.dart
packages/package_info_plus/package_info_plus/test/package_info_test.dart
packages/package_info_plus/package_info_plus_platform_interface/test/method_channel_package_info_test.dart
packages/sensors_plus/sensors_plus/example/integration_test/sensors_plus_test.dart
packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
packages/sensors_plus/sensors_plus/test/sensors_test.dart
packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart
packages/share_plus/share_plus/example/android/build.gradle
packages/share_plus/share_plus/example/integration_test/share_plus_test.dart

Resolving all analyzer warnings from Flutter 3.10.0 reported in tests.
Here is one of jobs with such warnings: https://github.com/fluttercommunity/plus_plugins/actions/runs/4956135708/jobs/8866237373

test(all): Fix Flutter 3.10 deprecations in tests

---

packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt
packages/battery_plus/battery_plus/example/android/build.gradle

Most of the context is in the bug but short summary is that broadcast receivers will require and export state if apps are targeting android api 34. Unfortunately I cant find a public document or post saying this but I see this on internal facing documents. 
There is an internal to google team using battery_plus who wishes to target api 34 and they reached out to me as the TL of flutter on android to help get their dependencies updated. You can see a similar issues and a pull request to fix our own url_launcher plugin below. 
I think the other examples of registerReceiver are ok because they are protected by a version check and not called on api 34. If that is incorrect I can fix those in a different pr. 
https://github.com/fluttercommunity/plus_plugins/issues/1810 …

fix(battery_plus): Use context compat to set exported state

---

docs/sensors_plus/usage.mdx
packages/sensors_plus/sensors_plus/README.md

As after #1405 `sensors_plus` returns error in case some sensor is not available. This PR adds info about such error into README and website docs.
Additionally unified plugin events description between README and website.

docs(sensor_plus): Add info about possible error cases

---

packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/example/macos/Runner.xcodeproj/project.pbxproj
packages/device_info_plus/device_info_plus/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/device_info_plus/device_info_plus/example/pubspec.yaml

Small cleanup for example app in `device_info_plus` for better readability. Bumped Dart to 3 in example, but it shouldn't affect users of the plugin with older Dart version.

chore(device_info_plus): Refactor example app

---

packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart
packages/device_info_plus/device_info_plus/lib/src/model/ios_device_info.dart

Added link to documentation of properties returned for Android and iOS to make it more visible to users which field means what. Decided to do so after #1847 where user confused `id` field with `Android id`. API doc for that field was also not very clear: https://pub.dev/documentation/device_info_plus/latest/device_info_plus/AndroidDeviceInfo/id.html

docs(device_info_plus): Add links to Android and iOS docs to every field

---

packages/sensors_plus/sensors_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/sensors_plus/sensors_plus/ios/Classes/FLTSensorsPlusPlugin.m

Potential fix for #1733. In any case it seems wrong that the same key was used for different sensors. I assume it was a typo from copy-paste actions during one of PRs.
#1733

fix(sensors_plus): Fix issues with emitting multiple sensors events on iOS

---

packages/android_alarm_manager_plus/pubspec.yaml
packages/android_intent_plus/pubspec.yaml
packages/battery_plus/battery_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml

Due to wrong links under `repository` tag in `pubspec.yaml` of every single package we have an issue where on pub.dev clicking on `example/lib/main.dart` link ([here it is](https://pub.dev/packages/android_intent_plus/example) at the top of the page), which is generated by pub.dev itself, users were redirected to 404 page.
Found a solution here: https://github.com/dart-lang/pub-dev/issues/3288
Closes #1861 

docs(all): Fix example links on pub.dev

---

packages/sensors_plus/sensors_plus/ios/Classes/FLTSensorsPlusPlugin.m

fixed the deprecated syntax.
- *Fix #1903*

fix(sensors_plus): fixed the deprecated syntax.

---

docs/share_plus/usage.mdx
packages/share_plus/share_plus/README.md

- Removed deprecated method `shareFiles` usage from the document.
- fixes #1906 

docs(share_plus): Updated document with latest available method

---

packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/package_info_plus/test/package_info_test.dart

This PR adds a `toMap()` function to the `PackageInfo` class in the `package_info_plus` plugin. Previously, this functionality was missing. The `toMap()` function returns a map representation of the `PackageInfo` instance. Notably, the `buildSignature` and `installerStore` fields are included in the map only if they are non-null and non-empty. This change ensures that the returned map only contains meaningful and useful data.

feat(package_info_plus): Added toMap method

---

.gitignore
pubspec.yaml

- Add `flutter_lints` to `pubspec.yaml` to get rid of a lint:
- Remove `pubspec_overrides.yaml` from `.gitignore`, which was added in https://github.com/fluttercommunity/plus_plugins/pull/1619
- Remove exemption that keeps `pubspec.lock`, which was introduced in https://github.com/fluttercommunity/plus_plugins/pull/1686, but the `pubspec.lock` was deleted in https://github.com/fluttercommunity/plus_plugins/pull/1772 with the reason https://dart.dev/guides/libraries/private-files#pubspeclock (at the moment, calling pub get in the root folder adds the lockfile newly to git - so either add it, or remove the exemption):

chore(all): Fix lint, cleanup .gitignore

---

packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/ios/Classes/FLTSharePlusPlugin.m
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart

Allow user to share URI with preview image on the iOS native share sheet. The image is fetched from the iOS native side rather than on the flutter side.
None

feat(share_plus): Allow user to share URI with preview image on the iOS native share sheet

---

packages/connectivity_plus/connectivity_plus/pubspec.yaml

Made the plugin use older `js` version as there were issues with compatibility for older Flutter versions as reported in #1960
Fixes #1960

fix(connectivity_plus): Downgrade js version to work with Flutter 3.3.10

---

packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_web_test.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart

Changes the regex that matches the URL for the version.json path generation.
The previous regex did not correctly recognize non-word characters in URLs and created a wrong version.json path.
- *Fix #1891*

fix(package_info_plus): proper version.json url for files with special characters

---

docs/package_info_plus/usage.mdx
packages/package_info_plus/package_info_plus/README.md

Added explanation on why sometimes users might get wrong version from the `package_info_plus` plugins on Windows. More info available in #343.
Closes #343

docs(package_info_plus): Add explanation for known issue on Windows

---

packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec

~~Found out that some plugins have explicit exception to only allow x86_64 arches which didn't allow to run builds on ARM Macs natively.
Note, I currently don't have any ARM Mac to validate that this doesn't break anything, so would appreciate checking out if iOS builds correctly after this change.~~
Removed deprecated iOS build config property.
#1467

feat(connectivity_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/device_info_plus/device_info_plus/ios/device_info_plus.podspec

~~Found out that some plugins have explicit exception to only allow x86_64 arches which didn't allow to run builds on ARM Macs natively.
Note, I currently don't have any ARM Mac to validate that this doesn't break anything, so would appreciate checking out if iOS builds correctly after this change.~~
Removed deprecated properties.
#1467

feat(device_info_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/package_info_plus/package_info_plus/ios/package_info_plus.podspec

feat(package_info_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/share_plus/share_plus/ios/share_plus.podspec

feat(share_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/battery_plus/battery_plus/ios/battery_plus.podspec

feat(battery_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/network_info_plus/network_info_plus/ios/network_info_plus.podspec

feat(network_info_arm): Remove deprecated VALID_ARCHS iOS property

---

packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec

Same as rest of ARM related PRs today
#1467 

feat(sensors_plus): Remove deprecated VALID_ARCHS iOS property

---

packages/device_info_plus/device_info_plus/lib/device_info_plus.dart

According to #1651 `device_info_plus` might cause some analyzer issues to other packages which use the plugin. After looking at code it looks like we already had a conditional export for windows part, so this PR adds the same condition to linux part to be sure that there are no unsupported libraries used for web (at least from package analyzer point of view). 
Fixes #1651 

fix(device_info_plus): Update exports to avoid web compatibility issues

---

.github/dependabot.yml

As partly discussed in [this PR](https://github.com/fluttercommunity/plus_plugins/pull/1989#issuecomment-1655610449).
Our dependabot update policy continuously tightens the constraints, updating every single patch release - making the latest versions of plus_plugins less compatible with the rest of the ecosystem.
I'll just open this PR and leave it to discussion whether any included changes make sense for `plug_plugins`.
Following the changes plus my understanding of the benefit:
1. Ignore dependabot pub updates for minor and patch releases:
If a plugin declares a dependency x of `1.0.0`, it's potentially compatible with version `1.0.0` up to `<2.0.0` and apps using the same dependency itself, or other packages using it (within the range `>=1.0.0 <2.0.0`). Updating to i.e. `1.2.4` …

chore(all): Adjust dependabot settings

---

.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

I missed the fact that Java version is set in 2 places in workflow files and didn't update Java for integration tests in #2055
Additionally I looked at a few other repos that use Android emulators Action that we use and found out that a few of such repos identify 21 and 32 as flaky emulators, which is something we often experience ourselves. As a result I changed min Android API to 22 and max to 31 in attempt to get lower number of failed CI tests due to flakiness of some emulators.

ci(all): Update Java version for integration tests, update Android APIs

---

.github/workflows/android_intent_plus.yaml

According to Github documentation `macos-13` machine should already have Java 17 installed: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#java
Thus, I am curious if we can drop installation step in order to save a few seconds during workflow runs. In case this PR doesn't fail I will open similar ones for other plugins workflows.

ci(android_intent_plus): Remove Java installation step

---

docs/share_plus/usage.mdx
packages/share_plus/share_plus/README.md

Saw that usage examples have invalid code snippets, so this PR fixes found issues both in README and on plugins website.

docs(share_plus): Fix usage code snippets

---

.github/workflows/android_alarm_manager_plus.yaml

The integration test for the lower Android API level fails since it was recently changed from 21 to 22.
The test already failed in the [PR](https://github.com/fluttercommunity/plus_plugins/pull/2057) changing the version, and since then in [all](https://github.com/fluttercommunity/plus_plugins/actions/workflows/android_alarm_manager_plus.yaml) workflow runs using the new API level. In a current PR, the test failed [seven](https://github.com/fluttercommunity/plus_plugins/actions/runs/6020568481/job/16339956921?pr=2112) times in a row. Unless we find the actual cause, it makes sense to revert the API level change.
This PR changes the version to the one that worked fine before.
In the future, I would suggest only merging PRs with successful tests (if they worked before), so we limit …

fix(android_alarm_manager_plus): Fix integration test

---

packages/android_alarm_manager_plus/android/build.gradle

Similar to https://github.com/fluttercommunity/plus_plugins/pull/2109.
https://github.com/fluttercommunity/plus_plugins/issues/2091.

chore(android_alarm_manger_plus): Change group name

---

packages/android_intent_plus/android/build.gradle

Similar to https://github.com/fluttercommunity/plus_plugins/pull/2109.
https://github.com/fluttercommunity/plus_plugins/issues/2091.

chore(android_intent_plus): Update group name

---

packages/package_info_plus/package_info_plus/android/build.gradle

Similar to https://github.com/fluttercommunity/plus_plugins/pull/2109.
https://github.com/fluttercommunity/plus_plugins/issues/2091.

chore(package_info_plus): Change group name

---

packages/sensors_plus/sensors_plus/android/build.gradle

Closes https://github.com/fluttercommunity/plus_plugins/issues/2091.

chore(sensors_plus): Update group name

---

packages/connectivity_plus/connectivity_plus/android/build.gradle

Similar to https://github.com/fluttercommunity/plus_plugins/pull/2109.
https://github.com/fluttercommunity/plus_plugins/issues/2091.

chore(connectivity_plus): Change group name

---

packages/connectivity_plus/connectivity_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/connectivity_plus/connectivity_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec

We have multiple bug reports about issues when `connectivity_plus` plugin is used in a project build with Xcode 15. Apparently, after some investigation found out that Xcode 15 supports [only iOS 12 and newer](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Overview) and not all APIs work fine.
Here is an example of similar solution: https://stackoverflow.com/a/77151438/7339798
In order to support Xcode 15 I am bumping min iOS version for the plugin to 12, so users won't have to modify their build configs on iOS. 
Marking as a breaking change to be sure I don't break projects for somebody who still supports <12 iOS versions.
Supposed to close quite a lot of issues:
Fixes #1955
Fixes #2136
Fixes #2154
Fixes #2155
Fixes #2159
Fixes #2162 
Fixes #2166 …

fix(connectivity_plus)!: Bump min iOS to 12 to support XCode 15

---

.github/dependabot.yml

When Dependabot opens a bunch of PRs it becomes a nightmare to merge them all as every merge causes all other PRs to rebase. It wastes a lot of time and energy for no reason as in most cases these Dependabot PRs are not related. Thus, I am disabling the default behavior of Dependabot to be more energy efficient and save our (maintainers) time as well.
Hope to not see such situation again:

ci(all): Disable automatic rebase for Dependabot PRs

---

packages/battery_plus/battery_plus/example/android/app/build.gradle

Bumping compileSDK to 34 to merge #2175 and be on par with latest Android version.
-

chore(battery_plus): Update compileSDK for example app to 34

---

packages/network_info_plus/network_info_plus/example/android/app/build.gradle

chore(network_info_plus): Update compileSDK to 34 for example

---

packages/android_alarm_manager_plus/example/android/app/build.gradle

chore(android_alarm_manager_plus): Update compileSDK to 34 for example

---

packages/device_info_plus/device_info_plus/example/android/app/build.gradle

chore(device_info_plus): Update compileSDK to 34 for example

---

CONTRIBUTING.md
melos.yaml

Since the end-to-end tests migration from Flutter driver to integration tests, the documentation and local melos commands were not updated accordingly.
- *Related #2217*

chore: Update docs and commands for e2e tests

---

packages/device_info_plus/device_info_plus/example/macos/Runner.xcodeproj/project.pbxproj
packages/device_info_plus/device_info_plus/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/device_info_plus/device_info_plus/lib/src/model/macos_device_info.dart
packages/device_info_plus/device_info_plus/macos/Classes/CwlSysctl.swift

Added an explanation that for apps running via Rosetta `arch` parameter` can be `x86_64` to avoid confusion like happened in #2213. Additionally removed a few conditions to check iOS properties as code from `macos` folder won't even run for iOS target.
#2213 

docs(device_info_plus): Add note about arch returned value on MacOS

---

.github/ISSUE_TEMPLATE/BUG.yaml
.github/ISSUE_TEMPLATE/QUESTION.yaml

Additional checkbox about searching through Github Issues in this repository first. I don't have high hopes for this change, but maybe it would improve situation a bit.

chore(github): Update templates to mention checkbox about searching through repository issues

---

packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/example/android/build.gradle

Same as #2229 and #2228 
Note, I am also setting compile options to compile against Java 8 to have less user reports. Will bump to Java 17 in a few months after its higher adoption.

fix(device_info_plus): Revert bump compileSDK to 34

---

packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/example/android/app/build.gradle

Reverting bump to compileSDK 34 as it introduces issues for projects not compiling against SDK 34 (Android 14). Will do this bump later as otherwise we will have tons of issues.

fix(battery_plus): Revert bump of compileSDK to 34

---

packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/example/android/build.gradle

fix(network_info_plus): Revert bump compileSDK to 34

---

packages/package_info_plus/package_info_plus/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/example/android/build.gradle

fix(package_info_plus): Revert bump compileSDK to 34

---

packages/sensors_plus/sensors_plus/android/build.gradle
packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/example/android/build.gradle

fix(sensors_plus): Revert bump compileSDK to 34

---

packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/build.gradle

fix(connectivity_plus): Revert bump compileSDK to 34

---

packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle

fix(share_plus): Revert bump to compileSDK 34

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/app/build.gradle
packages/android_alarm_manager_plus/example/android/build.gradle

fix(alarm_manager_plus): Revert bump compileSDK 34

---

packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/example/android/app/build.gradle
packages/android_intent_plus/example/android/build.gradle

fix(android_intent_plus): Revert bump compileSDK to 34

---

packages/android_intent_plus/android/build.gradle

With `compileOnly` I had the following issue while trying to add `android_intent_plus` to a new empty project:
With `implementation` didn't see such issue, thus, changing declaration.

fix(android_intent_plus): Fix annotation dependency declaration

---

packages/connectivity_plus/connectivity_plus/CHANGELOG.md

During changelog generation there was a mistake about requirement of Kotlin while connectivity_plus doesn't need it.
Same applies to `android_alarm_manager_plus` and `android_intent_plus`, but I will open separate PRs for it.

fix(connectivity_plus): Fix CHANGELOG to not mention Kotlin requirement

---

packages/share_plus/share_plus/android/build.gradle

Kotlin update to 1.9.10 was too fast as it brought some problems, like https://github.com/fluttercommunity/plus_plugins/pull/2134 and #2251
Due to #2134 I decided to make major release, but it was a mistake as there were more hidden problems from this Kotlin version, like requirement of Android Gradle Plugin 8.x for projects that use the plugin with this Kotlin version. And while I am a fan of using latest dependency versions in projects this is too much.
Thus, I retracted new breaking changes versions and will open a series of PRs downgrading Kotlin to release another update tomorrow.
Also, validated that downgrading Kotlin resolves the problem I reported in #2251 as that projects builds fine when `share_plus` is used from this branch.
Fixes #2251 
Does your PR require plugin users to …

fix(share_plus): Change Kotlin version from 1.9.10 to 1.7.22

---

packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/build.gradle

fix(network_info_plus): Change Kotlin version from 1.9.10 to 1.7.22

---

packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/build.gradle

fix(device_info_plus): Change Kotlin version from 1.9.10 to 1.7.22

---

packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart

[pub points](https://pub.dev/packages/sensors_plus/score) is reduced.
```
40/50 points: code has no errors, warnings, lints, or formatting issues
Found 3 issues. Showing the first 2:
INFO: Unclosed instance of 'Sink'.
INFO: Unclosed instance of 'Sink'.
```
N/A

fix(sensors_plus): Close stream controllers on cancel on web

---

packages/sensors_plus/sensors_plus/README.md
packages/sensors_plus/sensors_plus/android/build.gradle

Same as #2252, but additionally fixed badge link in README
#2251 

fix(sensors_plus): Change Kotlin version from 1.9.10 to 1.7.22

---

packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/example/android/build.gradle

fix(battery_plus): Change Kotlin version from 1.9.10 to 1.7.22

---

packages/device_info_plus/device_info_plus/macos/Classes/SystemUUID.swift

Fix macOS warning for device_info_plus
- *Fix #2376*

fix(device_info_plus): Fix deprecation warning on MacOS

---

packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_web_test.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart

This PR aims at fixing a scenario where we get `version.json` from the app page with no file extension on the web. Such an url would previously break the `version.json` url when trying to get it.
- *Fixes #2282*
There is a small breaking change as an url not ending with a slash would previously have been recognized as a folder, resulting in a different url. For exemple, given an app url "https://example.com/a/b/c?hello_world=true#/my-page", the version.json path would be:
- Before change: "https://example.com/a/b/c/version.json?cachebuster=1" (notice the "c/" in url)
- After change: "https://example.com/a/b/version.json?cachebuster=1"

fix(package_info_plus)!: allow no page extension in versionJsonUrl on web

---

packages/package_info_plus/package_info_plus/lib/src/file_version_info.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart
packages/package_info_plus/package_info_plus/pubspec.yaml

Change from using `dart:html` to `package:web`. This will allow this plugin to be used from Wasm.

fix(package_info_plus): migrate to pkg:web from dart:html

---

packages/sensors_plus/sensors_plus_platform_interface/lib/src/method_channel_sensors.dart
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml

Since android [SensorManager.registerListener()](https://developer.android.com/reference/android/hardware/SensorManager#registerListener(android.hardware.SensorEventListener,%20android.hardware.Sensor,%20int)) reserved value 0-3 for samplingPeriodUs to `SENSOR_DELAY_*` constants. If user set the value to 1-3μs in this plugin, it cause android and ios behave differently. Note that 0 is safe.
This PR is to add protection by printing warning message and change the value automatically.
Related #2248

fix(sensors_plus): Add protection of reserved samplingPeriod value

---

packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt
packages/battery_plus/battery_plus_platform_interface/lib/src/enums.dart
packages/battery_plus/battery_plus_platform_interface/lib/src/utils.dart

Normally, there are 5 different states to define the battery state on the Android side:
https://developer.android.com/reference/android/os/BatteryManager#BATTERY_STATUS_CHARGING
`full`, `charging`, `discharging`, `not _charging`, `unknown`. But in the current code base, `discharging` and `not_charging` are considered the same, and both are parsed as `discharging`.
With this change, if the Android SDK has a `not_charging` state, the Flutter side will also see this state.
On Samsung phones, if we enable battery protection, the phone charges up to 85%. When it reaches 85%, the status changes from `charging` to `not_charging`. When I checked, the current used is almost 0 mA.
Fix #2274

fix(battery_plus): Implement not charging battery state

---

packages/battery_plus/battery_plus/example/macos/Runner.xcodeproj/project.pbxproj
packages/battery_plus/battery_plus/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/battery_plus/battery_plus/macos/Classes/BatteryPlusChargingHandler.swift
packages/battery_plus/battery_plus_platform_interface/lib/src/enums.dart
packages/battery_plus/battery_plus_platform_interface/lib/src/utils.dart

Adding new `connected_not_charging` state to MacOS as follow-up to #2275 which introduced such state on Android.
Renamed the state from the initial name suggested in #2275 to be more explicit.
Marking as a breaking change to bring attention to the new state in platform interface and because I have reimplemented MacOS states definition.
Looks like this state can be added for Linux as well, so will open one more PR for Linux platform.

feat(battery_plus)!: Introduce connected_not_charging state on MacOS

---

packages/battery_plus/battery_plus/lib/src/battery_plus_linux.dart
packages/battery_plus/battery_plus_platform_interface/lib/src/enums.dart

Feature similar to #2399 and #2275 
Had hard time trying to find out what is `pending discharge` state and made an assumption that it is similar to `discharging` as it was done here, for example: https://yarp.it/git-master/upowerBattery_8cpp_source.html

feat(battery_plus): Introduce not_charging state on Linux

---

docs/battery_plus/usage.mdx
packages/battery_plus/battery_plus/README.md

Mention the new state returned by the plugin and add missing information about battery save mode to both README and website docs.

docs(battery_plus): Improve documentation on battery states

---

packages/sensors_plus/sensors_plus/README.md

Following the discussion in the #2448 issue updating the plugin's README to mention that it is not guaranteed that specified sampling period will work on Android.
#2448 

docs(sensors_plus): Update README to mention how sampling rate works on Android

---

packages/battery_plus/battery_plus/android/src/main/kotlin/dev/fluttercommunity/plus/battery/BatteryPlusPlugin.kt

Fix for a forgotten renaming in Android implementation.
Fixes #2450

fix(battery_plus): Return correct state enum value on Android for not charging state

---

packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart

On web magnetometer stream wasn't closed and this issue was catched by pub.dev score checker.

fix(sensors_plus): Close magnetometerStreamController on web

---

packages/share_plus/share_plus/README.md

Updated file-sharing compatibility text for desktop platforms
The readme file had misleading info stating file sharing is not supported on Linux and Windows. But on Windows file sharing was working. This PR contains a fix for that.

docs(share_plus): Fix supported platforms in README

---

packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt

My friend who would share links via `share_plus` through Verizon's Message+ app, faced an issue where there would always be an additional null message alongside the shared link:
After doing a lot of digging and trying different things to try to fix this, I noticed that `Intent.EXTRA_SUBJECT` is always set to null when a subject is not specified. I suspected that this was the issue, given it was only happening for this one messaging platform, which may not filter out a null subject like most others do. Sure enough, after using my fork in place of the official `share_plus` package and having my friend send me a link again, this issue was fixed. I suspect that there may be other platforms affected by this as well.
N/A
Does your PR require plugin users to manually update their apps to …

fix(share_plus): Ensure subject is not null before calling putExtra(Intent.EXTRA_SUBJECT, subject)

---

docs/connectivity_plus/usage.mdx

Fixed variable name in documentation of connectivity_plus (usage)
- [ x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x ] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [ x] All existing and new tests are passing.
- [ x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ x] No, this is *not* a breaking change.

docs(connectivity_plus): fix var name in usage.mdx 

---

packages/network_info_plus/network_info_plus/README.md

Since I didn't see that network info plus doesn't work in IOS simulators and I got null every time I made this PR to add that note to readme and avoid wasting time.

docs: Added ios simulators note for testing

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_windows.dart

Fixes a crash in DIP when the Digital product ID on Windows is malformed.
By the way, the analyzer is in fact failing on my machine on this PR, but this is due to already existing errors within all modules.
I will not fix them here as they are unrelated to this PR.
If you think, I can also fix (at least the DIP-related ones) in this PR, I will of course do so.
- Fixes #2270

fix(device_info_plus): fix crash on non-standard Digital Product IDs

---

packages/battery_plus/battery_plus/ios/Classes/FPPBatteryPlusPlugin.m

If battery percentage never read battery state is always unknown
None

fix(battery_plus): battery state always unknown (iOS only)

---

.github/workflows/device_info_plus.yaml

Testing how new M1 runners work
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

chore(device_info_plus): Switch CI runners to M1

---

.github/workflows/battery_plus.yaml

Switching the next plugin to M1

chore(battery_plus): Switch CI runners to M1

---

.github/workflows/android_alarm_manager_plus.yaml

Switching to M1. Note, like the rest of plugins job to run Android integration tests doesn't migrate due to emulator Action not supporting ARMs at the moment.

chore(android_alarm_manager_plus): Partially switch CI runners to M1

---

.github/workflows/android_intent_plus.yaml

Switching to M1. Note, like the rest of plugins job to run Android integration tests doesn't migrate due to emulator Action not supporting ARMs at the moment.

chore(android_intent_plus): Partially switch runners to M1

---

.github/workflows/share_plus.yaml

Continue migration of the rest of Plus Plugins workflows to M1 machines

chore(share_plus): Switch CI runners to M1

---

packages/battery_plus/battery_plus/ios/PrivacyInfo.xcprivacy
packages/battery_plus/battery_plus/ios/battery_plus.podspec

- Add PrivacyInfo to podspec of **Battery Plus**

fix(battery_plus): Add iOS Privacy Info

---

packages/share_plus/share_plus/ios/PrivacyInfo.xcprivacy
packages/share_plus/share_plus/ios/share_plus.podspec

- Add PrivacyInfo to podspec of **Share Plus**

fix(share_plus): Add iOS Privacy Info

---

packages/sensors_plus/sensors_plus/ios/PrivacyInfo.xcprivacy
packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec

- Add PrivacyInfo to podspec of **Sensors Plus**

fix(sensors_plus): Add iOS Privacy Info

---

packages/package_info_plus/package_info_plus/ios/PrivacyInfo.xcprivacy
packages/package_info_plus/package_info_plus/ios/package_info_plus.podspec

- Add PrivacyInfo to podspec of **Package Info Plus**

fix(package_info_plus): Add iOS Privacy Info

---

packages/network_info_plus/network_info_plus/ios/PrivacyInfo.xcprivacy
packages/network_info_plus/network_info_plus/ios/network_info_plus.podspec

- Add PrivacyInfo to podspec of **Network Info Plus**

fix(network_info_plus): Add iOS Privacy Info

---

packages/device_info_plus/device_info_plus/ios/PrivacyInfo.xcprivacy
packages/device_info_plus/device_info_plus/ios/device_info_plus.podspec

- Add PrivacyInfo to podspec of **Device Info Plus**

fix(device_info_plus): Add iOS Privacy Info

---

packages/connectivity_plus/connectivity_plus/ios/PrivacyInfo.xcprivacy
packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec

- Add PrivacyInfo to podspec of **Connectivity Plus**

fix(connectivity_plus): Add iOS Privacy Info

---

packages/connectivity_plus/connectivity_plus/macos/connectivity_plus.podspec

Bump MACOSX_DEPLOYMENT_TARGET to Flutter minimum (10.14)

refactor(connectivity_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/device_info_plus/device_info_plus/macos/device_info_plus.podspec

Bump MACOSX_DEPLOYMENT_TARGET to Flutter minimum (10.14)

refactor(device_info_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/share_plus/share_plus/macos/share_plus.podspec

Bump `MACOSX_DEPLOYMENT_TARGET` to Flutter minimum (10.14)

refactor(share_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/battery_plus/battery_plus/macos/battery_plus.podspec

Bump `MACOSX_DEPLOYMENT_TARGET` to Flutter minimum (10.14)

refactor(battery_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/package_info_plus/package_info_plus/macos/package_info_plus.podspec

Bump `MACOSX_DEPLOYMENT_TARGET` to Flutter minimum (10.14)

refactor(package_info_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/network_info_plus/network_info_plus/macos/network_info_plus.podspec

Bump `MACOSX_DEPLOYMENT_TARGET` to Flutter minimum (10.14)

refactor(network_info_plus)!: bump MACOSX_DEPLOYMENT_TARGET from 10.11 to 10.14

---

packages/device_info_plus/device_info_plus/ios/Classes/FPPDeviceInfoPlusPlugin.m
packages/device_info_plus/device_info_plus/lib/src/model/ios_device_info.dart
packages/device_info_plus/device_info_plus/test/model/ios_device_info_test.dart

For iOS devices `isPhysicalDevice` was returned as `String` from native platform, now it is returning boolean from native platform.
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/fluttercommunity/plus_plugins/issues). Indicate, which of these issues are resolved or fixed by this PR.*
*e.g.*
- *Fix #2483  *
- *Related N/A*

fix(device_info_plus)!: return type of isPhysicalDevice as boolean for ios

---

packages/package_info_plus/package_info_plus/pubspec.yaml

Allow the latest 0.5.0 release of the web package.
Other packages like http already require a minimum version of 0.5.0 (changelog)[https://pub.dev/packages/http/changelog#121].
none

chore(package_info_plus): support web 0.5.0

---

packages/device_info_plus/device_info_plus/macos/Classes/CwlSysctl.swift

removed one print line
- Fix #2526

fix(device_info_plus): remove unnecessary print

---

packages/share_plus/share_plus/ios/Classes/FPPSharePlusPlugin.m

- The code was never completing when being awaited.
- This is due to the missing call to `result(nil)`.
- Tested on iOS simulator using example project.
- Fix #2609 

fix(share_plus): Add missing call to result for shareUri on iOS

---

.github/workflows/all_plugins.yaml

Bumping to v3 to use Node 20 to be in line with Github's changes: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Currently, we also have warnings after CI runs due to usage of Node 16:

chore(all): Update GitHub Action for Dart Analyzer

---

packages/package_info_plus/package_info_plus/lib/package_info_plus.dart

Opening as a replacement for #2622 as there the author couldn't explain clearly why that change was needed in the PR description.
Despite the fact that `package_info_plus` already migrated to package `web` in November in #2316 it was still not fully compatible with WASM according to point 1 here: https://dart.dev/interop/js-interop/package-web#package-web-vs-dart-html
There is a suggestion on how imports need to be modified to support WASM compilation: https://dart.dev/interop/js-interop/package-web#conditional-imports
Change in this PR is based on that suggestion.
It was briefly mentioned in #2623 but had poor title and explanation.

feat(package_info_plus): Use js_interop instead of html to support compilation to WASM

---

packages/device_info_plus/device_info_plus/lib/src/model/linux_device_info.dart
packages/device_info_plus/device_info_plus/test/model/linux_device_info_test.dart

Adds `toString` for `LinuxDeviceInfo`. This is useful when debugging apps on Linux distros.
N/A

feat(device_info_plus): LinuxDeviceInfo toString method

---

packages/device_info_plus/device_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/device_info_plus/device_info_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/device_info_plus/device_info_plus/ios/device_info_plus.podspec

Updating iOS setup to explicitly mention that iOS 12 is a min deployment version, so there are no warnings. 
Considering that we are bumping min Dart version to 3.3 it means that it will be users with latest Flutter versions, which already work with min iOS 12 only, thus, this change would not really affect such users.
Will open follow-up PRs for other plugins as well.
Part of #2442

feat(device_info_plus): Update min iOS target to 12

---

packages/connectivity_plus/connectivity_plus/example/lib/main.dart
packages/connectivity_plus/connectivity_plus_platform_interface/lib/method_channel_connectivity.dart

I was working on updates for example app to show newly added multiple [connection types feature](#2599) in a more nice way and found a bug that when only one connection type is available there is an exception in the platform interface as returned result isn't a list, but a String:
This PR fixes mentioned bug and also updates the example UI to look better:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix(connectivity_plus): Return valid connection type when only one available

---

.github/workflows/all_plugins.yaml
packages/android_alarm_manager_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/FlutterBackgroundExecutor.java
packages/android_alarm_manager_plus/example/android/gradle/wrapper/gradle-wrapper.properties
packages/android_intent_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/AndroidIntentPlugin.java
packages/android_intent_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java

Just found out that we had version 1.3 of Google Java Format tool, which was released in 2017. Updated to the latest one.
Probably, some new issues would appear with formatting as I expect rules changes during all these years.

ci(all): Update Google Java Format tool

---

.gitignore

- Adds the `pubspec_overrides.yaml` configuration file to `.gitignore` at the project root.
- This file is created by the `melos bootstrap` command when configuring the project.
- We avoid committing it by mistake.
- none

chore: ignore pubspec_overrides.yaml in git

---

packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart

As suggested by the `package:web/helpers.dart` that it is deprecated and `package:web/web.dart` should be used instead as both these files export the same thing.
They do not pose any issue while using the package, but while fixing another issue in one of the packages I saw these linting warnings and thought of fixing them.
Trivial changes so doesn't need an issue.

chore(package_info_plus): change deprecated web/helpers to web/web import

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.kt
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/src/main/kotlin/io/flutter/plugins/deviceinfoexample/example/MainActivity.kt
packages/device_info_plus/device_info_plus/example/lib/main.dart

- Ensure that the `WindowManager` is obtained from the `Activity Context` instead of `Application Context`
- Use `ActivityAware` to obtain `Activity` binding in `DeviceInfoPlusPlugin` class.
- Set a null MethodHandler when the activity is detached (doing the same as in the `onDetachedFromEngine` method).
- Add the Strict Mode configuration to example project Android code to ensure the `Activity Context` use is correct.
- Tested on Pixel 5.
- Fixes #2687

fix(device_info_plus): Ensure use of Activity Context to obtain WindowManager

---

packages/android_intent_plus/lib/flag.dart

Fixes the dangling dart doc comment linting issue by moving the ignore comment at top of file and adding one where not present. 
They do not pose any issue while using the package, but while fixing another issue in one of the packages I saw these linting warnings and thought of fixing them.
Trivial changes so doesn't need an issue.

chore(android_intent_plus): fixes dangling dart doc comment linting issue

---

packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
packages/sensors_plus/sensors_plus/lib/src/web_sensors_interop.dart
packages/sensors_plus/sensors_plus/pubspec.yaml

APIs such as Accelerometer are defined independently using dart:js_interop.
---
Do you know how to see the sensor change in the browser, I tried emulation with chrome dev tools but could not see the value change.
https://developer.chrome.com/docs/devtools/sensors
- Resolve #2602

feat(sensors_plus)!: Migrate to dart:js_interop

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_macos.dart

Ignores the dangling dart doc comment linting issue for an empty file with informative comment.
They do not pose any issue while using the package, but while fixing another issue in one of the packages I saw these linting warnings and thought of fixing them.
Trivial changes so doesn't need an issue.

chore(device_info_plus): ignores dangling dart doc comment linting issue for empty file

---

packages/connectivity_plus/connectivity_plus/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle

Bringing plugins up to date to compile against latest Android version. Picked `build` as prefix because `chore` won't end up in the release notes during Melos versioning and this change is something that needs to be in release notes.

build(connectivity_plus): Update to target and compile SDK 34 on Android

---

packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/example/android/app/build.gradle

Same as #2701 but for `battery_plus`

build(battery_plus): Update to target and compile SDK 34 on Android

---

packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/device_info_plus/device_info_plus/example/android/app/build.gradle

Same as #2701 but for `device_info_plus`

build(device_info_plus): Update to target and compile SDK 34 on Android

---

packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle

Same as #2701 but for `network_info_plus`

build(network_info_plus): Update to target and compile SDK 34 on Android

---

packages/package_info_plus/package_info_plus/android/build.gradle
packages/package_info_plus/package_info_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/package_info_plus/package_info_plus/example/android/app/build.gradle

Same as #2701 but for `package_info_plus`

build(package_info_plus): Update to target and compile SDK 34 on Android

---

packages/sensors_plus/sensors_plus/android/build.gradle
packages/sensors_plus/sensors_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/sensors_plus/sensors_plus/example/android/app/build.gradle

Same as #2701 but for `sensors_plus`

build(sensors_plus): Update to target and compile SDK 34 on Android

---

packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus/lib/src/share_plus_web.dart
packages/share_plus/share_plus/pubspec.yaml

Migration to the `web` package and addition of override methods.
---
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility
Chrome desktop doesn't support Share API on macOS.If someone want to run on macOS, please use Safari.
First, `flutter run` and check the service's url (ex. `http://localhost:55926/`). Then, open the url by Safari. 
---
https://koji-1009.github.io/plus_plugins/
I uploaded example app. The branch is [share_plus_web_demo](https://github.com/koji-1009/plus_plugins/tree/feat/share_plus_web_demo).
When I try to build on GitHub Actions, it fails at [odd points](https://github.com/koji-1009/plus_plugins/actions/runs/8304801875/job/22730899994). For this reason, we push the build on the local machine to the gh-pages branch.
- Closes #2603
- …

feat(share_plus)!: Migrate to package:web

---

packages/android_alarm_manager_plus/android/build.gradle
packages/android_alarm_manager_plus/example/android/app/build.gradle
packages/android_alarm_manager_plus/example/lib/main.dart
packages/android_alarm_manager_plus/example/pubspec.yaml

Moving the plugin to target and compile against SDK 34 (Android 14).
Decided to also rework the example app a bit to let users request SCHEDULE_EXACT_ALARM permission. When app has no such permission schedule alarm button is disabled and request permission buttons is enabled. When user provides the permission schedule button becomes enabled while request permission button disables.
Additionally improved texts to improve UX by explaining what is currently happening.

build(android_alarm_manager_plus): Update to target and compile SDK 34 on Android

---

packages/android_intent_plus/android/build.gradle
packages/android_intent_plus/android/src/main/AndroidManifest.xml
packages/android_intent_plus/example/android/app/build.gradle
packages/android_intent_plus/example/android/app/src/main/java/io/flutter/plugins/androidintentexample/MainActivity.java

Same as #2701 but for `android_intent_plus`. 
Additionally, fixed the example app as it didn't even build locally.

build(android_intent_plus): Update to target and compile SDK 34 on Android

---

packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/Share.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt
packages/share_plus/share_plus/example/android/app/build.gradle

Same as #2701 but with a few additional fixes for the example app.

build(share_plus): Update to target and compile SDK 34 on Android

---

packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart

link https://github.com/fluttercommunity/plus_plugins/pull/2709#issuecomment-2002369298
This PR fix a problem in the release build where DOMException cannot be try-catch.
The problem occurs in Desktop browsers where the Sensors API is not available.
- Related #2602

fix(sensors_plus): Add try-catch for release builds

---

packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/SharePlusPendingIntent.kt

Minor change to see less warnings during the build. As we use that broadcast receiver only when use `withResult`, which works only for Android API 22 and newer, this annotation effects nothing except of dropping lint warning which appears due to `Intent.EXTRA_CHOSEN_COMPONENT` otherwise.
In the #2519 there is one more deprecation mentioned, but it was valid only for compile SDK 33 as in 34 this warning doesn't appear.
Closes #2519

fix(share_plus): Resolve deprecation warning in Android part

---

docs/android_alarm_manager_plus/usage.mdx
packages/android_alarm_manager_plus/README.md
packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart

Added information about Android 13 and 14 on exact alarms. Should be enough, I believe.
Closes #2194

docs(android_alarm_manager_plus): Update information about SCHEDULE_EXACT_ALARM permission

---

packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java

Adding connectivity types check on Android when user subscribes to a stream of changes. This is needed for case with no active connections during subscription, like it is described in #2527. I checked it and indeed `NetworkCallback` triggers on subscription only when some connection is available. When device has everything off and user subscribes to connectivity types changes no events triggered. 
As I described in my comment in the issue I don't consider it a bug, but a specific of usage.
In any case added `sendEvent()` call in the `onListen()` function and it makes the stream emit an event with connection types right away on subscription.
Tested with example app by removing the call to [`checkConnectivity()`](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivit …

fix(connectivity_plus): Emit event with types on Android when subscribing to onConnectivityChanged

---

packages/connectivity_plus/connectivity_plus/example/ios/Runner/Info.plist

Looks like I didn't notice wrong name when was working on regeneration of example apps some time ago.

fix(connectivity_plus): Fix iOS example app name

---

packages/android_alarm_manager_plus/android/build.gradle

Targeting Java 17 to be up to date with ecosystem.
Considering that we are using Gradle 8.4 now no compatibility problems expected: https://docs.gradle.org/current/userguide/compatibility.html
Also, with this change users should not see such deprecation warnings anymore:
Marking as a breaking change to highlight it in release notes.

build(alarm_manager_plus)!: Target Java 17 on Android

---

packages/device_info_plus/device_info_plus/android/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle

build(device_info_plus)!: Target Java 17 on Android

---

packages/battery_plus/battery_plus/android/build.gradle
packages/battery_plus/battery_plus/android/gradle/wrapper/gradle-wrapper.properties
packages/battery_plus/battery_plus/example/android/app/build.gradle
packages/battery_plus/battery_plus/example/lib/main.dart

Same as #2723 
Additionally updated example app a bit as text with state didn't look good from my point of view.
Here is before and after:

build(battery_plus)!: Target Java 17 on Android

---

packages/network_info_plus/network_info_plus/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle

build(network_info_plus)!: Target Java 17 on Android

---

packages/share_plus/share_plus/android/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties

build(share_plus)!: Target Java 17 on Android

---

packages/battery_plus/battery_plus/example/lib/main.dart
packages/battery_plus/battery_plus/example/pubspec.yaml
packages/battery_plus/battery_plus/lib/src/battery_plus_web.dart
packages/battery_plus/battery_plus/pubspec.yaml

Migration to the `web` package and add missing API.
https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager#browser_compatibility
BatteryManager API is only supported Chrome or Edge.
Safari and Firefox are not supported, so status is expected to be unknown.
- Related #2653

feat(battery_plus)!: Migrate to package:web

---

packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/example/android/build.gradle
packages/package_info_plus/package_info_plus/example/android/settings.gradle

Considering that fact that some of Plug Plugins will require Flutter 3.19 as min version in their next release I decided to also address the deprecation in how we declare Android related plugins in example apps. Currently users would see warnings during example app builds like this one: https://github.com/fluttercommunity/plus_plugins/actions/runs/8308735389/job/22743183649#step:5:96
There is also an official guidance from the Flutter team on this topic: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
With this change our example apps will be more or less up to date and show a good example on how to apply the new approach to apps.

refactor(package_info_plus): Migrate Android example to use the new plugins declaration

---

packages/package_info_plus/package_info_plus/example/android/settings.gradle
packages/share_plus/share_plus/example/android/app/build.gradle
packages/share_plus/share_plus/example/android/build.gradle
packages/share_plus/share_plus/example/android/settings.gradle

Updating example app according to https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
Similar to #2715

refactor(share_plus): Migrate Android example to use the new plugins declaration

---

packages/battery_plus/battery_plus/example/lib/main.dart
packages/battery_plus/battery_plus/lib/src/battery_plus_web.dart

Fixed an exception that occurred when calling `getBattery()` in firefox and safari.
In cases where `getBattery()` is undefined, you need to declare `JSPromise<BatteryManager>? ` instead of `JSPromise<BatteryManager>`.
The example code has been reverted to the previous one, as the try-catch is now correct.
- Related #2720

fix(battery_plus): Fix return value of getBattery to be nullable

---

packages/device_info_plus/device_info_plus/README.md

- Adds clarification regarding entitlements needed to access the property `UIDevice.current.name` on iOS 16 and later.
- Also formatted the README.md a bit.
- Closes #2755

docs(device_info_plus): Add iOS name property entitlements info

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.kt
packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt
packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_fake.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_test.dart

The idea is to detect whether the running device is on low RAM or not. From `ActivityManager` we are getting `isLowRamDevice()` which is added on `AndroidDeviceInfo`
- Fix #2759

feat(device_info_plus): Add isLowRamDevice property to AndroidDeviceInfo

---

packages/connectivity_plus/connectivity_plus/README.md
packages/connectivity_plus/connectivity_plus/darwin/Classes/PathMonitorConnectivityProvider.swift

This PR introduces a couple of code changes:
1. Increases the `DispatchQueue` "Quality of Service" from `.background` to `.utility`, as per documentation seems like a better choice.
2. The `pathUpdateHandler` has been modified to use the provided `path` instead of using the stored `currentPath` in the path monitor. This may make a difference when it comes to obtaining reliable connectivity change updates. The code has been refactored to reuse the existing method.
As well, I have updated the README.md with some information regarding the iOS implementation and its limitations.
- Closes https://github.com/fluttercommunity/plus_plugins/issues/858

fix(connectivity_plus): Improve iOS PathMonitorConnectivityProvider implementation and documentation

---

packages/share_plus/share_plus/README.md

Improves the README.md adding an explanation on how to deal with different localizations and the share sheet on iOS.
- Related to #2696 

docs(share_plus): Add info regarding localization on Apple to README

---

packages/connectivity_plus/connectivity_plus/README.md

Revisited the README after looking through https://github.com/fluttercommunity/plus_plugins/issues/2041 issue. Re-phrased a few statements to bring some more clarity and did minor typo/formatting fixes.

docs(connectivity_plus): Update README for more clarity

---

packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/gradle/wrapper/gradle-wrapper.properties
packages/connectivity_plus/connectivity_plus/example/android/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/settings.gradle

Similar to #2769
The only difference is removal of unused old `gradle-wrapper` file.

refactor(connectivity_plus): Migrate Android example to use the new plugins declaration

---

packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/example/android/build.gradle
packages/network_info_plus/network_info_plus/example/android/settings.gradle

Updating example app according to https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
Similar to https://github.com/fluttercommunity/plus_plugins/pull/2715

refactor(network_info_plus): Migrate Android example to use the new plugins declaration

---

packages/android_alarm_manager_plus/example/android/app/build.gradle
packages/android_alarm_manager_plus/example/android/build.gradle
packages/android_alarm_manager_plus/example/android/settings.gradle

Similar to #2773. Last of PRs on this topic. All plugins now migrated to the new recommended way to declare Android plugins.

refactor(android_alarm_manager_plus): Migrate Android example to use the new plugins declaration

---

packages/connectivity_plus/connectivity_plus/README.md

This PR contains documentation updates for `connectivity_plus`.
Since not all possible `ConnectivityResult` values are supported on all platforms (e.g. the iOS implementation doesn't support bluetooth connectivity reporting) I think it would be useful to document that, in order to avoid misunderstandings.
Also included macOS in the section about iOS, since they share implementation.
- Closes https://github.com/fluttercommunity/plus_plugins/issues/2776

docs(connectivity_plus): Document supported ConnectivityResult per platform

---

packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt

- Looking at issues reported in #1936 and #1351, I figured out that the `ShareSuccessManager` was in a bad state which blocked users from continuing using the plugin.
- The `ShareSuccessManager` checks the state of the current callback state, and fails if a callback was never executed. This is problematic because causes this state to be never recover after an error happened.
- The problem is that, on error, `onActivityResult` is never called, so the state is never restored.
- To solve this problem, I introduced a `clear()` method that will reset the state, only call to this method in cases we catch an error.
- did a refactor, and moved things a bit, simplifying the code of the `MethodCallHandler`.
- to test this, I call `shareXFiles` with bad `XFile` (wrong paths), which causes an …

fix(share_plus): Recover ShareSuccessManager state after error

---

packages/device_info_plus/device_info_plus/lib/device_info_plus.dart

Migrates the conditional imports to support WASM (see https://dart.dev/interop/js-interop/package-web#conditional-imports)
- Fixes https://github.com/fluttercommunity/plus_plugins/issues/2821

fix(device_info_plus): WASM-compatible conditional imports

---

packages/connectivity_plus/connectivity_plus/lib/connectivity_plus.dart

Migrates the conditional imports to support WASM (see https://dart.dev/interop/js-interop/package-web#conditional-imports)
- Fixes https://github.com/fluttercommunity/plus_plugins/issues/2822

fix(connectivity_plus): WASM-compatible conditional imports

---

packages/sensors_plus/sensors_plus/lib/sensors_plus.dart

Migrates the conditional imports to support WASM (see https://dart.dev/interop/js-interop/package-web#conditional-imports)
- Fixes https://github.com/fluttercommunity/plus_plugins/issues/2823

fix(sensors_plus): WASM-compatible conditional imports

---

packages/share_plus/share_plus/README.md
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/MethodCallHandler.kt
packages/share_plus/share_plus/android/src/main/kotlin/dev/fluttercommunity/plus/share/ShareSuccessManager.kt
packages/share_plus/share_plus/example/integration_test/share_plus_test.dart
packages/share_plus/share_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/share_plus/share_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/share_plus/share_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/share_plus/share_plus/example/ios/Runner/Info.plist
packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/example/macos/Runner.xcodeproj/project.pbxproj
packages/share_plus/share_plus/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/share_plus/share_plus/ios/Classes/FPPSharePlusPlugin.m
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus/lib/src/share_plus_linux.dart
packages/share_plus/share_plus/lib/src/share_plus_web.dart
packages/share_plus/share_plus/lib/src/share_plus_windows.dart
packages/share_plus/share_plus/macos/Classes/SharePlusMacosPlugin.swift
packages/share_plus/share_plus/windows/share_plus_plugin.cpp
packages/share_plus/share_plus/windows/share_plus_windows_plugin.h
packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart

This PR contains a major cleanup of the `share_plus` plugin.
In detail:
- Reduces API to three methods: `shareUri`, `share` and `shareXFiles`(removed deprecated methods).
- All methods return a `ShareResult`.
- Cleanup of Android implementation. 
- Modified the `ShareSuccessManager` so it would not deadlock users anymore, instead, calling to `share` while there is another call waiting, causes that the previous call will be called back with `ShareResult.unavailable`, instead of causing an error.
- Tested on Pixel 5 for all three methods sharing on Telegram, they all work with `ShareResult` correctly returned.
- Clean of iOS implementation.
- Tested on iPhone 12 mini, sharing uri, text, and text+image on Telegram, all work and return `ShareResult` correctly.
- Cleanup macOs implementation
- …

refactor(share_plus)!: Share API cleanup

---

packages/connectivity_plus/connectivity_plus/README.md
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/Connectivity.java
packages/connectivity_plus/connectivity_plus/android/src/main/java/dev/fluttercommunity/plus/connectivity/ConnectivityBroadcastReceiver.java
packages/connectivity_plus/connectivity_plus/example/lib/main.dart
packages/connectivity_plus/connectivity_plus/lib/connectivity_plus.dart
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/share_plus/share_plus/windows/vector.h

- Doing tests, I noticed that the connectivity did not change when disabling mobile connection, see https://github.com/fluttercommunity/plus_plugins/issues/2831#issuecomment-2048946133
- The events received in `onConnectivityChange` were not correct.
- When I disconnected mobile, the `onConnectivityChange` was still reporting connectivity `mobile`.
- I did some changes on the connectivity change listeners in Android and the issue is gone.
- In the `onLost` callback: Increased the delay to 500 milliseconds to avoid race conditions.
- In the other two callbacks, use the provided Network and Capabilities objects, this ensures that the actual event payload is used and not reading a value that may be not up-to-date.
- The "delayed" callback is now only used `onLost`.
- I added a `distinct` to …

fix(connectivity_plus): Ensure Connectivity on Android is correctly reported when lost

---

.github/workflows/all_plugins.yaml
.github/workflows/all_plugins_skipper.yaml
.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

Don't see much value in `analyze` for all packages as it would be more appropriate to analyze every individual package when changed. Thus, modified workflows to do exactly this.
Didn't change `infos` to `fatal` state as it seemed too much, but maybe forcing even infos might be good to be sure that we and other contributors resolve lint issues right away.
Part of #2775 

ci(all): Analyze every package individually

---

.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

Expanding the Android versions matrix to include the latest Android 14 (API 34) into a test suit as well. 
I expect that integration tests will fail for `android_alarm_manager_plus` because of permission requirements.
Also changed from iPhone 14 to 15, but it shouldn't make any difference for iOS tests.

refactor(all): Update integration tests configuration

---

.github/workflows/android_alarm_manager_plus.yaml
.github/workflows/android_intent_plus.yaml
.github/workflows/battery_plus.yaml
.github/workflows/connectivity_plus.yaml
.github/workflows/device_info_plus.yaml
.github/workflows/network_info_plus.yaml
.github/workflows/package_info_plus.yaml
.github/workflows/sensors_plus.yaml
.github/workflows/share_plus.yaml

This is a minor change to not automatically cancel all jobs in the integration tests matrix on Android as we currently have.
In most cases it is API 22 that causes the trouble, but I believe we are still interested in rest of APIs passing without the need to do some manual re-tries ourselves.

ci(all): Do not fail fast on Android integration tests failure

---

packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/FlutterBackgroundExecutor.java

Flutter will be removing the remains of the android v1 embedding code and to make that easier for you here is a CL.
Please make a release ASAP that includes this change.

fix(android_alarm_manager_plus): Remove references to v1 embedding

---

packages/android_alarm_manager_plus/example/android/settings.gradle

Reverts fluttercommunity/plus_plugins#2895
Reverting as it turned out that fresh AGP version requires newer Gradle version

chore(deps): revert bump com.android.application from 8.3.1 to 8.4.0 in android_alarm_manager_plus/example

---

packages/network_info_plus/network_info_plus/android/build.gradle

Reverts fluttercommunity/plus_plugins#2894
Reverting as new AGP requires Gradle 8.6

chore(deps): revert bump com.android.tools.build:gradle from 8.3.1 to 8.4.0 network_info_plus

---

packages/android_intent_plus/example/android/app/build.gradle
packages/battery_plus/battery_plus/example/android/app/build.gradle
packages/connectivity_plus/connectivity_plus/example/android/app/build.gradle
packages/device_info_plus/device_info_plus/example/android/app/build.gradle
packages/network_info_plus/network_info_plus/example/android/app/build.gradle
packages/package_info_plus/package_info_plus/example/android/app/build.gradle
packages/sensors_plus/sensors_plus/example/android/app/build.gradle
packages/share_plus/share_plus/example/android/app/build.gradle

`minSdk` must be `21` on Flutter  `3.22.0` since it is a requirement by `integration_test` package.
- Some Dependabot PRs failed, e.g.: #2939 

chore(all): Increase minSdk to 21 on all Android examples

---

.github/workflows/android_intent_plus.yaml
packages/android_intent_plus/example/integration_test/android_intent_plus_test.dart
packages/android_intent_plus/example/pubspec.yaml

Because `android_intent_example` doesn't match `android_intent_plus`, the package is not properly bootstraped by melos, and so PRs that change the package and example fail to build.

ci(android_intent_plus): fix example package name

---

packages/android_alarm_manager_plus/example/integration_test/android_alarm_manager_plus_test.dart
packages/android_alarm_manager_plus/example/pubspec.yaml

Fix similar to #2973 as we had the same problem for the `android_alarm_manager_plus` (for example, issue is mentioned here https://github.com/fluttercommunity/plus_plugins/pull/2898#issuecomment-2089880624) plugin as well with bootstrapping and building the example app on CI.

ci(android_alarm_manager_plus): fix example package name

---

packages/android_intent_plus/android/src/main/AndroidManifest.xml

In gradle 8 ou higher setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
*[Question]: #2611

fix(android_intent_plus): remove package name from AndroidManifest

---

packages/package_info_plus/package_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/packageinfo/PackageInfoPlugin.kt

This plugin fails to compile with the latest nullability signatures for Android 35
The compilation error messages are:
```
PackageInfoPlugin.kt:45:56: error: [UNSAFE_CALL] Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ApplicationInfo?
put("appName", info.applicationInfo.loadLabel(packageManager).toString())
^
PackageInfoPlugin.kt:47:36: error: [TYPE_MISMATCH] Type mismatch: inferred type is String? but String was expected
put("version", info.versionName)
^^^^^^^^^^^^^^^^
PackageInfoPlugin.kt:108:51: error: [SMARTCAST_IMPOSSIBLE] Smart cast to 'Array<(out) Signature!>' is impossible, because 'packageInfo.signatures' is a mutable property that could have been changed by this time
if (signatures.isNullOrEmpty() || packageInfo.signatures.first() == …
```

fix(package_info_plus): Address changed fields nullability on Android 15 (API 35)

---

packages/network_info_plus/network_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/network_info/NetworkInfo.kt

The Android implementation of `network_info_plus` has been ignoring certain internal errors, making it impossible to debug why the methods return `null`.
e.g. https://github.com/fluttercommunity/plus_plugins/issues/1553#issuecomment-2216680660
This PR removes the try/catch.
According to `MethodHandler` docs:
> Any uncaught exception thrown by this method will be caught by the channel implementation and logged, and an error result will be sent back to Flutter.
In this case, the exceptions will be sent to the Flutter layer, and devs will have to handle them.
This is marked a BREAKING CHANGE, because I think this can cause unwanted errors for apps using this plugin (or a plugin that depends on this plugin), and so the code should be changed to handle these errors.
- Related #1553 
Does your …

fix(network_info_plus)!: Do not ignore errors on Android

---

packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
packages/package_info_plus/package_info_plus/example/pubspec.yaml

Fixing tests for `installerStore` value on Android as it seems like since Android 14 OS returns `com.android.shell` for apps installed via package manager, adb command (I suppose so) instead of `null`. Don't see any mentions of it in the documentation. Earlier we didn't see this test failing because we had no API 34 in our build matrix.
Checked with emulators and real phone with Android 14 - on Android 13 I see `null`, while on 14 for both virtual and real device see `com.android.shell` when installing example via Android Studio. I believe this fix for the integration test should be correct.

test(package_info_plus): Fix integration test for Android

---

README.md
packages/sensors_plus/sensors_plus/README.md
packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/SensorsPlugin.kt
packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt
packages/sensors_plus/sensors_plus/example/ios/Runner/Info.plist
packages/sensors_plus/sensors_plus/example/lib/main.dart
packages/sensors_plus/sensors_plus/ios/Classes/FPPSensorsPlusPlugin.swift
packages/sensors_plus/sensors_plus/ios/Classes/FPPStreamHandlerPlus.swift
packages/sensors_plus/sensors_plus/ios/sensors_plus.podspec
packages/sensors_plus/sensors_plus/lib/sensors_plus.dart
packages/sensors_plus/sensors_plus/lib/src/sensors.dart
packages/sensors_plus/sensors_plus/lib/src/sensors_plus_web.dart
packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
packages/sensors_plus/sensors_plus/lib/src/web_sensors_interop.dart
packages/sensors_plus/sensors_plus/test/sensors_test.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/sensors_plus_platform_interface.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/barometer_event.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/method_channel_sensors.dart
packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart

This PR implements barometer support for all platforms (Android, iOS, and web) within the `sensors_plus` plugin. The barometer sensor measures atmospheric pressure and can be used for various applications such as altimeters. 
Note: There are limitations for web platform, as according to [MZN docs](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs), there is no such support for barometer support. This has been implemented similarly to the magnetometer which is also not implemented on any modern browsers, so it handles and throws the right errors if used.
- Android Implementation (Tested): Updated Android specific methods and handlers for barometer sensor in:
- `...sensors_plus\android\src\main\kotlin\dev\fluttercommunity\plus\sensors\SensorsPlugin.kt`
- …

feat(sensors_plus)!: add barometer support for all platforms

---

packages/android_alarm_manager_plus/pubspec.yaml
packages/android_intent_plus/pubspec.yaml
packages/battery_plus/battery_plus/pubspec.yaml
packages/battery_plus/battery_plus_platform_interface/pubspec.yaml
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus_platform_interface/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_platform_interface/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/pubspec.yaml

Homepage link was not working for any plugins, replace those like with [https://github.com/fluttercommunity/plus_plugins](https://github.com/fluttercommunity/plus_plugins)
Fix #3092 

fix(all): changed homepage url in pubspec.yaml

---

packages/share_plus/share_plus/README.md
packages/share_plus/share_plus/example/lib/main.dart
packages/share_plus/share_plus/lib/share_plus.dart
packages/share_plus/share_plus/lib/src/share_plus_linux.dart
packages/share_plus/share_plus/lib/src/share_plus_web.dart
packages/share_plus/share_plus/lib/src/share_plus_windows.dart
packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart

* Adds parameter `nameOverride` to funciton `shareXFiles`
* If set the values in  `nameOverride` will be used as the file names for the files share
* Also added new button in example that demonstrates this behavior.
* This is needed because `XFile.fromData` ignores `name` parameter on platforms other than web.
- *Fix #3032*
- *Related #1548*

feat(share_plus)!: Introduce optional parameter `nameOverride` to `shareXFiles`.

---

packages/android_alarm_manager_plus/pubspec.yaml
packages/android_intent_plus/pubspec.yaml
packages/battery_plus/battery_plus/pubspec.yaml
packages/connectivity_plus/connectivity_plus/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml

Picked some of available topics from https://dart.dev/tools/pub/pubspec#topics and added for every plugin.
Feel free to add some if I missed something or there are some better topics.
Closes #2941

chore(all): Add pub.dev topics

---

packages/sensors_plus/sensors_plus/README.md
packages/sensors_plus/sensors_plus/example/lib/main.dart

Change sensors plus README.md to include:
1. Units for barometer
2. Web platform specific considerations for magnetometer and barometer due to it being missing.
4. iOS platform specific limitation for barometer not supporting custom sampling frequencies.
5. iOS platform requirement for `NSMotionUsageDescription`.
Change sensors plus example app to show pressure units.
Building on PR #3079.

chore(sensors_plus): update README and example app for units and platform specific recomendations

---

packages/sensors_plus/sensors_plus/android/src/main/kotlin/dev/fluttercommunity/plus/sensors/StreamHandlerImpl.kt
packages/sensors_plus/sensors_plus/example/lib/main.dart
packages/sensors_plus/sensors_plus/ios/Classes/FPPStreamHandlerPlus.swift
packages/sensors_plus/sensors_plus/lib/src/web_sensors.dart
packages/sensors_plus/sensors_plus/test/sensors_test.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/accelerometer_event.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/barometer_event.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/gyroscope_event.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/magnetometer_event.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/method_channel_sensors.dart
packages/sensors_plus/sensors_plus_platform_interface/lib/src/user_accelerometer_event.dart
packages/sensors_plus/sensors_plus_platform_interface/test/sensors_plus_platform_interface_test.dart

Add timestamp to events from plateform instead of using DateTime.now() at event arrival that can suffer from jitter.
This can be useful to make fft or signal analysis.
I would start this PR as a discussion about the usefulness of this feature or how to implement it
I will provide the iOS implementation in the next few days
- Fix https://github.com/flutter/flutter/issues/26078 event if it is not the same repo the problem is the same
- The API change but most sensor streams users won't need to change anything (if you don't create events like `UserAccelerometerEvent`)

feat(sensors_plus)!: Add support for platform timestamp in event

---

.github/workflows/android_alarm_manager_plus.yaml

Package name in the CI workflow was incorrect, the `_plus_` in the name was missing, so the integration tests didn't run any code. 
- None

ci(android_alarm_manager_plus): Fix integration test example package name

---

packages/battery_plus/battery_plus/macos/Classes/BatteryPlusMacosPlugin.swift

When using a desktop Mac, such as a Mac mini, retrieving the battery level can cause a crash due to an array out-of-bounds error. I added a check to return `-1` when the power sources list is empty.

fix(battery_plus): Fix crash when retrieving battery level on desktop Mac.

---

packages/battery_plus/battery_plus/README.md

Requirements section was outdated, so this PR fixes it.

docs(battery_plus): Update plugin requirements

---

.github/ISSUE_TEMPLATE/BUG.yaml
.github/ISSUE_TEMPLATE/COMPILATION.yaml

Maybe we avoid some of the Android compilation tickets we have been seeing recently.

docs: Add link to gradle plugin docs in COMPILATION.yaml

---

packages/share_plus/share_plus/lib/src/share_plus_web.dart

Adds the missing error handling that can be seen in the `share()` and `shareXFiles()` method.
- Fix #2910

fix(share_plus): #2910 Handle user dismissing dialog on shareUri() in web

---

packages/network_info_plus/network_info_plus/lib/src/network_info_plus_windows.dart
packages/network_info_plus/network_info_plus/pubspec.yaml

Thanks to analyzer on pub.dev I found out that we declared incorrect range of supported win32 versions, so users with `win32` v4 would see errors as some constants are not available there. 
I did the check with `flutter pub downgrade` which brought me win32 v4 
and `flutter analyze` to see the same set of issues as reported on pub.dev:
It looks like not a lot of people had codebases with old win32 versions, so we saw no reports for this issue so far (or I missed them).
In any case in this PR I declared win32 with min 5.4.0 where the constants in question are already in their new place.
I expect this change to be non-breaking for the same reason as why we haven't seen reports for the issue - not a lot of people rely on old win32 version.
Does your PR require plugin users to manually update …

fix(network_info_plus): Avoid usage of unsupported package:win32 versions

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_windows.dart

This PR fixes a type cast error if `digitalProductId` does not exist. 
`[] as Uint8List` causes the following error: `type 'List<dynamic>' is not a subtype of type 'Uint8List' in type cast`

fix(device_info_plus): Fix type cast of digitalProductId on windows

---

.github/dependabot.yml

As discussed internally, we remove the Gradle dependabot config to avoid having an overwhelming amount of PRs opened every month.
Android dependencies should be updated manually, since not all versions are compatible with Flutter, so this requires extra work than just merging them.
- See all Dependabot "java" PRs

ci(all): Remove Gradle Dependabot config

---

packages/battery_plus/battery_plus/macos/PrivacyInfo.xcprivacy
packages/battery_plus/battery_plus/macos/battery_plus.podspec
packages/device_info_plus/device_info_plus/macos/PrivacyInfo.xcprivacy
packages/device_info_plus/device_info_plus/macos/device_info_plus.podspec
packages/network_info_plus/network_info_plus/macos/PrivacyInfo.xcprivacy
packages/network_info_plus/network_info_plus/macos/network_info_plus.podspec
packages/package_info_plus/package_info_plus/macos/PrivacyInfo.xcprivacy
packages/package_info_plus/package_info_plus/macos/package_info_plus.podspec
packages/share_plus/share_plus/macos/PrivacyInfo.xcprivacy
packages/share_plus/share_plus/macos/share_plus.podspec

*This PR is to add privacy manifests to macOS.*
- *Fix #3250*

fix(all): Add macOS Privacy Manifests

---

packages/device_info_plus/device_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml

Due to incompatibility with `web32 (<5.5.1)` and `dart (>=3.5.0)`, I changed the web32 version to use the latest version rather than a range.
- Reported in #3259
- Mentioned here: https://github.com/halildurmus/win32/issues/887#issuecomment-2329109205

chore(all): set `win32` dependency to `^5.5.3`

---

packages/battery_plus/battery_plus/macos/PrivacyInfo.xcprivacy
packages/device_info_plus/device_info_plus/macos/PrivacyInfo.xcprivacy
packages/network_info_plus/network_info_plus/macos/PrivacyInfo.xcprivacy
packages/package_info_plus/package_info_plus/macos/PrivacyInfo.xcprivacy
packages/share_plus/share_plus/macos/PrivacyInfo.xcprivacy

Clean up macOS manifests
- *Fix #3263*

fix(all): Clean up macOS Privacy Manifests

---

packages/device_info_plus/device_info_plus/example/web/index.html
packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart
packages/device_info_plus/device_info_plus/lib/src/model/web_browser_info.dart
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus/test/model/web_browser_info_test.dart

This PR allows device_info_plus to be used in a web project compiled to webasm.
For that a type had to be changed (devicememory became a double?) and one converted from JStype to dart type.
I also took the liberty to update the example "index.html" file, as it was based on a deprecated template and not compatible with webasm compilation.
Most of this commit is a copy of what was done in https://github.com/fluttercommunity/plus_plugins/pull/3161 by @GiacomoPignoni . Credits go to him.
- *Fix #3253*

fix(device_info_plus)!: fixed webasm compliance

---

packages/device_info_plus/device_info_plus/android/build.gradle

when ./gradlew clean
./gradlew build --refresh-dependencies
run on any project including the example project, it throws an error and build fails. Adding lint option in user project does not fix the build, it must be in the package build.gradle.
#3316 #1986 #3110 

fix(device_info_plus): Ignore `MissingPermission` lint error on Android

---

packages/android_intent_plus/README.md
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/IntentSender.java
packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java
packages/android_intent_plus/example/android/app/src/main/AndroidManifest.xml
packages/android_intent_plus/example/integration_test/android_intent_plus_test.dart
packages/android_intent_plus/example/lib/main.dart
packages/android_intent_plus/lib/android_intent.dart
packages/android_intent_plus/test/android_intent_test.dart

Adds getResolvedActivity to return app name, activity name and package name of the default activity that will be resolved for a given intent.
- [x ] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.

feat(android_intent_plus): adds getResolvedActivity method

---

packages/battery_plus/battery_plus/ios/battery_plus/Sources/battery_plus/PrivacyInfo.xcprivacy

While working on #3154 occasionally removed one of keys that is need for iOS privacy manifests.
This PR brings it back.

fix(battery_plus): Bring back entry needed by the iOS privacy manifest

---

packages/share_plus/share_plus/ios/share_plus/Sources/share_plus/PrivacyInfo.xcprivacy

Same as #3323, but for `share_plus` plugin

fix(share_plus): Update iOS privacy manifest

---

packages/share_plus/share_plus/ios/share_plus/Sources/share_plus/FPPSharePlusPlugin.m

On iPhone 13, when sharing an image and the image is very large, the sharing box may occasionally fail to be awakened.
- fix: #3322

fix(share_plus): #3322 Image preview on iOS downscale to avoid issues

---

packages/battery_plus/battery_plus/README.md
packages/battery_plus/battery_plus/example/integration_test/battery_plus_test.dart
packages/battery_plus/battery_plus/lib/battery_plus.dart
packages/battery_plus/battery_plus/macos/battery_plus/Sources/battery_plus/BatteryPlusMacosPlugin.swift

While testing SPM for `battery_plus` was surprised that the check for battery save mode throws `Unimplemented....` on MacOS, because such check is available in MacOS since version 12.0: https://developer.apple.com/documentation/foundation/processinfo/1617047-islowpowermodeenabled
This PR adds implementation for this check and it seems to work fine:

feat(battery_plus): Add battery save mode check on MacOS

---

CONTRIBUTING.md

With recent Melos changes I now have to not only push the new branch to remote, but also specify the tracking information with git command in order to run `melos version...`. Without setting tracking information I see such exception:
Update documentation to mention this requirement.

chore(all): Update the release process docs

---

packages/device_info_plus/device_info_plus/macos/device_info_plus.podspec
packages/device_info_plus/device_info_plus/macos/device_info_plus/Package.swift

Something that was overlooked during SPM migration PRs review - updated paths for privacy manifest files. This PR fixes the issue for `device_info_plus`.
Part of #3346 

fix(device_info_plus): Update privacy manifest paths

---

packages/package_info_plus/package_info_plus/macos/package_info_plus.podspec

Same as #3347 but for `package_info_plus`
Part of #3346 

fix(package_info_plus): Update privacy manifest path

---

packages/share_plus/share_plus/macos/share_plus.podspec

Same as #3348 and #3347, but for `share_plus`.
Part of #3346 

fix(share_plus): Update privacy manifest path

---

packages/network_info_plus/network_info_plus/macos/network_info_plus.podspec

Should be the last in the series related to the issue #3346
Part of #3346 

fix(network_info_plus): Update privacy manifest path on MacOS

---

packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_web_test.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_web.dart

Web apps using file scheme cannot retrieve version.json, `PackageInfoPlusWebPlugin.versionJsonUrl` calls Uri.origin which throws `StateError` if scheme is not `http` or `https`

fix(package_info_plus): add support for file scheme on web

---

packages/android_alarm_manager_plus/example/pubspec.yaml
packages/android_intent_plus/example/pubspec.yaml
packages/battery_plus/battery_plus/example/pubspec.yaml
packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/example/pubspec.yaml
packages/device_info_plus/device_info_plus/pubspec.yaml
packages/device_info_plus/device_info_plus_platform_interface/pubspec.yaml
packages/network_info_plus/network_info_plus/example/pubspec.yaml
packages/network_info_plus/network_info_plus/pubspec.yaml
packages/network_info_plus/network_info_plus_platform_interface/pubspec.yaml
packages/package_info_plus/package_info_plus/example/pubspec.yaml
packages/package_info_plus/package_info_plus/pubspec.yaml
packages/package_info_plus/package_info_plus_platform_interface/pubspec.yaml
packages/sensors_plus/sensors_plus/example/pubspec.yaml
packages/sensors_plus/sensors_plus/pubspec.yaml
packages/sensors_plus/sensors_plus_platform_interface/pubspec.yaml
packages/share_plus/share_plus/example/pubspec.yaml
packages/share_plus/share_plus/pubspec.yaml
packages/share_plus/share_plus_platform_interface/pubspec.yaml

Switching to a range for `flutter_lints` because 5.0.0 requires latest dart as it was mentioned in #3366, while we have no reasons to make min requirements that high.
Fixes #3366

refactor(all): Use range of flutter_lints for broader compatibility

---

packages/share_plus/share_plus/ios/share_plus/Sources/share_plus/FPPSharePlusPlugin.m

Fix the warnings: "A function declaration without a prototype is deprecated in all versions of C"

fix(share_plus): A function declaration without a prototype is deprecated in all versions of C

---

packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart

I'm not sure why this part is hardcoded. But if we do it this way, it means our local tests might not pass.

fix(device_info_plus): fix the error in the e2e test.

---

CONTRIBUTING.md

Found a much simpler way to version packages with Melos by starting versioning on the `main` branch. 
Tested with #3394 - seems to be working.

chore(docs): Simplify release creation guide

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_web.dart

Fixes *type 'Null' is not a subtype of type 'double'* for deviceMemory in webBrowserInfo on Safari and Firefox
- Fix #3391 
- Related: https://github.com/dart-lang/web/issues/326

fix(device_info_plus): device memory null error on Safari and Firefox

---

packages/device_info_plus/device_info_plus/macos/device_info_plus/Package.swift

It is just separation into smaller commits of #3396 to generate meaningful changelogs during the next release.
I did testing for MacOS and iOS with Flutter 3.27.1 and enabled SPM and can confirm that the issue happens only on MacOS due to a redundant comma. 
I will do the same for `package_info_plus` and check the rest of plugins.

fix(device_info_plus): Resolve compilation issues with SPM enabled

---

packages/package_info_plus/package_info_plus/macos/package_info_plus/Package.swift

Same as #3405 but for package_info_plus.
P.S. Checked the rest of plugins and didn't find issues with missing or redundant separators.

fix(package_info_plus): Resolve compilation issues with SPM enabled

---

packages/network_info_plus/network_info_plus/example/ios/Runner/AppDelegate.swift
packages/network_info_plus/network_info_plus/ios/network_info_plus/Sources/network_info_plus/FPPNetworkInfoPlusPlugin.m

Based on information provided in https://github.com/fluttercommunity/plus_plugins/issues/1652#issuecomment-2373580942 changed the iOS implementation to retrieve IP address to get values even when device uses not `en0` interface for Wi-Fi.
Additionally did minor improvements with log entry when interfaces info retrieval fails and changed the comparison to simplify it a bit.
Fixes #1652

fix(network_info_plus): Improve Wi-Fi IP address retrieval on iOS to avoid null

---

packages/connectivity_plus/connectivity_plus/README.md

This is merely keeping the readme up to date with what was described in the changelog for version 6.0.1.

docs(connectivity_plus): update requirements

---

.github/workflows/stale.yml

This GH action closes PRs and Issues that have been closed and without activity for a year.
This is to avoid spam on older issues and force users to create new tickets if they have problems.
The default is 365 days since last activity. We can lower this value to something shorter e.g. 90 days.
- None

ci: Automatically lock issues and PRs older than a year

---

packages/package_info_plus/package_info_plus/README.md
packages/package_info_plus/package_info_plus/lib/package_info_plus.dart

This PR fixes two broken doc references: one in `src/package_info_plus_linux.dart` and one in `package_info_plus.dart`. Also fixes warnings from `flutter analyze` about unnecessary library names.
No related issues.

docs(package_info_plus): doc ref links and unnecessary library names

---

CONTRIBUTING.md

I want to add some notes to the Contributing guidelines regarding large PRs (usually are for new features but always applies), as they should be discussed beforehand.
I may add some other notes to the Contributing file before merging.
- None

docs: Add note regarding large PRs to CONTRIBUTING.md

---

packages/android_intent_plus/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java

Currently, when sending an intent, any native errors occur silently without any notification to the flutter side of code.
This adds error forwarding back to flutter through the MethodCaller.
This is achieved by wrapping the whole caller in a try/catch
This can be tested by trying to send an intent to an Activity that doesn't exist.
- Previous behaviour, it would show a native error in the log but this is not catchable in flutter code
- New behaviour forwards the error and allows it to be caught
No related issues exist for this

fix(android_intent_plus): adds error catching and forwarding

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/DeviceInfoPlusPlugin.kt
packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt
packages/device_info_plus/device_info_plus/example/integration_test/device_info_plus_test.dart
packages/device_info_plus/device_info_plus/example/lib/main.dart
packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_fake.dart
packages/device_info_plus/device_info_plus/test/model/android_device_info_test.dart

This PR updates the functionality of the NAME property to now include and send the customer's device name. This enhancement ensures that the application can capture and utilize the user device name for better identification, personalization, and debugging. Prior to this change, the NAME property did not include device-specific details. This update significantly improves logging, user tracking, and system behavior analysis. 
In the current package, the user is unable to obtain the Android user's custom device name
e.g.
- Fix #3437 
- Related #3437 

feat(device_info_plus): Add User Device Name in Android (PR #3437)

---

packages/package_info_plus/package_info_plus/macos/package_info_plus/Sources/package_info_plus/FPPPackageInfoPlusPlugin.m

Fixes compilation warning on macOS
- Closes #3459 

fix(package_info_plus): fix macOS compilation warning

---

packages/package_info_plus/package_info_plus/example/ios/Flutter/AppFrameworkInfo.plist
packages/package_info_plus/package_info_plus/example/ios/Runner.xcodeproj/project.pbxproj
packages/package_info_plus/package_info_plus/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/package_info_plus/package_info_plus/example/ios/Runner/AppDelegate.swift
packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/package_info_plus/test/package_info_test.dart

This commit addresses an issue where the `installTime` was not being properly serialized due to being a `DateTime` object. When attempting to convert the object to JSON, an error occurred as `DateTime` is not natively encodable. The `installTime` is now explicitly converted to a string before being included in the JSON, preventing the serialization failure.
This PR addresses an issue where the `installTime` (a `DateTime` object) was not being properly serialized into JSON, causing errors when trying to encode the object. The `installTime` is now explicitly converted to a string before it’s included in the JSON, ensuring compatibility with the encoding process. This change prevents the "Converting object to an encodable object failed" error and allows for correct JSON handling.
- Fixes …

fix(package_info_plus): data serialization converts installTime to String instead of DateTime

---

packages/device_info_plus/device_info_plus/macos/device_info_plus/Sources/device_info_plus/SystemUUID.swift

Fix memory leak when call DeviceInfoPlugin().macOsInfo in macOS.
[[Bug]: device_info_plus memory leak in macOS](https://github.com/fluttercommunity/plus_plugins/issues/3473)

fix(device_info_plus): fix memory leak when calling DeviceInfoPlugin().macOsInfo

---

packages/package_info_plus/package_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/packageinfo/PackageInfoPlugin.kt
packages/package_info_plus/package_info_plus/example/integration_test/package_info_plus_test.dart
packages/package_info_plus/package_info_plus/example/lib/main.dart
packages/package_info_plus/package_info_plus/ios/package_info_plus/Sources/package_info_plus/FPPPackageInfoPlusPlugin.m
packages/package_info_plus/package_info_plus/lib/package_info_plus.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_linux.dart
packages/package_info_plus/package_info_plus/lib/src/package_info_plus_windows.dart
packages/package_info_plus/package_info_plus/macos/package_info_plus/Sources/package_info_plus/FPPPackageInfoPlusPlugin.m
packages/package_info_plus/package_info_plus/test/package_info_test.dart
packages/package_info_plus/package_info_plus_platform_interface/lib/method_channel_package_info.dart
packages/package_info_plus/package_info_plus_platform_interface/lib/package_info_data.dart

Adds update time
- On Android, returns `PackageManager.lastUpdateTime`
- On iOS and macOS, return the last modified date of the app main bundle
- On Windows and Linux, returns the last modified date of the app executable.
If the last modified date is not available, returns `null`
Unimplemented on web
Also refactored getting install and update time code on Android, iOS, macOS and Linux
- Closes #3430

feat(package_info_plus): add update time

---

packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java

Removes an import for the no longer existing `io.flutter.view.FlutterNativeView` class in Android.
This fixes build issues seen in Flutter starting with version `3.29.0`.
Fix #3476 
- [~] The analyzer (`flutter analyze`) does not report any problems on my PR.
^ It *does* find issues - but they are not related to my changes

fix(alarm_manager_plus): removed import that broke build

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_windows.dart
packages/device_info_plus/device_info_plus/pubspec.yaml

Fixes windows code for https://github.com/fluttercommunity/plus_plugins/pull/3482
n/a

chore(deps): bump win32_registry from 1.1.5 to 2.0.1 in /packages/device_info_plus/device_info_plus

---

packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt

`Settings.Global.getString()` can return null. And `Any` is not a subtype of nullable, so if `getString()` returns null the code will crash. Kotlin did not warn us about this.
https://developer.android.com/reference/android/provider/Settings.Global#getString(android.content.ContentResolver,%20java.lang.String)
- Fix #3505 

fix(device_info_plus): handle nullability on getString(DEVICE_NAME)

---

.github/workflows/all_plugins.yaml

This PR adds a CI jobs that runs the analyzer on all plugins. Similar to the CI job that runs tests. This job is not marked as mandatory (yet).
I will fix the individual projects one by one in separated PRs
- None

ci: run analyze on all plugins

---

packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart

Fixes dart analysis warnings in plugin.
- Related to PR: #3513 

chore(android_alarm_manager_plus): fix analysis issues in comments

---

packages/device_info_plus/device_info_plus/lib/src/device_info_plus_windows.dart
packages/device_info_plus/device_info_plus/lib/src/model/android_device_info.dart
packages/device_info_plus/device_info_plus/test/device_info_plus_linux_test.dart
packages/device_info_plus/device_info_plus/test/device_info_plus_web_test.dart
packages/device_info_plus/device_info_plus/test/device_info_plus_windows_test.dart

Fixes analysis issues in plugins and tests
- Related #3513 

chore(device_info_plus): fix analysis issues in plugin and tests

---

packages/network_info_plus/network_info_plus/lib/src/network_info_plus_windows.dart

Fixes analyzer warnings in the windows implementation
- related #3513 

fix(network_info_plus): fix deprecated member use in Windows implementation

---

packages/sensors_plus/sensors_plus/example/lib/main.dart

Ignoring the "Don't use 'BuildContext's across async gaps." in the example code.
- related: #3513 

chore(sensors_plus): Ignore BuildContext across async gaps warning in example

---

packages/share_plus/share_plus/lib/src/share_plus_linux.dart
packages/share_plus/share_plus/lib/src/share_plus_windows.dart

Removes unnecessary library name, as reported by dart analyzer warning that it is not necessary.
- related #3513

chore(share_plus): remove unnecessary library name

---

packages/network_info_plus/network_info_plus/lib/network_info_plus.dart

dart.library.html isn't supported when exporting with flutter build web --wasm and result in an compilation error

chore(network_info_plus): Fix imports on wasm
